import test from 'node:test';import assert from 'node:assert/strict';import {fixture} from './support.mjs';import {handler} from '../http.mjs';import {Workspace} from '../service.mjs';import {AGREEMENT_VERSION,AGREEMENT_HASH} from '../agreement.mjs';import {authenticate} from '../security.mjs';
async function request(run,action,{method='GET',body,cookie=''}={}){const result={headers:{}};await run({url:'/api/workspace?action='+action,method,body,headers:{origin:'https://class.invalid','content-type':'application/json',cookie},socket:{remoteAddress:'127.0.0.1'}},{setHeader:(k,v)=>result.headers[k]=v,end:data=>result.body=JSON.parse(data),set statusCode(v){result.status=v;}});return result;}
test('first student session is gated until explicit current agreement, saved once without altering credentials or old works',async t=>{
 const f=await fixture(2);t.after(f.close);await f.db.query('update rib.students set sharing_agreement=null');const original=await f.db.query('select * from rib.credentials order by student_id'),run=handler({db:f.db,store:f.store,origin:'https://class.invalid',rateSecret:'local',secure:true});
 const login=await request(run,'login',{method:'POST',body:{term:'11501',studentId:'11500001',code:'012345'}});assert.equal(login.status,200);const cookie=login.headers['Set-Cookie'].split(';')[0];let home=(await request(run,'home',{cookie})).body.data;assert.equal(home.agreementRequired,true);assert.deepEqual(home.activities,[]);assert.equal(home.sharingAgreement.version,AGREEMENT_VERSION);
 assert.equal((await request(run,'board',{cookie})).status,403);assert.equal((await request(run,'ensureWork',{method:'POST',cookie,body:{activityId:'w4-demo'}})).status,403);
 for(const body of [{accepted:false,version:AGREEMENT_VERSION},{accepted:true,version:'old'}])assert.equal((await request(run,'agreement',{method:'POST',cookie,body})).status,400);
 const accepted={method:'POST',cookie,body:{accepted:true,version:AGREEMENT_VERSION,studentId:'11500002'}};assert.equal((await request(run,'agreement',accepted)).status,200);const rows=await f.db.query('select * from rib.students order by student_id');assert.equal(rows[0].sharing_agreement.documentHash,AGREEMENT_HASH);assert.equal(rows[1].sharing_agreement,null,'cannot accept on another student behalf');
 const timestamp=rows[0].sharing_agreement.acceptedAt;await request(run,'agreement',accepted);assert.equal((await f.db.query("select count(*)::int as n from rib.events where kind='sharing-agreement'"))[0].n,1);assert.equal((await f.db.query("select sharing_agreement from rib.students where student_id='11500001'"))[0].sharing_agreement.acceptedAt,timestamp);
 home=(await request(run,'home',{cookie})).body.data;assert.equal(home.agreementRequired,false);assert.ok(home.activities.length);assert.equal((await f.db.query('select count(*)::int as n from rib.publications'))[0].n,0);
 // Login may upgrade the hash, but the six digits and identity are unchanged.
 const session=await new Workspace(f.db,f.store).login({term:'11501',studentId:'11500001',code:'012345'},'retry');assert.equal((await authenticate(f.db,session.token)).studentId,'11500001');assert.equal((await f.db.query('select revision from rib.credentials where student_id=$1',['11500001']))[0].revision,original[0].revision);
 await f.db.query("update rib.students set sharing_agreement=jsonb_set(sharing_agreement,'{version}','\"old\"') where student_id='11500001'");assert.equal((await request(run,'home',{cookie})).body.data.agreementRequired,true);assert.equal((await request(run,'ensureWork',{method:'POST',cookie,body:{activityId:'w4-demo'}})).status,403);
});
test('accepting agreement never republishes old versions and opt-out remains across repeated agreement',async t=>{
 const f=await fixture(2);t.after(f.close);const s=new Workspace(f.db,f.store),p=f.people[0],w=await s.ensureWork(p,{activityId:'w4-demo'});await f.db.query("insert into rib.versions(id,work_id,ordinal,media,request_id) values('old-version',$1,1,'[]','old-import')",[w.id]);await f.db.query("insert into rib.publications(id,version_id) values('old-publication','old-version')");await s.consent(p,{workId:w.id,consent:false});await f.db.query('update rib.students set sharing_agreement=null');await s.agreement(p,{accepted:true,version:AGREEMENT_VERSION});await s.agreement(p,{accepted:true,version:AGREEMENT_VERSION});assert.equal((await f.db.query('select sharing_opt_out from rib.members where work_id=$1',[w.id]))[0].sharing_opt_out,true);assert.equal((await s.gallery()).items.length,0);await s.consent(p,{workId:w.id,consent:true});assert.equal((await s.gallery()).items.length,0);assert.equal((await f.db.query("select status from rib.publications where id='old-publication'"))[0].status,'withdrawn');await assert.rejects(s.agreement(f.teacher,{accepted:true,version:AGREEMENT_VERSION}),/學生/);
});
