import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './support.mjs';
import {Workspace} from '../service.mjs';
import {snapshot,restoreEmpty} from '../backup.mjs';
const seed=async f=>{const service=new Workspace(f.db,f.store),w=await service.ensureWork(f.people[0],{activityId:'w4-demo'});await f.db.query("insert into rib.versions(id,work_id,ordinal,media,metadata,request_id) values('v1',$1,1,'[]','{}','request1')",[w.id]);await f.db.query("insert into rib.ai_readings(id,version_id,comment_a,comment_b,source_hash,image_key,teacher_notes,status,created_by,published_at) values('reading1','v1','甲內容','乙內容','hash','private/reading.jpg','{\"judgment\":\"秘密判讀依據\"}','published','fixture',now())");return {service,w};};
test('private reading belongs to author; peer exhibit access and assigned review do not disclose it',async t=>{const f=await fixture();t.after(f.close);const {service,w}=await seed(f);await f.db.query("update rib.activities set phase='exhibit'");assert.equal((await service.work(f.people[1],w.id)).id,w.id);await assert.rejects(service.aiReading(f.people[1],{readingId:'reading1'}),e=>e.status===403);const r=await service.aiReading(f.people[0],{readingId:'reading1'});assert.equal(r.commentA,'甲內容');assert.equal(r.ordinal,1);assert.ok(!JSON.stringify(r).includes('秘密'));assert.equal(r.teacherNotes,undefined);assert.equal(r.source_hash,undefined);assert.equal((await service.aiReading(f.teacher,{readingId:'reading1'})).teacherNotes.judgment,'秘密判讀依據');const wrongTeacher={role:'teacher',email:'outside@example.invalid',teacher:{scopes:[{term:'11501',className:'102'}]}};await assert.rejects(service.aiReading(wrongTeacher,{readingId:'reading1'}),e=>e.status===403);await f.db.query("update rib.activities set phase='review'");await f.db.query("insert into rib.reviews(id,activity_id,target_work_id,reviewer_id,term,version_id,status) values('review1','w4-demo',$1,$2,'11501','v1','assigned')",[w.id,f.people[1].studentId]);await assert.rejects(service.aiReading(f.people[1],{readingId:'reading1'}),e=>e.status===403);});
test('W5 shows prior W4 owned exercise even before W5 upload; drafts, foreign term and peers are excluded',async t=>{const f=await fixture();t.after(f.close);const {service}=await seed(f);await f.db.query("update rib.activities set kind='w5-personal' where id='w5-demo'");assert.equal((await service.board(f.people[0],{activityId:'w5-demo'})).aiReadings.length,1);assert.equal((await service.board(f.people[1],{activityId:'w5-demo'})).aiReadings.length,0);assert.equal((await service.board(f.people[0],{activityId:'w4-demo'})).aiReadings.length,1);await f.db.query("update rib.ai_readings set status='draft'");assert.equal((await service.board(f.people[0],{activityId:'w5-demo'})).aiReadings.length,0);await assert.rejects(service.aiReading(f.people[0],{readingId:'reading1'}),e=>e.status===403);assert.equal((await service.board(f.teacher,{activityId:'w5-demo',className:'101'})).aiReadings.length,1);await f.db.query("update rib.ai_readings set status='published'");await f.db.query("update rib.activities set archived=true where id='w4-demo'");assert.equal((await service.board(f.people[0],{activityId:'w5-demo'})).aiReadings.length,0);await assert.rejects(service.aiReading(f.people[0],{readingId:'reading1'}),e=>e.status===403);});
test('reading stays bound to V1 after new submission and enters private backup, not public gallery',async t=>{const f=await fixture();t.after(f.close);const {service,w}=await seed(f);await f.db.query("insert into rib.versions(id,work_id,ordinal,media,metadata,request_id) values('v2',$1,2,'[]','{}','request2')",[w.id]);assert.equal((await service.aiReading(f.people[0],{readingId:'reading1'})).versionId,'v1');const backup=await snapshot(f.db);assert.equal(backup.format,'rib-backup-v4');assert.equal(backup.tables.ai_readings[0].teacher_notes.judgment,'秘密判讀依據');assert.ok(!JSON.stringify(await service.gallery()).includes('甲內容'));await assert.rejects(f.db.query("update rib.ai_readings set version_id='missing'"));});

test('unclear drawing can show a task note without fabricating a pair',async t=>{const f=await fixture();t.after(f.close);const {service}=await seed(f);await f.db.query("update rib.ai_readings set comment_a='',comment_b='',task_note='請補成三格並釐清動作'");const r=await service.aiReading(f.people[0],{readingId:'reading1'});assert.equal(r.commentA,'');assert.equal(r.commentB,'');assert.equal(r.taskNote,'請補成三格並釐清動作');assert.equal((await service.board(f.people[0],{activityId:'w4-demo'})).aiReadings[0].has_pair,false);await assert.rejects(f.db.query("update rib.ai_readings set task_note=''"));});

test('teacher-authorized record is visible only to owner; internal notes remain private',async t=>{const f=await fixture();t.after(f.close);const {service}=await seed(f);const record={published:true,kind:'joint',disclosure:'共同判讀摘要',teacherReply:'老師說仍不確定',basis:'證據不足',internalSecret:'不可公開'};await f.db.query("update rib.ai_readings set teacher_notes=teacher_notes || $1::jsonb",[JSON.stringify({studentRecord:record})]);const own=await service.aiReading(f.people[0],{readingId:'reading1'});assert.equal(own.studentRecord.kind,'joint');assert.equal(own.studentRecord.teacherReply,'老師說仍不確定');assert.equal(own.studentRecord.basis,'證據不足');assert.equal(own.studentRecord.internalSecret,undefined);assert.equal(own.teacherNotes,undefined);await assert.rejects(service.aiReading(f.people[1],{readingId:'reading1'}),e=>e.status===403);await f.db.query("update rib.ai_readings set teacher_notes=jsonb_set(teacher_notes,'{studentRecord,published}','false')");assert.equal((await service.aiReading(f.people[0],{readingId:'reading1'})).studentRecord,null);});
