import test from 'node:test';import assert from 'node:assert/strict';import sharp from 'sharp';
import {fixture} from './support.mjs';import {Workspace} from '../service.mjs';import {sha} from '../security.mjs';import {upgradeGroups} from '../group-upgrade.mjs';
async function setup(t){const f=await fixture();t.after(f.close);return {...f,s:new Workspace(f.db,f.store)};}
const leave=(s,p,w,revision=0)=>s.leaveGroup(p,{workId:w.id,expectedRevision:revision,confirmed:true});
test('wrong or self-created empty groups can be left and rejoined, without moving classmates automatically',async t=>{const f=await setup(t),{s}=f,[a,b]=f.people,w=await s.ensureWork(a,{activityId:'w5-demo'}),wrong=await s.ensureWork(b,{activityId:'w5-demo'});
 await assert.rejects(s.invitePreview(a,{workId:w.id,seats:[2]}),/離開這個小組/);
 await leave(s,b,wrong);await s.invite(a,{workId:w.id,seats:[2],expectedStudentIds:[b.studentId]});assert.equal((await s.ensureWork(b,{activityId:'w5-demo'})).id,w.id);
 const board=await s.board(f.teacher,{activityId:'w5-demo',className:'101'});assert.equal(board.works.length,1);assert.equal((await f.db.query('select * from rib.works where id=$1',[wrong.id])).length,1);
 await s.consent(b,{workId:w.id,consent:false});await leave(s,b,w);await assert.rejects(s.invite(b,{workId:w.id,studentIds:[f.people[2].studentId]}));await s.invite(a,{workId:w.id,studentIds:[b.studentId]});assert.equal((await f.db.query('select sharing_opt_out from rib.members where work_id=$1 and student_id=$2',[w.id,b.studentId]))[0].sharing_opt_out,true);
});
test('leave is self-only, revision checked, group-only, allowed when closed but blocked when archived',async t=>{const f=await setup(t),{s}=f,[a,b]=f.people,w=await s.ensureWork(a,{activityId:'w5-demo'});
 await assert.rejects(leave(s,b,w));await assert.rejects(leave(s,f.teacher,w));await assert.rejects(leave(s,a,w,4),/更新/);await assert.rejects(s.leaveGroup(a,{workId:w.id,expectedRevision:0}),/確認/);
 const personal=await s.ensureWork(a,{activityId:'w4-demo'});await assert.rejects(leave(s,a,personal),/小組/);
 await f.db.query("update rib.activities set accepting=false where id='w5-demo'");await leave(s,a,w);
 const w2=await s.ensureWork(b,{activityId:'w4-demo'});await f.db.query("update rib.activities set archived=true where id='w4-demo'");await assert.rejects(leave(s,b,w2),/封存/);
});
test('leaving saved work preserves versions and former roster, removes own selection, holds publication and invalidates prepared uploads',async t=>{const f=await setup(t),{s}=f,[a,b]=f.people,w=await s.ensureWork(a,{activityId:'w5-demo'});await s.invite(a,{workId:w.id,studentIds:[b.studentId]});
 const bytes=await sharp({create:{width:32,height:32,channels:3,background:'#aaa'}}).png().toBuffer(),files=[1,2].map(()=>({bytes:bytes.length,mime:'image/png',sha256:sha(bytes)}));
 const prepare=async(p,rev,id)=>{const u=await s.prepare(p,{workId:w.id,requestId:id,expectedRevision:rev,files,topics:['A02','B02']});for(const file of (await f.db.query('select files from rib.uploads where id=$1',[u.ticketId]))[0].files)f.store.objects.set(file.key,bytes);return u;};
 const first=await s.finalize(a,{ticketId:(await prepare(a,0,'first')).ticketId});await s.selectionSave(b,{versionIds:[first.versionId],expectedRevision:0});const pending=await prepare(a,1,'pending');await leave(s,b,w,1);
 assert.equal((await f.db.query('select * from rib.versions where work_id=$1',[w.id])).length,1);assert.deepEqual((await f.db.query('select version_ids from rib.selections where student_id=$1',[b.studentId]))[0].version_ids,[]);
 assert.equal((await s.gallery()).items.length,0);assert.equal((await s.work(a,w.id,{write:true})).publication_hold,true);await assert.rejects(s.work(b,w.id,{write:true}));await assert.rejects(s.finalize(a,{ticketId:pending.ticketId}),/更新|版本/);
 await assert.rejects(s.selectionSave(b,{versionIds:[first.versionId],expectedRevision:2}),/自己的/);await assert.rejects(s.invite(a,{workId:w.id,studentIds:[b.studentId]}),/已有共同作品/);
 const board=await s.board(f.teacher,{activityId:'w5-demo',className:'101'});assert.equal(board.works[0].members.find(m=>m.student_id===b.studentId).status,'declined');assert.equal((await f.db.query("select * from rib.events where kind='group-leave'")).length,1);
});
test('legacy conversion is validated, atomic and idempotent',async t=>{const f=await setup(t),{s}=f,[a,b]=f.people,w=await s.ensureWork(a,{activityId:'w5-demo'});await f.db.query("insert into rib.members(work_id,term,student_id,status) values($1,'11501',$2,'invited')",[w.id,b.studentId]);assert.equal((await upgradeGroups(f.db)).members,1);
 await f.db.query("update rib.students set class_name='102' where student_id=$1",[b.studentId]);await assert.rejects(upgradeGroups(f.db,{apply:true}),/validation/);assert.equal((await f.db.query('select status from rib.members where student_id=$1',[b.studentId]))[0].status,'invited');await f.db.query("update rib.students set class_name='101' where student_id=$1",[b.studentId]);assert.equal((await upgradeGroups(f.db,{apply:true})).members,1);assert.equal((await upgradeGroups(f.db,{apply:true})).members,0);assert.equal((await s.work(b,w.id,{write:true})).own,true);await assert.rejects(s.invitation(b,{}),/已改為/);
});

test('HTTP leave requires same-origin authenticated POST and cannot remove another student',async t=>{const {handler}=await import('../http.mjs'),{createSession}=await import('../security.mjs');const f=await setup(t),p=f.people[0],w=await f.s.ensureWork(p,{activityId:'w5-demo'});await f.s.invite(p,{workId:w.id,studentIds:[f.people[1].studentId]});const session=await createSession(f.db,{role:'student',term:p.term,studentId:p.studentId,revision:1}),run=handler({db:f.db,store:f.store,origin:'https://class.invalid',rateSecret:'test'});const request=async(method,origin,token)=>{const r={};await run({url:'/api/workspace?action=leaveGroup',method,body:{workId:w.id,expectedRevision:0,confirmed:true,studentId:f.people[1].studentId},headers:{origin,'content-type':'application/json',cookie:'rib_session='+token}},{setHeader:()=>{},set statusCode(v){r.status=v},end:b=>r.body=JSON.parse(b)});return r;};assert.equal((await request('GET','https://class.invalid',session.token)).status,405);assert.equal((await request('POST','https://bad.invalid',session.token)).status,403);assert.equal((await request('POST','https://class.invalid','')).status,401);assert.equal((await request('POST','https://class.invalid',session.token)).status,200);assert.equal((await f.s.work(f.people[1],w.id,{write:true})).own,true);await assert.rejects(f.s.work(p,w.id,{write:true}));});

test('legacy five-person groups are preserved and conversion cannot expose existing works',async t=>{const f=await fixture(5);t.after(f.close);const s=new Workspace(f.db,f.store),a=f.people[0],w=await s.ensureWork(a,{activityId:'w5-demo'});const bytes=await sharp({create:{width:30,height:30,channels:3,background:'#aaa'}}).png().toBuffer(),file={bytes:bytes.length,mime:'image/png',sha256:sha(bytes)};const u=await s.prepare(a,{workId:w.id,requestId:'legacy',expectedRevision:0,files:[file,file],topics:['A02','B02']});for(const row of (await f.db.query('select files from rib.uploads where id=$1',[u.ticketId]))[0].files)f.store.objects.set(row.key,bytes);await s.finalize(a,{ticketId:u.ticketId});for(const p of f.people.slice(1))await f.db.query("insert into rib.members(work_id,term,student_id,status) values($1,'11501',$2,'invited')",[w.id,p.studentId]);assert.equal((await s.gallery()).items.length,0);const report=await upgradeGroups(f.db,{apply:true});assert.equal(report.members,4);assert.equal(report.preservedOversizedGroups,1);assert.equal(report.heldWorks,1);assert.equal((await s.gallery()).items.length,0);assert.equal((await f.db.query("select * from rib.members where work_id=$1 and status='confirmed'",[w.id])).length,5);assert.equal((await f.db.query('select * from rib.versions where work_id=$1',[w.id])).length,1);assert.equal((await s.work(a,w.id)).publication_hold,true);});
