import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './support.mjs';
import {handler} from '../http.mjs';
async function request(run,{action='home',method='GET',body,origin='https://class.invalid',cookie='' }={}){let result={headers:{}};const req={url:'/api/workspace?action='+action,method,body,headers:{origin,cookie,'content-type':'application/json'},socket:{remoteAddress:'127.0.0.1'}};const res={setHeader:(k,v)=>result.headers[k]=v,end:data=>{result.status=res.statusCode;result.body=JSON.parse(data);}};await run(req,res);return result;}
test('HTTP rejects cross-site writes, oversized JSON, expired sessions, GET mutations and disabled rollout',async t=>{const f=await fixture();t.after(f.close);const options={db:f.db,store:f.store,origin:'https://class.invalid',rateSecret:'test',secure:true},run=handler(options);assert.equal((await request(run)).status,401);assert.equal((await request(handler({...options,enabled:false}))).status,503);assert.equal((await request(run,{action:'login',method:'POST',origin:'https://attacker.invalid',body:{}})).status,403);assert.equal((await request(run,{action:'login',method:'POST',body:{x:'a'.repeat(32001)}})).status,413);
const result=await request(run,{action:'login',method:'POST',body:{term:'11501',studentId:'11500001',code:'012345'}});assert.equal(result.status,200);assert.match(result.headers['Set-Cookie'],/HttpOnly; SameSite=Lax;.*Secure/);assert.ok(!JSON.stringify(result.body).includes('token'));const cookie=result.headers['Set-Cookie'].split(';')[0];assert.equal((await request(run,{cookie,action:'ensureWork'})).status,405);assert.equal((await request(run,{cookie})).status,200);await f.db.query("update rib.sessions set expires_at=now()-interval '1 second'");assert.equal((await request(run,{cookie})).status,401);
});
test('browser database roles cannot see private schema; RLS enabled on every table',async t=>{const f=await fixture();t.after(f.close);const tables=await f.db.query("select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='rib' and c.relkind='r'");assert.ok(tables.length>10&&tables.every(t=>t.relrowsecurity));await f.pg.exec('create role rib_untrusted; set role rib_untrusted;');await assert.rejects(f.db.query('select * from rib.credentials'),/permission denied/);await f.pg.exec('reset role;');});
