import {test} from 'node:test';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import {fixture} from './support.mjs';
import {Workspace} from '../service.mjs';
import {sha} from '../security.mjs';
import {setupLateCheckpoints} from '../late-setup.mjs';
import {snapshot,restoreEmpty} from '../backup.mjs';
import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
async function setup(t){const f=await fixture(5);t.after(f.close);await setupLateCheckpoints(f.db,{apply:true});const s=new Workspace(f.db,f.store);const [a]=await f.db.query("select * from rib.activities where kind='w14-public-proposal' and not coalesce((legacy->>'testOnly')::boolean,false)");const [b]=await f.db.query("select * from rib.activities where kind='w15-argument-poster' and not coalesce((legacy->>'testOnly')::boolean,false)");await f.db.query('update rib.activities set accepting=true where id=any($1::text[])',[[a.id,b.id]]);return {...f,s,a,b};}
async function revision(f,id){return (await f.db.query('select revision from rib.works where id=$1',[id]))[0].revision;}
async function submit(f,p,w,req,poster=false){const files=poster?[await sharp({create:{width:3600,height:5100,channels:3,background:'white'}}).png().toBuffer()]:[];const prepared=await f.s.prepare(p,{workId:w.id,requestId:req,expectedRevision:await revision(f,w.id),title:'虛構測試作品',text:'建議增設公共資訊，並試辦兩週。',recipient:'虛構圖書館',channel:'電子郵件',files:files.map(b=>({bytes:b.length,mime:'image/png',sha256:sha(b)}))});if(prepared.versionId)return prepared;const [ticket]=await f.db.query('select files from rib.uploads where id=$1',[prepared.ticketId]);ticket.files.forEach((v,i)=>f.store.objects.set(v.key,files[i]));return f.s.finalize(p,{ticketId:prepared.ticketId});}
async function control(f,a,op,extra={}){const [c]=await f.db.query('select revision from rib.late_controls where activity_id=$1 and class_name=$2',[a.id,'101']);return f.s.lateControl(f.teacher,{activityId:a.id,className:'101',operation:op,confirm:true,expectedRevision:c?.revision||0,...extra});}
async function receipt(f,p,w,req='receipt'){const bytes=await sharp({create:{width:200,height:100,channels:3,background:'red'}}).png().toBuffer();const input={workId:w.id,requestId:req,sent:true,date:'2026-10-02',caseNumber:'PRIVATE-CASE',reply:'PRIVATE-REPLY',receiptUrl:'https://example.invalid/receipt-private',files:[{bytes:bytes.length,mime:'image/png',sha256:sha(bytes)}]},u=await f.s.lateEvidencePrepare(p,input);const [r]=await f.db.query('select files from rib.late_deliveries where id=$1',[u.ticketId]);f.store.objects.set(r.files[0].key,bytes);await f.s.lateEvidenceFinalize(p,{ticketId:u.ticketId});return u;}
test('late setup is read-only by default, repeatable and leaves old activities/credentials intact',async t=>{const f=await fixture();t.after(f.close);const old=await f.db.query('select * from rib.activities order by id'),creds=await f.db.query('select * from rib.credentials');const plan=await setupLateCheckpoints(f.db);assert.equal(plan.needed.length,4);assert.equal(plan.created.length,0);await setupLateCheckpoints(f.db,{apply:true});assert.equal((await setupLateCheckpoints(f.db,{apply:true})).created.length,0);assert.deepEqual(await f.db.query("select * from rib.activities where id in('w4-demo','w5-demo') order by id"),old);assert.deepEqual(await f.db.query('select * from rib.credentials'),creds);assert.equal((await f.db.query("select count(*)::int n from rib.activities where kind like '%argument%' and accepting"))[0].n,0);});
test('four proposal authors each personally confirm; a fifth is refused; old direct join stays intact',async t=>{
 const f=await setup(t),[a,b,c,d,e]=f.people,w=await f.s.ensureWork(a,{activityId:f.a.id});
 await f.s.invite(a,{workId:w.id,studentIds:[b.studentId,c.studentId,d.studentId]});
 await assert.rejects(submit(f,a,w,'before-confirm'),/確認/);
 await assert.rejects(f.s.invite(a,{workId:w.id,studentIds:[e.studentId]}),/最多 4 人/);
 await assert.rejects(f.s.invitation(e,{activityId:f.a.id,workId:w.id,accept:true}),/邀請/);
 for(const p of [b,c])await f.s.invitation(p,{activityId:f.a.id,workId:w.id,accept:true});
 await assert.rejects(submit(f,a,w,'fourth-unconfirmed'),/確認/);
 await f.s.invitation(d,{activityId:f.a.id,workId:w.id,accept:true});
 assert.equal((await f.s.board(d,{activityId:f.a.id})).works.length,1);
 await submit(f,a,w,'confirmed');
 await assert.rejects(f.s.leaveGroup(b,{workId:w.id,expectedRevision:await revision(f,w.id),confirmed:true}),/原組/);
 const old=await f.s.ensureWork(a,{activityId:'w5-demo'});
 await f.s.invite(a,{workId:old.id,studentIds:[b.studentId,c.studentId,d.studentId]});
 assert.equal((await f.s.board(d,{activityId:'w5-demo'})).works.length,1);
});
test('seat preview includes the fourth proposal author but refuses a fifth, including pending invitations',async t=>{
 const f=await setup(t),[a,b,c,d]=f.people,w=await f.s.ensureWork(a,{activityId:f.a.id});
 const preview=await f.s.invitePreview(a,{workId:w.id,seats:[2,3,4]});
 assert.deepEqual(preview.students.map(x=>x.studentId),[b,c,d].map(x=>x.studentId));
 await f.s.invite(a,{workId:w.id,seats:[2,3,4],expectedStudentIds:preview.students.map(x=>x.studentId)});
 await assert.rejects(f.s.invitePreview(a,{workId:w.id,seats:[5]}),/最多 4 人（含自己）/);
 await f.s.invitation(d,{activityId:f.a.id,workId:w.id,accept:false});
 assert.equal((await f.s.invitePreview(a,{workId:w.id,seats:[5]})).students.length,1);
});
test('argument posters retain three authors and report their own limit for IDs and seats',async t=>{
 const f=await setup(t),[a,b,c,d]=f.people,w=await f.s.ensureWork(a,{activityId:f.b.id});
 await assert.rejects(f.s.invitePreview(a,{workId:w.id,seats:[2,3,4]}),/最多 3 人（含自己）/);
 await assert.rejects(f.s.invite(a,{workId:w.id,studentIds:[b.studentId,c.studentId,d.studentId]}),/最多 3 人/);
 await f.s.invite(a,{workId:w.id,studentIds:[b.studentId,c.studentId]});
 await assert.rejects(f.s.invite(a,{workId:w.id,studentIds:[d.studentId]}),/最多 3 人/);
});
test('proposal seal defeats prepared stale upload, raw work mutation and late new groups; receipts remain append-only',async t=>{const f=await setup(t),p=f.people[0],w=await f.s.ensureWork(p,{activityId:f.a.id}),v=await submit(f,p,w,'v1');const pending=await f.s.prepare(p,{workId:w.id,requestId:'stale-v2',expectedRevision:1,title:'stale',text:'新版',recipient:'窗口',channel:'其他',files:[]});await control(f,f.a,'proposal');await assert.rejects(f.s.finalize(p,{ticketId:pending.ticketId}),/封存/);await assert.rejects(submit(f,p,w,'v2'),/封存/);await assert.rejects(f.s.ensureWork(f.people[1],{activityId:f.a.id}),/封存/);await receipt(f,p,w);await receipt(f,p,w,'receipt2');const [k]=await f.db.query('select * from rib.late_checkpoints where work_id=$1',[w.id]);assert.equal(k.proposal_version_id,v.versionId);assert.equal((await f.s.lateEvidence(f.teacher,{workId:w.id})).items.length,2);assert.equal((await f.db.query('select count(*)::int n from rib.versions where work_id=$1',[w.id]))[0].n,1);await assert.rejects(control(f,f.a,'proposal'),/已封存/);});
test('private receipts leak into no student/groupmate, poster wall, gallery, W18, or proposal media',async t=>{const f=await setup(t),[a,b,c]=f.people,w=await f.s.ensureWork(a,{activityId:f.a.id});await f.s.invite(a,{workId:w.id,studentIds:[b.studentId]});await f.s.invitation(b,{activityId:f.a.id,workId:w.id,accept:true});const v=await submit(f,a,w,'v1');await receipt(f,a,w);for(const p of [a,b,c])await assert.rejects(f.s.lateEvidence(p,{workId:w.id}),/教師/);for(const p of [a,b]){const responses=[await f.s.board(p,{activityId:f.a.id}),await f.s.media(p,{versionId:v.versionId}),await f.s.selections(p)];const str=JSON.stringify(responses);assert.ok(!str.includes('PRIVATE-CASE')&&!str.includes('PRIVATE-REPLY')&&!str.includes('private-delivery')&&!str.includes('receipt-private'));}await f.db.query("update rib.activities set phase='exhibit' where id=$1",[f.a.id]);await assert.rejects(f.s.media(c,{versionId:v.versionId}),/本組/);await assert.rejects(f.s.classWall(a,{activityId:f.a.id}),/不開放/);assert.equal((await f.s.gallery()).items.length,0);const x=await f.s.lateExport(f.teacher,{activityId:f.a.id,className:'101'});assert.ok(!x.csv.includes('PRIVATE-CASE')&&!x.csv.includes('private-delivery'));});
test('close receipts rechecks in-flight ticket; teacher-only extensions have explicit reason and expiry',async t=>{const f=await setup(t),p=f.people[0],w=await f.s.ensureWork(p,{activityId:f.a.id});await submit(f,p,w,'v1');await control(f,f.a,'proposal');const u=await f.s.lateEvidencePrepare(p,{workId:w.id,requestId:'late-ticket',sent:true,date:'2026-10-02',files:[]});await control(f,f.a,'evidence');await assert.rejects(f.s.lateEvidenceFinalize(p,{ticketId:u.ticketId}),/不能/);await assert.rejects(f.s.lateExtension(p,{workId:w.id,type:'evidence',until:new Date(Date.now()+86400000).toISOString(),reason:'設備問題',expectedRevision:1}),/教師/);const [k]=await f.db.query('select * from rib.late_checkpoints where work_id=$1',[w.id]);await assert.rejects(f.s.lateExtension(f.teacher,{workId:w.id,type:'content',until:new Date(Date.now()+86400000).toISOString(),reason:'設備問題',expectedRevision:k.revision}),/不可換版/);await f.s.lateExtension(f.teacher,{workId:w.id,type:'evidence',until:new Date(Date.now()+86400000).toISOString(),reason:'設備問題',expectedRevision:k.revision});await f.s.lateEvidenceFinalize(p,{ticketId:u.ticketId});await f.db.query("update rib.late_checkpoints set evidence_until=now()-interval '1 minute' where work_id=$1",[w.id]);await assert.rejects(receipt(f,p,w,'expired'),/關閉/);});
test('late empty content can be extended once and auto-seals on submission; sealed ID never changes',async t=>{const f=await setup(t),p=f.people[0],w=await f.s.ensureWork(p,{activityId:f.a.id});await control(f,f.a,'proposal');await f.s.lateExtension(f.teacher,{workId:w.id,type:'content',until:new Date(Date.now()+86400000).toISOString(),reason:'老師確認設備障礙',expectedRevision:0});const v=await submit(f,p,w,'late');assert.equal((await f.db.query('select proposal_version_id from rib.late_checkpoints where work_id=$1',[w.id]))[0].proposal_version_id,v.versionId);await assert.rejects(submit(f,p,w,'late-v2'),/封存/);});
test('poster V1 and final are independent, private before manual class opening, and only sealed versions enter W18',async t=>{const f=await setup(t),[a,b]=f.people,w=await f.s.ensureWork(a,{activityId:f.b.id}),v1=await submit(f,a,w,'v1',true);const [v]=await f.db.query('select media from rib.versions where id=$1',[v1.versionId]);const meta=await sharp(f.store.objects.get(v.media[0].fullKey)).metadata();assert.equal(meta.height,5000);assert.equal((await f.s.gallery()).items.length,0);await f.db.query("update rib.activities set phase='exhibit' where id=$1",[f.b.id]);await assert.rejects(f.s.media(b,{versionId:v1.versionId}),/尚未/);await assert.rejects(f.s.classWall(b,{activityId:f.b.id}),/尚未/);await control(f,f.b,'v1');const v2=await submit(f,a,w,'v2',true);await control(f,f.b,'classroom',{open:true});assert.equal((await f.s.classWall(b,{activityId:f.b.id})).items[0].versions.length,1);await f.s.media(b,{versionId:v1.versionId});await assert.rejects(f.s.media(b,{versionId:v2.versionId}),/封存/);assert.deepEqual((await f.s.selections(a)).candidates.map(x=>x.id),[v1.versionId]);await control(f,f.b,'final');const [k]=await f.db.query('select * from rib.late_checkpoints where work_id=$1',[w.id]);assert.equal(k.v1_version_id,v1.versionId);assert.equal(k.final_version_id,v2.versionId);await assert.rejects(submit(f,a,w,'v3',true),/封存/);assert.equal((await f.s.selections(a)).candidates.length,2);});
test('teacher class scopes and optimistic revisions enforced; score data remains untouched',async t=>{const f=await setup(t),w=await f.s.ensureWork(f.people[0],{activityId:f.a.id});await submit(f,f.people[0],w,'v1');await receipt(f,f.people[0],w);const other={role:'teacher',email:'other@example.invalid',teacher:{scopes:[{term:'11501',className:'102'}]}};await assert.rejects(f.s.lateEvidence(other,{workId:w.id}),/權限/);await assert.rejects(f.s.lateExport(other,{activityId:f.a.id,className:'101'}),/權限/);await assert.rejects(f.s.lateControl(other,{activityId:f.a.id,className:'101',operation:'proposal',confirm:true,expectedRevision:0}),/權限/);const [k]=await f.db.query('select * from rib.late_checkpoints where work_id=$1',[w.id]);await assert.rejects(f.s.lateStatus(f.teacher,{workId:w.id,status:'completed',verified:false,expectedRevision:k.revision}),/核對/);await f.s.lateStatus(f.teacher,{workId:w.id,status:'completed',verified:true,reason:'教師核對收件通知',expectedRevision:k.revision});await assert.rejects(f.s.lateStatus(f.teacher,{workId:w.id,status:'pending',verified:false,expectedRevision:k.revision}),/更新/);assert.equal((await f.db.query('select count(*)::int n from rib.assessments'))[0].n,0);});
test('private checkpoint backups retain seals, evidence history and authors on empty restore',async t=>{const f=await setup(t),p=f.people[0],w=await f.s.ensureWork(p,{activityId:f.a.id});await submit(f,p,w,'v1');await receipt(f,p,w);await control(f,f.a,'proposal');const backup=await snapshot(f.db);assert.equal(backup.format,'rib-backup-v7');const pg=new PGlite();t.after(()=>pg.close());await pg.exec(await readFile(new URL('../schema.sql',import.meta.url),'utf8'));const wrap=c=>({query:async(q,p=[])=> (await c.query(q,p)).rows,transaction:fn=>c.transaction(x=>fn(wrap(x)))}),db=wrap(pg);const counts=await restoreEmpty(db,backup);assert.equal(counts.late_deliveries,1);assert.deepEqual(await db.query('select * from rib.late_checkpoints'),await f.db.query('select * from rib.late_checkpoints'));assert.deepEqual(await db.query('select * from rib.late_deliveries'),await f.db.query('select * from rib.late_deliveries'));});
test('poster class sharing never exposes another class, even after global exhibit toggle',async t=>{const f=await setup(t),[a,b,c]=f.people;await f.db.query("update rib.students set class_name='102' where student_id=$1",[c.studentId]);c.student.class_name='102';const w1=await f.s.ensureWork(a,{activityId:f.b.id}),w2=await f.s.ensureWork(c,{activityId:f.b.id}),v1=await submit(f,a,w1,'class101',true),v2=await submit(f,c,w2,'class102',true);await control(f,f.b,'v1');await control(f,f.b,'classroom',{open:true});await f.db.query("update rib.activities set phase='exhibit' where id=$1",[f.b.id]);const wall=await f.s.classWall(b,{activityId:f.b.id});assert.equal(wall.items.length,1);assert.equal(wall.items[0].id,w1.id);await assert.rejects(f.s.media(b,{versionId:v2.versionId}),/本班/);await f.s.media(b,{versionId:v1.versionId});await assert.rejects(f.s.classWall(c,{activityId:f.b.id}),/尚未/);});
test('poster public gallery requires BOTH an immutable seal and manual teacher review, respects author opt-out',async t=>{const f=await setup(t),p=f.people[0],w=await f.s.ensureWork(p,{activityId:f.b.id}),v=await submit(f,p,w,'poster',true);const [pub]=await f.db.query('select * from rib.publications where version_id=$1',[v.versionId]);assert.equal((await f.s.gallery()).items.length,0);await assert.rejects(f.s.publish(f.teacher,{publicationId:pub.id,publish:true,reviewed:true}),/第三輪|封存/);await control(f,f.b,'v1');await assert.rejects(f.s.publish(f.teacher,{publicationId:pub.id,publish:true,reviewed:true}),/第三輪/);await control(f,f.b,'classroom',{open:true});await assert.rejects(f.s.publish(f.teacher,{publicationId:pub.id,publish:true}),/逐張/);await f.s.publish(f.teacher,{publicationId:pub.id,publish:true,reviewed:true,title:'虛構匿名海報'});assert.equal((await f.s.gallery()).items.length,1);await f.s.consent(p,{workId:w.id,consent:false});assert.equal((await f.s.gallery()).items.length,0);});
test('regrouping in poster activity does not remove original proposal members or their supplement responsibility',async t=>{const f=await setup(t),[a,b,c]=f.people,original=await f.s.ensureWork(a,{activityId:f.a.id});await f.s.invite(a,{workId:original.id,studentIds:[b.studentId]});await f.s.invitation(b,{activityId:f.a.id,workId:original.id,accept:true});await submit(f,a,original,'proposal');await control(f,f.a,'proposal');const poster=await f.s.ensureWork(c,{activityId:f.b.id});await f.s.invite(c,{workId:poster.id,studentIds:[b.studentId]});await f.s.invitation(b,{activityId:f.b.id,workId:poster.id,accept:true});await receipt(f,b,original,'original-author-evidence');assert.equal((await f.s.board(b,{activityId:f.a.id})).works[0].id,original.id);assert.equal((await f.s.board(b,{activityId:f.b.id})).works[0].id,poster.id);assert.equal((await f.s.lateEvidence(f.teacher,{workId:original.id})).items.length,1);});
test('new HTTP routes enforce origin, method, role, teacher preview and archived-semester guards',async t=>{
 const f=await setup(t),p=f.people[0],w=await f.s.ensureWork(p,{activityId:f.a.id});await submit(f,p,w,'v1');await receipt(f,p,w);
 const {handler}=await import('../http.mjs'),{createSession}=await import('../security.mjs');const run=handler({db:f.db,store:f.store,origin:'https://class.invalid',rateSecret:'test',secure:true}),student=(await createSession(f.db,{role:'student',term:p.term,studentId:p.studentId,revision:1})).token,teacher=(await createSession(f.db,{role:'admin',email:f.teacher.email})).token;
 async function request(action,{token=student,method='GET',body={},origin='https://class.invalid',query={}}={}){const req={url:'/api/workspace?'+new URLSearchParams({action,...query}),method,body,headers:{origin,cookie:'rib_session='+token,'content-type':'application/json'},socket:{remoteAddress:'127.0.0.1'}};let result={};const res={setHeader(){},end(data){result={status:this.statusCode,data:JSON.parse(data)};}};await run(req,res);return result;}
 assert.equal((await request('lateEvidence',{query:{workId:w.id}})).status,403);assert.equal((await request('lateEvidence',{token:teacher,query:{workId:w.id}})).status,200);
 assert.equal((await request('lateEvidence',{token:teacher,query:{workId:w.id,previewStudent:p.studentId,previewActivity:f.a.id}})).status,403);
 assert.equal((await request('lateControl',{token:teacher,query:{activityId:f.a.id}})).status,405);
 assert.equal((await request('lateControl',{token:teacher,method:'POST',origin:'https://evil.invalid',body:{activityId:f.a.id}})).status,403);
 await f.db.query('update rib.activities set archived=true where id=$1',[f.a.id]);assert.equal((await request('lateStatus',{token:teacher,method:'POST',body:{workId:w.id,status:'pending',verified:false,expectedRevision:0}})).status,403);
});
test('semester activation retains checkpoint data in the ACTUAL pre-switch archive, clones no old seals',async t=>{
 const f=await setup(t),p=f.people[0],w=await f.s.ensureWork(p,{activityId:f.a.id});await submit(f,p,w,'v1');await receipt(f,p,w);await control(f,f.a,'proposal');
 const draft=await f.s.termSave(f.teacher,{term:'11502',sourceTerm:'11501',expectedRevision:0,teachers:[f.teacher.email],rosterText:f.people.map(p=>`${p.studentId}\t${p.student.name}\t101\t${p.student.seat}`).join('\n')});
 const result=await f.s.termActivate(f.teacher,{term:'11502',expectedRevision:draft.draft.revision,confirmTerm:'11502',confirm:true});const [job]=await f.db.query('select * from rib.term_changes where id=$1',[result.jobId]),{gunzipSync}=await import('node:zlib');const backup=JSON.parse(gunzipSync(await f.store.get(job.summary.backupKey)));
 assert.equal(backup.format,'rib-backup-v7');assert.equal(backup.tables.late_deliveries.length,1);assert.equal(backup.tables.late_checkpoints.length,1);assert.equal(backup.tables.late_checkpoints[0].proposal_version_id,(await f.db.query('select proposal_version_id from rib.late_checkpoints where work_id=$1',[w.id]))[0].proposal_version_id);
 const [count]=await f.db.query("select count(*)::int n from rib.late_controls c join rib.activities a on a.id=c.activity_id where a.term='11502'");assert.equal(count.n,0);assert.ok((await f.db.query("select accepting from rib.activities where term='11502'")).every(a=>!a.accepting));
});
test('acknowledgement retries after a seal or evidence closure return the SAME immutable saved record',async t=>{const f=await setup(t),p=f.people[0],w=await f.s.ensureWork(p,{activityId:f.a.id}),v=await submit(f,p,w,'v1'),u=await receipt(f,p,w);const [ticket]=await f.db.query('select id from rib.uploads where work_id=$1',[w.id]);await control(f,f.a,'proposal');await control(f,f.a,'evidence');assert.equal((await f.s.finalize(p,{ticketId:ticket.id})).versionId,v.versionId);assert.equal((await f.s.lateEvidenceFinalize(p,{ticketId:u.ticketId})).saved,true);assert.equal((await f.db.query('select count(*)::int n from rib.late_deliveries where work_id=$1 and completed',[w.id]))[0].n,1);});
