import test from 'node:test';import assert from 'node:assert/strict';import sharp from 'sharp';
import {fixture} from './support.mjs';import {Workspace} from '../service.mjs';import {sha} from '../security.mjs';import {autoPublish} from '../publication.mjs';import {snapshot,restoreEmpty} from '../backup.mjs';import {PGlite} from '@electric-sql/pglite';import {readFile} from 'node:fs/promises';
async function setup(t){const f=await fixture(3);t.after(f.close);const old=process.env.RIB_ACCEPTANCE_ONLY;process.env.RIB_ACCEPTANCE_ONLY='false';t.after(()=>old===undefined?delete process.env.RIB_ACCEPTANCE_ONLY:process.env.RIB_ACCEPTANCE_ONLY=old);return {...f,s:new Workspace(f.db,f.store)};}
async function upload(f,p,w,input={}){const row=(await f.db.query('select revision from rib.works where id=$1',[w.id]))[0],bytes=await sharp({create:{width:30,height:30,channels:3,background:'#123456'}}).png().toBuffer(),file={bytes:bytes.length,mime:'image/png',sha256:sha(bytes)};const args={workId:w.id,requestId:crypto.randomUUID(),expectedRevision:row.revision,files:input.group?[file,file]:[file],topics:['A02','B02'],publicDisplay:true,privacyChecked:true,...input};const prepared=await f.s.prepare(p,args);assert.equal((await f.s.prepare(p,args)).ticketId,prepared.ticketId,'retries compare JSONB metadata independent of key order');const [ticket]=await f.db.query('select files from rib.uploads where id=$1',[prepared.ticketId]);for(const item of ticket.files)f.store.objects.set(item.key,bytes);return f.s.finalize(p,{ticketId:prepared.ticketId});}
test('login agreement makes new submissions public by default; public list uses thumbnails and no private fields',async t=>{
 const f=await setup(t),p=f.people[0],w=await f.s.ensureWork(p,{activityId:'w4-demo'});
 await f.db.query('update rib.students set sharing_agreement=null where student_id=$1',[p.studentId]);await assert.rejects(upload(f,p,w),/登入後/);await f.db.query('update rib.students set sharing_agreement=$1 where student_id=$2',[JSON.stringify(p.student.sharing_agreement),p.studentId]);
 const v=await upload(f,p,w),gallery=await f.s.gallery();assert.equal(gallery.items.length,1);const item=gallery.items[0];assert.deepEqual(Object.keys(item).sort(),['id','thumbnails','title','week']);assert.equal(item.title,'匿名作品');assert.match(item.thumbnails[0],/thumb/);
 assert.ok(!JSON.stringify(gallery).includes(p.studentId));assert.ok(!JSON.stringify(gallery).includes(p.student.name));const detail=await f.s.galleryItem({publicationId:item.id});assert.equal(detail.images.length,1);assert.ok(!Object.keys(detail).includes('metadata'));assert.equal((await f.db.query('select reviewed_by from rib.publications where version_id=$1',[v.versionId]))[0].reviewed_by,null);
 const other=f.people[1],privateWork=await f.s.ensureWork(other,{activityId:'w4-demo'});await f.s.consent(other,{workId:privateWork.id,consent:false});await upload(f,other,privateWork);await f.s.consent(p,{workId:w.id,consent:true});assert.equal((await f.s.gallery()).items.length,1,'old or private versions never auto-publish through consent alone');
});
test('groups need no per-work opt-in, any member can opt out, and teacher holds persist',async t=>{
 const f=await setup(t),[a,b]=f.people,w=await f.s.ensureWork(a,{activityId:'w5-demo'});await f.s.invite(a,{workId:w.id,studentIds:[b.studentId]});await f.s.invitation(b,{activityId:'w5-demo',workId:w.id,accept:true});await upload(f,a,w,{group:true});assert.equal((await f.s.gallery()).items.length,1);
 let [item]=(await f.s.gallery()).items;assert.ok(item);await f.s.consent(b,{workId:w.id,consent:false});await assert.rejects(f.s.galleryItem({publicationId:item.id}),/沒有公開/);await f.s.consent(a,{workId:w.id,consent:true});await upload(f,a,w,{group:true});assert.equal((await f.s.gallery()).items.length,0,'another author or new version cannot override the opt-out');await assert.rejects(f.s.publish(f.teacher,{publicationId:item.id,publish:true,reviewed:true}),/不公開/);await f.s.consent(b,{workId:w.id,consent:true});assert.equal((await f.s.gallery()).items.length,1);
 await f.s.publish(f.teacher,{publicationId:item.id,publish:false});assert.equal((await f.s.gallery()).items.length,0);await f.s.consent(b,{workId:w.id,consent:true});await upload(f,a,w,{group:true});assert.equal((await f.s.gallery()).items.length,0,'resubmission cannot evade teacher hold');
 const [latest]=await f.db.query('select p.id from rib.publications p join rib.versions v on v.id=p.version_id where v.work_id=$1 order by v.ordinal desc',[w.id]);await f.s.publish(f.teacher,{publicationId:latest.id,publish:true,reviewed:true});assert.equal((await f.s.gallery()).items.length,1);await assert.rejects(f.s.galleryItem({publicationId:item.id}),/沒有公開/);
 await f.s.publish(f.teacher,{publicationId:latest.id,publish:false});const backup=await snapshot(f.db),pg=new PGlite();t.after(()=>pg.close());await pg.exec(await readFile(new URL('../schema.sql',import.meta.url),'utf8'));const wrap=c=>({query:async(q,p=[])=> (await c.query(q,p)).rows,transaction:fn=>c.transaction(tx=>fn(wrap(tx)))});await restoreEmpty(wrap(pg),backup);assert.equal((await pg.query('select publication_hold from rib.works')).rows[0].publication_hold,true);
});
test('test accounts, test activities, hidden works and acceptance deployment cannot leak through list or detail',async t=>{
 const f=await setup(t),p=f.people[0],w=await f.s.ensureWork(p,{activityId:'w4-demo'});await upload(f,p,w);const [item]=(await f.s.gallery()).items;
 await f.db.query('update rib.works set hidden=true where id=$1',[w.id]);assert.equal((await f.s.gallery()).items.length,0);await assert.rejects(f.s.galleryItem({publicationId:item.id}),/沒有公開/);await f.db.query('update rib.works set hidden=false where id=$1',[w.id]);
 await f.db.query('update rib.students set is_test=true where student_id=$1',[p.studentId]);assert.equal(await autoPublish(f.db,w.id),false);assert.equal((await f.s.gallery()).items.length,0);await assert.rejects(f.s.galleryItem({publicationId:item.id}),/沒有公開/);await f.db.query('update rib.students set is_test=false');
 await f.db.query(`update rib.activities set legacy='{"testOnly":true}' where id='w4-demo'`);assert.equal(await autoPublish(f.db,w.id),false);assert.equal((await f.s.gallery()).items.length,0);await f.db.query('update rib.activities set legacy=null');
 process.env.RIB_ACCEPTANCE_ONLY='true';assert.equal((await f.s.gallery()).items.length,0);await assert.rejects(f.s.galleryItem({publicationId:item.id}),/沒有公開/);await assert.rejects(f.s.publish(f.teacher,{publicationId:item.id,publish:true,reviewed:true}),/驗收站/);
});
test('public pagination is bounded and old backups without publication_hold still restore',async t=>{
 const f=await setup(t),p=f.people[0],w=await f.s.ensureWork(p,{activityId:'w5-demo'});await upload(f,p,w,{group:true});const [version]=await f.db.query('select * from rib.versions');for(let i=2;i<=26;i++){await f.db.query('insert into rib.versions(id,work_id,ordinal,media,request_id) values($1,$2,$3,$4,$1)',['gallery-'+i,w.id,i,JSON.stringify(version.media)]);await f.db.query("insert into rib.publications(id,version_id,status) values($1,$1,'published')",['gallery-'+i]);}
 const one=await f.s.gallery({page:0}),two=await f.s.gallery({page:1});assert.equal(one.items.length,24);assert.equal(one.hasMore,true);assert.equal(two.items.length,2);assert.equal(two.hasMore,false);assert.equal(new Set([...one.items,...two.items].map(i=>i.id)).size,26);await assert.rejects(f.s.gallery({page:-1}),/頁碼/);
 const backup=await snapshot(f.db);for(const row of backup.tables.works)delete row.publication_hold;for(const row of backup.tables.members)delete row.sharing_opt_out;for(const row of backup.tables.students)delete row.sharing_agreement;const {sha256,...payload}=backup;backup.sha256=sha(JSON.stringify(payload));const pg=new PGlite();t.after(()=>pg.close());await pg.exec(await readFile(new URL('../schema.sql',import.meta.url),'utf8'));const wrap=c=>({query:async(q,p=[])=> (await c.query(q,p)).rows,transaction:fn=>c.transaction(tx=>fn(wrap(tx)))});await restoreEmpty(wrap(pg),backup);assert.equal((await pg.query('select publication_hold from rib.works')).rows[0].publication_hold,false);
});
