import {test} from 'node:test';import assert from 'node:assert/strict';
import {fixture} from './support.mjs';import {Workspace} from '../service.mjs';import {snapshot,restoreEmpty} from '../backup.mjs';
import {studentNext} from '../../workspace/ui-model.js';

test('new drawings preserve the original ORID version and prompt a check before reuse',async t=>{
 const f=await setup(t),p=f.people[0],input=payload(f);await f.s.saveReflection(p,input);
 await f.db.query("insert into rib.versions(id,work_id,ordinal,metadata,media,request_id) values('v0-new',$1,2,'{}','[]','new-drawing')",[input.workId]);
 await f.db.query("update rib.works set current_version_id='v0-new' where id=$1",[input.workId]);
 let board=await f.s.board(p,{activityId:'w5-demo'});assert.match(studentNext(board,{})[0],/回看原 ORID/);
 let item=(await f.s.classWall(f.people[1],{activityId:'w5-demo'})).items.find(x=>x.id===input.workId);
 assert.equal(item.reflection.versionId,'v0');assert.equal(item.reflection.ordinal,1);assert.notEqual(item.reflection.versionId,item.currentVersionId);
 assert.deepEqual((await f.s.reflection(p,{workId:input.workId})).reflection.answers,input.answers);
 await assert.rejects(f.s.reviewReflection(f.teacher,{workId:input.workId,expectedRevision:1,reviewed:true,answers:input.answers}),/目前作品版本/);
 await f.s.saveReflection(p,{...input,versionId:'v0-new',expectedRevision:1,requestId:'reuse-after-check'});
 board=await f.s.board(p,{activityId:'w5-demo'});assert.match(studentNext(board,{})[0],/作品與 ORID 已保存/);
 item=(await f.s.classWall(f.people[1],{activityId:'w5-demo'})).items.find(x=>x.id===input.workId);assert.equal(item.reflection.versionId,item.currentVersionId);assert.equal(item.reflection.ordinal,2);
});
async function setup(t){const f=await fixture(6);t.after(f.close);await f.db.query("update rib.workspace_state set current_term='11501'");await f.db.query("update rib.activities set kind='w5-personal',phase='exhibit' where id='w5-demo'");
 const s=new Workspace(f.db,f.store),works=[];
 for(const [i,p]of f.people.entries()){p.student.class_name=['108','109','110','108','108','108'][i];p.student.is_test=i===4;await f.db.query('update rib.students set class_name=$1,is_test=$2 where student_id=$3',[p.student.class_name,p.student.is_test,p.studentId]);if(i===4)continue;
  await s.chooseTopic(p,{activityId:'w5-demo',topic:i===3?'B06':'A06',expectedRevision:0});const w=(await s.board(p,{activityId:'w5-demo'})).works[0],v='v'+i;
  await f.db.query('insert into rib.versions(id,work_id,ordinal,metadata,media,request_id) values($1,$2,1,$3,$4,$1)',[v,w.id,JSON.stringify({topic:w.topic}),JSON.stringify([{fullKey:'x',thumbKey:'t',displayHash:'h'}])]);await f.db.query('update rib.works set current_version_id=$2 where id=$1',[w.id,v]);await f.db.query("insert into rib.publications(id,version_id,status) values($1,$2,'published')",['pub'+i,v]);works[i]={...w,current_version_id:v};
 }return {...f,s,works};}
function payload(f,extra={}){return {workId:f.works[0].id,versionId:'v0',referenceVersionId:'v1',expectedRevision:0,requestId:'first',status:'submitted',allowPublic:true,answers:{o:'用兩條線區分兩個條件。',r:'覺得清楚。',id:'自己的圖保留分支，補上條件。'},...extra};}
test('named course wall spans only the configured joint classes; direct media and references obey the same boundary',async t=>{const f=await setup(t),[p,q,out]=f.people;const wall=await f.s.classWall(p,{activityId:'w5-demo',className:'110'});assert.equal(wall.items.length,4);assert.ok(wall.items.some(w=>w.label.includes(q.student.name)));assert.ok(!JSON.stringify(wall).includes(out.student.name));assert.ok(!JSON.stringify(wall).includes(p.studentId));
 assert.equal((await f.s.media(p,{versionId:'v1'})).images.length,1);await assert.rejects(f.s.media(p,{versionId:'v2'}),/共同上課/);await assert.rejects(f.s.media(out,{versionId:'v0'}),/共同上課/);assert.equal((await f.s.classWall(out,{activityId:'w5-demo'})).items.length,1);
 await assert.rejects(f.s.classWall(f.people[4],{activityId:'w5-demo'}),/自己的課堂/);const teacher={role:'teacher',email:'limited',teacher:{scopes:[{term:'11501',className:'108'}]}};assert.equal((await f.s.classWall(teacher,{activityId:'w5-demo'})).items.length,3);await assert.rejects(f.s.reflection(teacher,{workId:f.works[1].id}),/權限/);
});
test('W3 and W4 display confirmed author names to joint classmates only',async t=>{const f=await fixture(2);t.after(f.close);const s=new Workspace(f.db,f.store);for(const [i,p]of f.people.entries()){p.student.class_name=i?'109':'108';await f.db.query('update rib.students set class_name=$1 where student_id=$2',[p.student.class_name,p.studentId]);}for(const [kind,week]of [['w3-personal',3],['w4',4]]){await f.db.query("insert into rib.activities(id,term,week,title,kind,phase,accepting) values($1,'11501',$2,$1,$1,'exhibit',true)",[kind,week]);const w=await s.ensureWork(f.people[0],{activityId:kind});await f.db.query('insert into rib.versions(id,work_id,ordinal,metadata,media,request_id) values($1,$2,1,$3,$4,$1)',[kind+'v',w.id,'{}','[]']);assert.match((await s.classWall(f.people[1],{activityId:kind})).items[0].label,/示範同學1/);}});
test('ORID preserves drafts, version reference, revisions and idempotency, rejects foreign/own/different-topic references',async t=>{const f=await setup(t),p=f.people[0],input=payload(f,{status:'draft'});await f.s.saveReflection(p,input);assert.equal((await f.s.saveReflection(p,input)).revision,1);assert.equal((await f.s.reflection(p,{workId:input.workId})).reference.label,'109 班 示範同學2');assert.equal((await f.s.classWall(f.people[1],{activityId:'w5-demo'})).items.find(w=>w.id===input.workId).reflection,null);
 await assert.rejects(f.s.reflection(f.people[1],{workId:input.workId}),/自己的/);await assert.rejects(f.s.saveReflection(p,{...input,requestId:'new'}),/另一個視窗/);
 for(const [referenceVersionId,pattern]of [['v0',/引用一件/],['v2',/共同上課/],['v3',/同一題/]])await assert.rejects(f.s.saveReflection(p,payload(f,{expectedRevision:1,requestId:referenceVersionId,referenceVersionId})),pattern);
 await assert.rejects(f.s.saveReflection(f.people[1],payload(f)),/保存/);await assert.rejects(f.s.saveReflection(p,payload(f,{expectedRevision:1,requestId:'empty',answers:{o:'',r:'',id:''}})),/三問/);
 await f.s.saveReflection(p,payload(f,{expectedRevision:1,requestId:'submit'}));assert.ok((await f.s.classWall(f.people[1],{activityId:'w5-demo'})).items.find(w=>w.id===input.workId).reflection.answers.o);
 await f.db.query('update rib.works set hidden=true where id=$1',[f.works[1].id]);assert.equal((await f.s.reflection(p,{workId:input.workId})).reference.unavailable,true);assert.match((await f.s.classWall(p,{activityId:'w5-demo'})).items.find(w=>w.own).reflection.referenceLabel,/不開放/);
});
test('public ORID is a teacher-reviewed anonymous copy; author edits and opt-out withdraw it; original images and prose survive',async t=>{const f=await setup(t),p=f.people[0],input=payload(f,{answers:{o:'示範同學2 用兩條線。',r:'清楚。',id:'補上條件。'}});await f.s.saveReflection(p,input);assert.equal((await f.s.galleryItem({publicationId:'pub0'})).reflection,null);
 const clean={o:'參考作品 A 用兩條線。',r:'清楚。',id:'補上條件。'},review={workId:input.workId,expectedRevision:1,reviewed:true,answers:clean};await assert.rejects(f.s.reviewReflection(p,review),/教師/);await assert.rejects(f.s.reviewReflection(f.teacher,{...review,reviewed:false}),/檢查/);await f.s.reviewReflection(f.teacher,review);
 const detail=await f.s.galleryItem({publicationId:'pub0'});assert.equal(detail.reflection.answers.o,clean.o);assert.ok(!JSON.stringify(detail).includes('示範同學'));assert.ok(!JSON.stringify(detail).includes('referenceVersionId'));assert.equal((await f.s.reflection(p,{workId:input.workId})).reflection.answers.o,input.answers.o);
 await f.s.saveReflection(p,{...input,expectedRevision:1,requestId:'edit'});assert.equal((await f.s.galleryItem({publicationId:'pub0'})).reflection,null);await assert.rejects(f.s.reviewReflection(f.teacher,review),/更新/);
 await f.s.reviewReflection(f.teacher,{...review,expectedRevision:2});await f.s.consent(p,{workId:input.workId,consent:false});await assert.rejects(f.s.galleryItem({publicationId:'pub0'}),/沒有公開/);assert.equal((await f.s.board(p,{activityId:'w5-demo'})).works[0].versions.length,1);
 const backup=await snapshot(f.db),empty=await fixture(0);t.after(empty.close);await empty.db.query('delete from rib.activities');await empty.db.query('delete from rib.teachers');await restoreEmpty(empty.db,backup);assert.equal((await empty.db.query('select reflection from rib.works where id=$1',[input.workId]))[0].reflection.answers.o,input.answers.o);
});
test('closed and archived activity blocks saves, and unpublished/changed versions cannot be cited or reviewed',async t=>{const f=await setup(t),p=f.people[0];await f.s.saveReflection(p,payload(f));await f.db.query("update rib.activities set phase='production' where id='w5-demo'");await assert.rejects(f.s.saveReflection(p,payload(f,{expectedRevision:1,requestId:'blocked'})),/展廳/);await f.db.query("update rib.activities set phase='exhibit',archived=true where id='w5-demo'");await assert.rejects(f.s.saveReflection(p,payload(f,{expectedRevision:1,requestId:'archived'})),/封存|無法查看/);});
test('archived activities reject reflection review even with a forged activity ID',async t=>{const f=await setup(t);await f.s.saveReflection(f.people[0],payload(f));await f.db.query("update rib.activities set archived=true where id='w5-demo'");await assert.rejects(f.s.reviewReflection(f.teacher,{workId:f.works[0].id,activityId:'w4-demo',expectedRevision:1,reviewed:true,answers:{o:'觀察',r:'感受',id:'運用'}}),/已封存/);});
