import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './support.mjs';
import {Workspace} from '../service.mjs';
import {w4Progress} from '../../workspace/w4-progress.js';
import {activityFlow} from '../../workspace/activity-flow.js';
import {studentNext} from '../../workspace/ui-model.js';
const answers={sourceReference:'W4 V1',comment:'甲',quote:'正在等人',color:'yellow',evidence:'只有站在門口，不能確定目的',rewritten:'他站在門口。'};
const work=()=>({versions:[{id:'v1'}],feedback:[],teacherReadings:[],decisions:[],grades:[],hasHumanFeedback:false});
test('W4 progress separates received feedback, own reader tasks, W5 drafts and formal assessment',()=>{
 const w=work(),b={activity:{kind:'w4',phase:'review',accepting:true},works:[w],reviews:[{status:'assigned'}],invitations:[]};
 assert.equal(w4Progress(w).step,1);
 w.teacherReadings=[{mode:'ai-simulation'}];assert.equal(w4Progress(w).step,1);
 w.teacherReadings=[{mode:'human'}];w.hasHumanFeedback=true;
 assert.equal(w4Progress(w).step,2);assert.match(activityFlow(b),/aria-current="step"><span>3<\/span>/);
 assert.match(studentNext(b)[0],/收到真人回饋/);assert.match(studentNext(b)[1],/我的初讀任務/);
 w.decisions=[{choice:'keep'}];assert.equal(w4Progress(w).step,3);assert.match(w4Progress(w).status,/待 W5 判讀/);
 assert.doesNotMatch(activityFlow(b),/aria-current/);assert.match(activityFlow(b),/取得真人初讀回饋/);
 w.w5JudgmentStatus='draft';assert.match(w4Progress(w).status,/待送出/);
 w.w5JudgmentStatus='submitted';assert.match(w4Progress(w).status,/待教師評閱/);
 w.grades=[{status:'graded'}];assert.equal(w4Progress(w).status,'已評閱');
});
test('teacher draft and AI simulation leave progress unchanged; published human reading and student decision advance it',async t=>{
 const f=await fixture();t.after(f.close);const s=new Workspace(f.db,f.store),p=f.people[0],w=await s.ensureWork(p,{activityId:'w4-demo'});
 await f.db.query("insert into rib.versions(id,work_id,ordinal,media,metadata,request_id) values('v1',$1,1,'[]','{}','v1')",[w.id]);
 const input={workId:w.id,versionId:'v1',mode:'human',situation:'有人站在門口',meaning:'看不出是否在等人',expectedRevision:0,status:'draft'};
 const current=async()=>w4Progress((await s.board(p,{activityId:'w4-demo'})).works[0]);
 await s.saveTeacherReading(f.teacher,input);assert.equal((await current()).step,1);
 await s.saveTeacherReading(f.teacher,{...input,status:'published',expectedRevision:1,mode:'ai-simulation',reviewed:true});assert.equal((await current()).step,1);
 await s.saveTeacherReading(f.teacher,{...input,status:'published',expectedRevision:2,personallyRead:true});assert.equal((await current()).step,2);
 await s.decision(p,{workId:w.id,versionId:'v1',reason:'保留站在門口的畫面，不強稱他在等人。'});assert.equal((await current()).step,3);assert.match((await current()).status,/待 W5 判讀/);
 await f.db.query("update rib.activities set kind='w5-personal' where id='w5-demo'");
 await s.saveAiJudgment(p,{activityId:'w5-demo',answers,status:'draft',expectedRevision:0});assert.match((await current()).status,/待送出/);
 await s.saveAiJudgment(p,{activityId:'w5-demo',answers,status:'submitted',expectedRevision:1});assert.match((await current()).status,/待教師評閱/);
 assert.equal((await s.board(f.people[1],{activityId:'w4-demo'})).works.length,0);
 const teacherWork=(await s.board(f.teacher,{activityId:'w4-demo',className:'101'})).works[0];assert.equal(teacherWork.w5JudgmentStatus,'submitted');assert.ok(!JSON.stringify(teacherWork).includes(answers.evidence));
 await s.saveAiJudgment(p,{activityId:'w5-demo',answers,status:'draft',expectedRevision:2});assert.match((await current()).status,/待送出/);
 await f.db.query("update rib.activities set archived=true where id='w5-demo'");assert.match((await current()).status,/待 W5 判讀/);
 await f.db.query("update rib.activities set archived=false,legacy='{\"testOnly\":true}' where id='w5-demo'");assert.match((await current()).status,/待 W5 判讀/);
 await f.db.query("update rib.activities set legacy='{}',term='11502' where id='w5-demo'");assert.match((await current()).status,/待 W5 判讀/);
});
