import test from 'node:test';import assert from 'node:assert/strict';import sharp from 'sharp';
import {fixture} from './support.mjs';import {Workspace} from '../service.mjs';import {sha} from '../security.mjs';import {upgradeW5Personal} from '../w5-personal-upgrade.mjs';import {W5_TOPICS} from '../../workspace/w5-topics.js';import {activityFlow} from '../../workspace/activity-flow.js';import {studentNext} from '../../workspace/ui-model.js';
async function setup(t){const f=await fixture();t.after(f.close);await upgradeW5Personal(f.db,{apply:true});return {...f,s:new Workspace(f.db,f.store)};}
async function upload(f,p,w,topic,requestId=crypto.randomUUID()){const bytes=await sharp({create:{width:40,height:40,channels:3,background:'#9baf98'}}).png().toBuffer(),file={bytes:bytes.length,mime:'image/png',sha256:sha(bytes)},input={workId:w.id,expectedRevision:w.revision,requestId,topic,files:[file]};const u=await f.s.prepare(p,input);for(const item of (await f.db.query('select files from rib.uploads where id=$1',[u.ticketId]))[0].files)f.store.objects.set(item.key,bytes);return {u,input,save:()=>f.s.finalize(p,{ticketId:u.ticketId})};}
test('W5 uses student topics aligned with current teaching with no teacher answers and requires saved choice before a single image',async t=>{const f=await setup(t),p=f.people[0],w=await f.s.ensureWork(p,{activityId:'w5-demo'});assert.equal(W5_TOPICS.length,16);assert.ok(W5_TOPICS.every(t=>!('check'in t)));assert.ok(!W5_TOPICS.some(t=>['A01','B01','B03','B04'].includes(t.id)));await assert.rejects(upload(f,p,w,'A02'),/先選定/);await assert.rejects(f.s.chooseTopic(p,{activityId:'w5-demo',topic:'A01',expectedRevision:0}),/自選題/);
 await f.s.chooseTopic(p,{activityId:'w5-demo',topic:'B06',expectedRevision:0});const current=await f.s.work(p,w.id);assert.equal(current.topic,'B06');assert.equal(current.revision,1);await assert.rejects(f.s.invite(p,{workId:w.id,studentIds:[f.people[1].studentId]}),/不使用小組/);const u=await upload(f,p,current,'B06');await assert.rejects(f.s.prepare(p,{...u.input,requestId:'two',files:[...u.input.files,...u.input.files]}),/1 張/);const saved=await u.save();assert.equal((await f.db.query('select metadata from rib.versions where id=$1',[saved.versionId]))[0].metadata.topic,'B06');await assert.rejects(f.s.chooseTopic(p,{activityId:'w5-demo',topic:'A02',expectedRevision:2}),/已交件/);
});
test('changing topic invalidates pending upload; saved topics persist, and another student cannot edit or claim the work',async t=>{const f=await setup(t),[p,q]=f.people;await f.s.chooseTopic(p,{activityId:'w5-demo',topic:'A02',expectedRevision:0});const w=(await f.s.board(p,{activityId:'w5-demo'})).works[0],pending=await upload(f,p,w,'A02');await f.s.chooseTopic(p,{activityId:'w5-demo',topic:'B10',expectedRevision:1});await assert.rejects(pending.save(),/新版本/);await assert.rejects(f.s.chooseTopic(p,{activityId:'w5-demo',topic:'A03',expectedRevision:1}),/更新/);await assert.rejects(f.s.work(q,w.id,{write:true}));await f.s.chooseTopic(q,{activityId:'w5-demo',topic:'A04',expectedRevision:0,workId:w.id});assert.equal((await f.s.board(p,{activityId:'w5-demo'})).works[0].topic,'B10');assert.equal((await f.s.board(q,{activityId:'w5-demo'})).works[0].topic,'A04');await f.db.query("update rib.activities set archived=true where id='w5-demo'");await assert.rejects(f.s.chooseTopic(p,{activityId:'w5-demo',topic:'A02',expectedRevision:2}),/封存/);
});
test('topic filtering keeps class and public privacy gates and supports pagination filters',async t=>{const f=await setup(t),[p,q]=f.people;for(const [i,student]of [p,q].entries()){await f.s.chooseTopic(student,{activityId:'w5-demo',topic:i?'B02':'A02',expectedRevision:0});const w=(await f.s.board(student,{activityId:'w5-demo'})).works[0];await(await upload(f,student,w,w.topic)).save();}assert.equal((await f.s.gallery({topic:'A02'})).items.length,1);assert.equal((await f.s.gallery({topic:'B02'})).items.length,1);assert.equal((await f.s.gallery({topic:'A03'})).items.length,0);await assert.rejects(f.s.gallery({topic:'bad'}));const pub=(await f.s.gallery({topic:'A02'})).items[0];assert.equal((await f.s.galleryItem({publicationId:pub.id})).topic,'A02');assert.ok(!JSON.stringify(await f.s.gallery()).includes(p.studentId));await assert.rejects(f.s.classWall(p,{activityId:'w5-demo'}),/尚未開放/);await f.db.query("update rib.activities set phase='exhibit' where id='w5-demo'");const wall=await f.s.classWall(p,{activityId:'w5-demo'});assert.equal(wall.items.length,2);assert.ok(wall.items.every(w=>W5_TOPICS.some(t=>t.id===w.versions[0].metadata.topic)));await f.s.consent(p,{workId:wall.items.find(w=>w.own).id,consent:false});assert.equal((await f.s.gallery({topic:'A02'})).items.length,0);assert.equal((await f.s.classWall(p,{activityId:'w5-demo'})).items.length,2);
});
test('migration preserves existing group works and members, makes a new personal activity, and is idempotent',async t=>{const f=await fixture();t.after(f.close);const s=new Workspace(f.db,f.store),p=f.people[0],w=await s.ensureWork(p,{activityId:'w5-demo'});await s.invite(p,{workId:w.id,studentIds:[f.people[1].studentId]});const members=await f.db.query('select * from rib.members order by student_id');assert.equal((await upgradeW5Personal(f.db)).preserveHistory,1);await upgradeW5Personal(f.db,{apply:true});assert.deepEqual(await f.db.query('select * from rib.members order by student_id'),members);assert.equal((await f.db.query("select archived from rib.activities where id='w5-demo'"))[0].archived,true);assert.equal((await f.db.query("select * from rib.activities where kind='w5-personal'")).length,1);assert.equal((await upgradeW5Personal(f.db,{apply:true})).activities,0);
});
test('weekly steps respect individual/group flows without claiming classroom completion',()=>{const b={activity:{kind:'w5-personal',accepting:true},works:[],invitations:[],reviews:[]};assert.match(activityFlow(b),/選一題/);assert.doesNotMatch(activityFlow(b),/組員/);assert.match(studentNext(b)[0],/先選/);b.works=[{topic:'A02',versions:[]}];assert.match(studentNext(b)[0],/上傳/);b.works[0].versions=[{}];assert.match(studentNext(b)[0],/同題/);for(const kind of ['w3-rebuild','w3-personal','w4','w7','w15-deck'])assert.match(activityFlow({...b,activity:{kind}}),/本週操作步驟/);});

// Topic selection and image upload must accept the same complete bank.
test('all 16 selectable topics upload; teacher practice examples remain excluded',async()=>{
 const {submissionMetadata}=await import('../weekly.mjs');
 for(const topic of W5_TOPICS)assert.equal(submissionMetadata('w5-personal',{topic:topic.id,files:[{}]}).topic,topic.id);
 for(const topic of ['A01','B01','B03','B04','unknown'])assert.throws(()=>submissionMetadata('w5-personal',{topic,files:[{}]}));
});
