import {previewFetch} from './student-preview.js';
import {W8_TOPICS,w8Topic} from './w8-topics.js';
import {W7_TOPICS,w7Topic} from './w7-topics.js';
import {W5_TOPICS,w5Topic} from './w5-topics.js';
import {activityTitle} from './activities.js';
import {learningBrief} from './learning-brief.js';
const $=s=>document.querySelector(s),wall=$('#exhibition'),status=$('#galleryStatus'),box=$('#lightbox'),params=new URLSearchParams(location.search);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const activityId=params.get('activity');let className=params.get('className')||'',data=null,loading=false,generation=0,observer,viewIndex=0,boxRequest=0,mutating=false;
let allItems=[],filterValue='';
const selected=new Map(),pages=new Map(),previews=new Map();let queue=[],running=0;
async function api(action,args={},write=false){const r=await previewFetch('/api/workspace'+(write?'':'?'+new URLSearchParams({action,...args})),{method:write?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:write?{'Content-Type':'application/json'}:{},...(write?{body:JSON.stringify({action,...args})}:{})});const p=await r.json();if(!p.ok)throw Error(p.error||'暫時無法讀取，請再試一次。');return p.data;}
function backLink(){const href='/workspace/?'+new URLSearchParams({activity:activityId||'',...(className?{className}:{})});$('#returnLink').href=href;$('#bottomReturn').href=href;}
backLink();
function version(w){return w.versions.find(v=>v.id===selected.get(w.id))||w.versions.find(v=>v.id===w.currentVersionId)||w.versions.at(-1);}
function caption(w,full=false){const v=version(w),m=v.metadata||{},text=['w3-rebuild','w3-personal'].includes(data.kind)?String(m.text||''):'';
 if(text){const label=data.kind==='w3-personal'?'作者的短文':'本版使用的完整描述';return '<p class="caption-label">'+label+'</p><p class="caption-text">'+esc(full||text.length<=180?text:text.slice(0,180)+'…')+'</p>'+(!full&&text.length>180?'<details class="caption-more"><summary>展開全文</summary><p class="caption-text">'+esc(text)+'</p></details>':'');}
 if(data.kind==='w8-proposal'){const t=w8Topic(m.topic);return '<p class="caption-label">'+esc(m.title||'我的提案')+'</p><p>'+esc(t?t.id+' · '+t.title:m.topic||'')+'</p><p class="caption-note">放大 p.2，看原稿、同學的真實問句與作者修改或保留的理由。</p>';}
 if(data.kind==='w7-news'){const t=w7Topic(m.topic);return '<p class="caption-label">'+esc(t?t.id+' · '+t.title:'新聞 × 研究')+'</p>'+(m.text?'<p class="caption-label">ORID交流紀錄</p><p class="caption-text">'+esc(m.text)+'</p>':'<p class="caption-note">比較同題作品：各組用了哪些依據、這些依據能支持什麼結論，又怎麼畫出來？</p>');}
 const topic=w5Topic(m.topic);if(data.kind==='w5-personal'&&topic)return '<p class="caption-label">'+esc(topic.id)+' · '+esc(topic.title)+'</p><p class="caption-note">'+esc(topic.purpose)+'</p><details class="caption-more"><summary>對照題目原文</summary><p class="caption-text">'+esc(topic.text)+'</p><p>'+esc(topic.question)+'</p><small>'+esc(topic.source)+'</small></details>';
 const note=data.kind==='w7'?(m.topic==='Z'?'動物園':m.topic==='M'?'校園手機':'同一事件，兩種呈現')+(v.ordinal===2?' · 修訂處（放大可對照 V1）':' · 圖文作品'):data.kind==='w15-deck'?(m.purpose||'公共說明作品'):data.kind==='w5-workshop'?'A、B 題作品 · 翻頁查看兩張圖':data.kind==='w4'?'先看畫面，再說說你的理解與根據。':'這一版沒有另存文字說明。';
 return '<p class="caption-note">'+esc(note)+'</p>';
}
function button(label,action,extra=''){return '<button type="button" data-action="'+action+'" '+extra+'>'+label+'</button>';}
function social(w){return (data.kind==='w5-personal'?(w.reflection&&w.reflection.versionId===version(w).id?'<section class="orid-caption"><h3>作者的 ORID 反思 · V'+esc(w.reflection.ordinal)+'</h3><p>回應的同題作品：'+esc(w.reflection.referenceLabel)+'</p>'+[['o','O｜看見'],['r','R｜感受'],['id','I＋D｜學習與運用']].map(([k,l])=>'<p><strong>'+l+'</strong><br>'+esc(w.reflection.answers[k])+'</p>').join('')+'</section>':'')+(!data.teacher&&data.canReflect&&version(w).metadata?.topic===data.ownTopic?'<a class="button" href="'+esc('/workspace/reflection.html?'+new URLSearchParams({activity:activityId,work:data.ownWorkId,...(!w.own?{reference:version(w).id}:{})}))+'">'+(w.own?'回自己的作品寫 ORID':'選這件作品，寫 ORID')+'</a>':''):'')+(data.kind==='w3-rebuild'?'<div class="social-strip"><span>欣賞票 · '+w.votes+'</span>'+(!data.teacher&&data.interactive&&data.votingOpen&&w.canInteract&&!w.own?button(w.liked?'♥ 已欣賞':'♡ 留一張欣賞票','vote','aria-pressed="'+w.liked+'"'):'')+'</div>':'')+
 (w.comments.length||data.interactive?'<details class="comments"><summary>留言與交流 · '+w.comments.length+'</summary>'+w.comments.map(c=>'<div class="comment"><strong>'+esc(c.label)+(c.hidden?' · 已隱藏':'')+'</strong><p>'+esc(c.body)+'</p>'+(data.teacher?button(c.hidden?'恢復留言':'隱藏留言','moderate','data-comment="'+esc(c.id)+'" data-hidden="'+!c.hidden+'"'):'')+'</div>').join('')+
 (!data.teacher&&data.interactive&&w.canInteract?'<form class="comment-form"><label>我注意到的細節／想問作者的問題<textarea name="body" maxlength="240" required></textarea></label><button>送出留言</button><p class="card-status" role="status"></p></form>':!data.teacher&&data.interactive&&!data.canComment?'<p class="caption-note">先回課堂建立自己的作品或由代表加入小組，就能留言交流。</p>':'')+'</details>':'');}
function artHTML(w,index){const v=version(w);return '<button class="frame" data-action="zoom" aria-label="放大'+esc(w.label)+'"><span class="frame-placeholder" role="status">正在掛上作品……</span><span class="zoom-mark" aria-hidden="true">點圖放大 ↗</span></button><div class="image-navigation" hidden></div><div class="placard"><div class="placard-top"><h2>'+esc(w.label)+(w.own?'<span class="own-label">'+(['w3-rebuild','w5-workshop','w15-deck'].includes(data.kind)?'本組':'我的作品')+'</span>':'')+'</h2><span class="catalogue-no">'+String(index+1).padStart(2,'0')+' / '+String(data.items.length).padStart(2,'0')+'</span></div><div class="version-switch" aria-label="'+esc(w.label)+'版本">'+w.versions.map(x=>button('V'+x.ordinal+(x.id===w.currentVersionId?' · 目前選用':''),'version','data-version="'+esc(x.id)+'" aria-pressed="'+(x.id===v.id)+'"')).join('')+'</div><div class="caption">'+caption(w)+'</div><div class="social">'+social(w)+'</div><p class="card-status art-status" role="status"></p></div>';}
function dirty(){return [...document.querySelectorAll('.comment-form textarea')].some(el=>el.value.trim());}
async function load(){if(loading||mutating)return;if(dirty()&&!confirm('有留言尚未送出，確定更新展覽？'))return;loading=true;$('#refresh').disabled=true;status.textContent='正在更新展覽……';wall.setAttribute('aria-busy','true');generation++;const gen=generation;observer?.disconnect();queue=[];previews.clear();
 try{if(!activityId)throw Error('請從課堂活動的「進入課程展廳」開啟這個展覽。');data=await api('classWall',{activityId});allItems=data.items;$('#topicFilterLabel').hidden=!['w5-personal','w7-news','w8-proposal'].includes(data.kind);if(['w5-personal','w7-news','w8-proposal'].includes(data.kind)){const old=$('#topicFilter').value||params.get('topic')||data.ownTopic||'';$('#topicFilter').innerHTML='<option value="">全部題目</option>'+(data.kind==='w8-proposal'?W8_TOPICS:data.kind==='w7-news'?W7_TOPICS:W5_TOPICS).map(t=>'<option value="'+t.id+'">'+esc(t.id+' · '+t.title)+'</option>').join('');$('#topicFilter').value=(data.kind==='w8-proposal'?w8Topic(old):data.kind==='w7-news'?w7Topic(old):w5Topic(old))?old:'';}backLink();$('#exhibitionTitle').textContent=activityTitle(data);document.title=activityTitle(data)+' · 課程展廳｜閱讀理解與表達';$('#edition').textContent=data.term+' 學期 · W'+data.week+' · 課程展廳';$('#exhibitionNote').innerHTML=(learningBrief(data.kind) || '留一點時間，看見彼此的安排。')+(data.kind==='w3-rebuild'&&!data.named?'<p>文字重建挑戰：先匿名欣賞與投票，老師結束投票後再公布作者。</p>':'')+(data.named?'<p>作者姓名只在共同上課班級的登入展廳顯示；對外展覽仍匿名。</p>':'');$('#collectionCount').textContent='一起展出 · '+data.items.length+' 件作品';
 renderCollection();
 }catch(e){data=null;wall.innerHTML='<div class="empty-exhibition"><h2>展覽暫時無法開啟</h2><p>'+esc(e.message)+'</p><a href="'+esc($('#returnLink').href)+'">回課堂登入或查看活動 →</a></div>';status.textContent='';$('#collectionCount').textContent='課程展廳';}
 finally{loading=false;$('#refresh').disabled=false;wall.setAttribute('aria-busy','false');}
}
function renderCollection(){filterValue=$('#topicFilter').value;generation++;observer?.disconnect();queue=[];previews.clear();data.items=allItems.filter(w=>!$('#topicFilter').value||version(w).metadata?.topic===$('#topicFilter').value);$('#collectionCount').textContent=($('#topicFilter').value?$('#topicFilter').value+' · ':'一起展出 · ')+data.items.length+' 件作品';
 wall.innerHTML=data.items.length?data.items.map((w,i)=>'<article class="exhibit" data-work="'+esc(w.id)+'">'+artHTML(w,i)+'</article>').join(''):'<div class="empty-exhibition"><h2>展牆已準備好。</h2><p>'+($('#topicFilter').value?'這個題目還沒有作品。可切回全部題目，或等同學交件後更新展覽。':'這個活動還沒有可展出的作品。交件後，作品就會掛在這裡。')+'</p></div>';
 observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){observer.unobserve(entry.target);queue.push({el:entry.target,gen:generation});}pump();},{rootMargin:'180px'});
 for(const el of wall.querySelectorAll('.exhibit'))observer.observe(el);status.textContent='';
}
$('#topicFilter').onchange=()=>{if(loading||mutating){$('#topicFilter').value=filterValue;return;}if(dirty()&&!confirm('有留言尚未送出，確定切換題目？')){$('#topicFilter').value=filterValue;return;}renderCollection();};
function pump(){while(running<3&&queue.length){const job=queue.shift();if(job.gen!==generation||!job.el.isConnected)continue;running++;loadPreview(job.el).finally(()=>{running--;pump();});}}
async function loadPreview(el){const w=data?.items.find(w=>w.id===el.dataset.work);if(!w)return;const v=version(w),token=String(Number(el.dataset.request||0)+1);el.dataset.request=token;try{const r=await api('media',{versionId:v.id,size:'thumb'});if(!el.isConnected||el.dataset.request!==token||version(w).id!==v.id)return;previews.set(w.id,r);paintPreview(el,w,r);}catch(e){if(el.isConnected&&el.dataset.request===token){el.querySelector('.frame').dataset.action='retry';el.querySelector('.frame').innerHTML='<span class="frame-placeholder">圖片暫時無法讀取 · 點此重試</span>';el.querySelector('.art-status').textContent=e.message;}}}
function pageName(w,i){const v=version(w),topics=v.metadata?.topics;return ['w5-personal','w7-news','w8-proposal'].includes(data.kind)?(v.metadata?.topic||'文字轉圖作品'):data.kind==='w5-workshop'?((i===0?'A 題':'B 題')+(topics?.[i]?' · '+topics[i]:'')):'第 '+(i+1)+' 張';}
function paintPreview(el,w,r){const frame=el.querySelector('.frame'),navigation=el.querySelector('.image-navigation'),page=Math.min(pages.get(w.id)||0,Math.max(0,r.images.length-1));pages.set(w.id,page);frame.dataset.action=r.images.length?'zoom':'retry';frame.innerHTML='';
 if(!r.images.length){frame.innerHTML='<span class="frame-placeholder">目前沒有可顯示的圖片</span>';navigation.hidden=true;return;}
 const img=new Image();img.alt=w.label+' · V'+version(w).ordinal+' · '+pageName(w,page);img.decoding='async';img.onload=()=>{el.querySelector('.art-status').textContent='';};img.onerror=()=>{frame.dataset.action='retry';frame.innerHTML='<span class="frame-placeholder">圖片連結暫時失效 · 點此重試</span>';};img.src=r.images[page].url;frame.append(img);const mark=document.createElement('span');mark.className='zoom-mark';mark.textContent='點圖放大 ↗';mark.setAttribute('aria-hidden','true');frame.append(mark);navigation.hidden=r.images.length<2;navigation.innerHTML=button('←','page','data-step="-1" aria-label="上一張" '+(page===0?'disabled':''))+'<span>'+esc(pageName(w,page))+' / '+r.images.length+'</span>'+button('→','page','data-step="1" aria-label="下一張" '+(page===r.images.length-1?'disabled':''));
}
async function openLarge(index){if(!data?.items[index])return;viewIndex=index;const w=data.items[index],v=version(w),request=++boxRequest;$('#lightboxTitle').textContent=w.label+' · V'+v.ordinal;$('#lightboxPosition').textContent=(index+1)+' / '+data.items.length;$('#previousWork').disabled=index===0;$('#nextWork').disabled=index===data.items.length-1;$('#lightboxContent').innerHTML='<p role="status">正在讀取清晰作品……</p>';if(!box.open)box.showModal();box.scrollTop=0;
 try{const r=await api('media',{versionId:v.id});if(request!==boxRequest||!box.open)return;const content=$('#lightboxContent');content.innerHTML='';for(const [i,m]of r.images.entries()){const figure=document.createElement('figure');figure.className='large-image';const img=new Image();img.src=m.url;img.alt=w.label+' · V'+v.ordinal+' · '+pageName(w,i);img.decoding='async';img.loading=i?'lazy':'eager';img.onerror=()=>{const p=document.createElement('p');p.textContent='這張圖片未能載入，請關閉後再開啟。';img.replaceWith(p);};figure.append(img);if(r.images.length>1){const label=document.createElement('figcaption');label.textContent=pageName(w,i);figure.append(label);}content.append(figure);}
 const label=document.createElement('div');label.className='lightbox-caption';label.innerHTML=caption(w,true);content.append(label);
 if(r.contextImages?.length){const details=document.createElement('details');details.innerHTML='<summary>對照 V1 原作品</summary>';details.addEventListener('toggle',()=>{if(!details.open||details.dataset.loaded)return;details.dataset.loaded='true';for(const m of r.contextImages){const img=new Image();img.src=m.url;img.alt='V1 原作品';img.style.maxWidth='100%';details.append(img);}});content.append(details);}
 }catch(e){if(request===boxRequest)$('#lightboxContent').innerHTML='<p>'+esc(e.message)+'</p><button data-action="largeRetry">重新讀取作品</button>';}
}
async function updateSocial(el,w){const fresh=await api('classWall',{activityId});const open=el.querySelector('.comments')?.open,draft=el.querySelector('textarea')?.value||'',request=el.querySelector('form')?.dataset.request;const updated=fresh.items.find(x=>x.id===w.id);if(!updated)return;Object.assign(w,updated);el.querySelector('.social').innerHTML=social(w);if(open&&el.querySelector('.comments'))el.querySelector('.comments').open=true;if(draft&&el.querySelector('textarea')){el.querySelector('textarea').value=draft;if(request)el.querySelector('form').dataset.request=request;}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='largeRetry'){await openLarge(viewIndex);return;}const el=b.closest('.exhibit'),w=data?.items.find(w=>w.id===el?.dataset.work);if(!w)return;
 if(a==='zoom'){await openLarge(data.items.indexOf(w));return;}
 if(a==='version'){selected.set(w.id,b.dataset.version);pages.set(w.id,0);previews.delete(w.id);el.querySelector('.image-navigation').hidden=true;el.querySelector('.caption').innerHTML=caption(w);el.querySelector('.social').innerHTML=social(w);for(const v of el.querySelectorAll('[data-action=version]'))v.setAttribute('aria-pressed',String(v===b));el.querySelector('.frame').innerHTML='<span class="frame-placeholder">正在換上這一版……</span>';await loadPreview(el);return;}
 if(a==='retry'){await loadPreview(el);return;}
 if(a==='page'){const r=previews.get(w.id);if(r){pages.set(w.id,Math.max(0,Math.min(r.images.length-1,(pages.get(w.id)||0)+Number(b.dataset.step))));paintPreview(el,w,r);}return;}
 if(mutating||loading)return;mutating=true;b.disabled=true;const msg=el.querySelector('.art-status');
 try{if(a==='vote'){await api('wallVote',{workId:w.id,active:!w.liked},true);await updateSocial(el,w);msg.textContent='欣賞票已更新。';}if(a==='moderate'){await api('moderateComment',{commentId:b.dataset.comment,hidden:b.dataset.hidden==='true'},true);await updateSocial(el,w);msg.textContent='留言顯示已更新。';}}catch(err){msg.textContent=err.message;}finally{mutating=false;if(b.isConnected)b.disabled=false;}
});
document.addEventListener('submit',async e=>{if(!e.target.matches('.comment-form'))return;e.preventDefault();if(mutating||loading)return;const form=e.target,el=form.closest('.exhibit'),w=data.items.find(x=>x.id===el.dataset.work),b=form.querySelector('button');mutating=true;b.disabled=true;form.elements.body.disabled=true;form.querySelector('.card-status').textContent='正在送出留言……';form.dataset.request||=crypto.randomUUID();
 try{await api('wallComment',{workId:w.id,body:form.elements.body.value,requestId:form.dataset.request},true);form.elements.body.value='';await updateSocial(el,w);el.querySelector('.art-status').textContent='留言已送出。';}catch(err){form.querySelector('.card-status').textContent=err.message;}finally{mutating=false;if(b.isConnected){b.disabled=false;form.elements.body.disabled=false;}}
});
document.addEventListener('input',e=>{if(e.target.closest('.comment-form'))delete e.target.closest('form').dataset.request;});
window.addEventListener('beforeunload',e=>{if(dirty()||mutating){e.preventDefault();e.returnValue='';}});
$('#refresh').onclick=load;
$('#closeLightbox').onclick=()=>box.close();box.addEventListener('close',()=>{boxRequest++;$('#lightboxContent').replaceChildren();});$('#previousWork').onclick=()=>openLarge(viewIndex-1);$('#nextWork').onclick=()=>openLarge(viewIndex+1);box.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();openLarge(viewIndex-1);}if(e.key==='ArrowRight'){e.preventDefault();openLarge(viewIndex+1);}});
await load();
