import {ALL_TOPICS,topicById} from './topic-bank.js';
const topicFilter=document.querySelector('#topicFilter');for(const t of ALL_TOPICS){const o=document.createElement('option');o.value=t.id;o.textContent=t.id+' · '+t.title;topicFilter.append(o);}
const items=document.querySelector('#galleryItems'),status=document.querySelector('#galleryStatus'),more=document.querySelector('#more'),dialog=document.querySelector('#galleryDetail'),media=document.querySelector('#galleryMedia');let page=0,busy=false,opened=null;
async function api(action,args={}){const r=await fetch('/api/workspace?'+new URLSearchParams({action,...args}),{cache:'no-store'}),p=await r.json();if(!p.ok)throw Error(p.error||'暫時無法讀取，請稍後再試。');return p.data;}
async function load(){if(busy)return;busy=true;more.disabled=true;topicFilter.disabled=true;document.querySelector('#galleryFilter').disabled=true;try{const r=await api('gallery',{page,topic:topicFilter.value,featured:String(document.querySelector('#galleryFilter').value==='featured')});for(const work of r.items){const button=document.createElement('button');button.className='card gallery-card';button.dataset.id=work.id;const label=document.createElement('strong');label.textContent=`W${work.week} · ${work.title}${work.topic?' · '+work.topic+' '+topicById(work.topic).title:''}`;button.append(label);for(const url of work.thumbnails){const img=new Image();img.src=url;img.alt='匿名作品縮圖';img.loading='lazy';img.decoding='async';img.onerror=()=>{img.alt='圖片連結已到期，點選作品重新讀取';};button.append(img);}items.append(button);}page++;more.hidden=!r.hasMore;status.textContent=items.children.length?'點選作品看大圖。':'這個展區還沒有公開作品。';}catch(e){status.textContent=e.message;more.hidden=false;more.textContent='重新讀取';}finally{busy=false;more.disabled=false;topicFilter.disabled=false;document.querySelector('#galleryFilter').disabled=false;}}
items.addEventListener('click',async e=>{const button=e.target.closest('[data-id]');if(!button)return;opened=button.dataset.id;const id=opened;media.textContent='正在讀取作品……';dialog.showModal();try{const work=await api('galleryItem',{publicationId:id});if(opened!==id||!dialog.open)return;media.replaceChildren();const h=document.createElement('h2');h.textContent=`W${work.week} · ${work.title}`;media.append(h);if(work.topic){const t=topicById(work.topic),p=document.createElement('p');p.textContent=t.id+' · '+t.title;media.append(p);}const wrap=document.createElement('div');wrap.className='images';if(work.text){const p=document.createElement('p');p.className='work-text';p.textContent=work.text;media.append(p);}for(const url of [...(work.contextImages||[]),...work.images]){const img=new Image();img.src=url;img.alt='匿名作品大圖';wrap.append(img);}media.append(wrap);}catch(e){if(opened===id)media.textContent=e.message;}});
document.querySelector('#closeGallery').onclick=()=>{opened=null;dialog.close();media.replaceChildren();};dialog.addEventListener('close',()=>{opened=null;media.replaceChildren();});more.onclick=load;load();

document.querySelector("#galleryFilter").onchange=()=>{if(busy)return;page=0;items.replaceChildren();load();};
if(new URLSearchParams(location.search).get("embed")==="1"){document.querySelector("header").hidden=true;document.querySelector("footer").hidden=true;}

topicFilter.onchange=()=>{if(busy)return;page=0;items.replaceChildren();load();};
