import {portfolioHtml} from './portfolio-export.js';
const art=v=>`<div class="tour-art"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 560 340" role="img" aria-label="模擬圖卡：教室門口的人與空位"><rect width="560" height="340" fill="#e9e2cc"/><path d="M0 245H560V340H0Z" fill="#a9ae99"/><rect x="360" y="40" width="145" height="210" fill="#819687"/><rect x="375" y="53" width="115" height="187" fill="#f6edcb"/><circle cx="315" cy="118" r="28" fill="#3c5a4c"/><path d="M285 155H342V265H285Z" fill="#55715e"/><path d="M303 261L293 322M330 261L343 322" stroke="#304b40" stroke-width="15"/><path d="M293 168L${v===2?'215 201':'361 165'}" stroke="#304b40" stroke-width="14"/><rect x="126" y="195" width="92" height="18" fill="#a88658"/><path d="M137 211V286M202 211V286" stroke="#675c42" stroke-width="12"/>${v===2?'<rect x="130" y="171" width="72" height="15" fill="#f3eee0"/><path d="M161 171V188" stroke="#687867" stroke-width="3"/>':''}</svg></div>`;
const frames=[
 ['系統全貌',()=>`<p class="eyebrow">01 · 一學期留下什麼</p><h2>從交作品，到說得出為什麼。</h2><div class="tour-flow"><article><h3>個人作品</h3><p>W3 短文作畫、W4 圖卡、W5 個人文字轉圖、W7 兩種呈現，保留既有版本。</p></article><article><h3>共同成果</h3><p>W3 小組重建、W15–W16 公共說明，由代表核對組員後共同保存。</p></article><article><h3>回看與選錄</h3><p>學期歷程串起已交作品；選重要版本下載，W18 可另外自願選期末精選。</p></article></div><p>作品、回饋、自己修改或保留的決定與教師評閱分開保存。交件數、欣賞票與檔案數都不等於能力分數。</p>`],
 ['個人作品',()=>`<p class="eyebrow">02 · 模擬 W4 圖卡</p><h2>我想說的，和別人讀到的。</h2><div class="tour-grid"><div>${art(1)}<div class="tour-caption"><strong>V1｜門口的空位</strong><p>作者想表達：同學留下位置，等朋友加入。</p></div></div><div><h3>先讓讀者獨立理解</h3><blockquote>我看到一個人站在門邊，像要離開。桌旁沒有其他人，所以有點孤單。</blockquote><h3>作者回看自己的安排</h3><p>我的手勢指向門外，讀者注意到「離開」，沒有看到我想表達的「等待」。</p><p class="muted">這些都是模擬敘述。正式初讀由真人完成；教師合看圖卡與紙本判斷。</p></div></div>`],
 ['回饋與修訂',()=>`<p class="eyebrow">03 · 留下理由，不覆蓋原話</p><h2>改一個線索，再看看。</h2><div class="tour-grid"><div>${art(2)}<div class="tour-caption"><strong>V2｜這裡還有一個位置</strong><p>把手勢轉向桌面，加上攤開的書。</p></div></div><div><h3>作者修改的依據</h3><p>我保留門口的情境，把手改成指向空位，希望「邀請加入」比「離開」更明確。</p><h3>原來的證據仍在</h3><p>V1、同學的回饋、V2 與修改或保留的依據都能回查。也可以有理由保留 V1，不必為了產生版本而修改。</p><p>W7 同學的回饋與修改或保留的依據仍在歷程本；系統不要求重新抄到網站。</p></div></div>`],
 ['小組成果',()=>`<p class="eyebrow">04 · 共同作品，個別責任</p><h2>同一份作品，不用每人重傳。</h2><div class="tour-flow"><article><h3>確認組員</h3><p>代表用同班座號核對姓名後直接加入，不用逐人確認。分錯組可由本人按「離開這個小組」，再請正確代表加入。</p></article><article><h3>保留版本</h3><p>W3 小組作品保留兩次生成；W15–W16 接續同一份五頁作品，修改才新增版本。</p></article><article><h3>接回個人歷程</h3><p>每位組員都能看到共同成果；畫面清楚標成小組作品，不宣稱整件都是個人完成。</p></article></div><p>個別能力與貢獻仍由教師合看本人證據。沒有為了作品集新增每人一份重複填答。</p>`],
 ['教師查閱',()=>`<p class="eyebrow">05 · 兩種查閱方向</p><h2>課堂看全班，評閱看脈絡。</h2><div class="tour-grid"><article><h3>從本週找需要協助的人</h3><p>課堂活動 → 班級交件與讀者任務 → 找尚未收到初讀的作品 → 一鍵補配。</p><p>慢交保留讀者位置；已完成回饋不重抽。兩位共同管理教師皆可查閱授課班級。</p></article><article><h3>從學生看整學期</h3><p>學生學期歷程 → 搜尋學生 → 各週個人／共同作品 → 展開前後版本、同學的回饋與學生修改或保留的決定。</p><p>教師分數不放進匿名展廳；學期歷程僅本人與授權教師可看。</p></article></div><blockquote>先找「學生如何使用回饋」，再判斷要給什麼協助。</blockquote>`],
 ['整理與匯出',()=>`<p class="eyebrow">06 · 帶走重要的作品</p><h2>選錄，不是再交一份。</h2><ol><li>在「我的學期作品」勾選重要版本。</li><li>核對清單與標題；同學初讀預設不收錄，可選私人保存。</li><li>下載圖片已嵌入的 HTML，離線開啟後列印另存 PDF。</li></ol><p>每次最多 12 個版本、36 張圖片，可分批。下載不等於公開；分享前仍須檢查個資。</p><button id="sampleDownload">下載本案例的模擬作品集</button><p class="muted">使用與正式作品集相同的匯出程式；內含模擬 V1、V2、同學的回饋與作者修改或保留的決定，沒有真實學生內容。</p>`]
];
let step=Math.max(0,Math.min(5,Number(location.hash.slice(1))||0));
function render(){document.querySelector('#tourNav').innerHTML=frames.map(([label],i)=>`<button class="secondary" data-step="${i}" ${i===step?'aria-current="step"':''}>${i+1} ${label}</button>`).join('');document.querySelector('#tourBody').innerHTML=frames[step][1]();document.querySelector('#tourPosition').textContent=`${step+1} / 6`;document.querySelector('#tourPrev').disabled=step===0;document.querySelector('#tourNext').disabled=step===5;history.replaceState(null,'','#'+step);}
document.querySelector('#tourNav').onclick=e=>{if(e.target.dataset.step!==undefined){step=Number(e.target.dataset.step);render();}};document.querySelector('#tourPrev').onclick=()=>{step--;render();};document.querySelector('#tourNext').onclick=()=>{step++;render();};
document.addEventListener('click',async e=>{if(e.target.id!=='sampleDownload')return;e.target.disabled=true;try{const work={title:'【模擬】W4 門口的空位',kind:'w4',reviews:[{version_id:'demo-v1',situation:'一個人站在門邊，像要離開。',meaning:'空位讓我感覺孤單。'}],decisions:[{version_id:'demo-v2',choice:'revise',reason:'把手勢轉向空位，加上攤開的書，讓邀請更明確。'}]},items=[];for(const n of [1,2]){const svg=art(n).match(/<svg[\s\S]*<\/svg>/)[0],url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'})),img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=1120;canvas.height=680;canvas.getContext('2d').drawImage(img,0,0,1120,680);URL.revokeObjectURL(url);items.push({work,version:{id:'demo-v'+n,ordinal:n,created_at:'模擬日期',metadata:{text:'【模擬示範，非真實學生作品】'}},images:[canvas.toDataURL('image/jpeg',.9)]});}const url=URL.createObjectURL(new Blob([portfolioHtml({title:'【模擬】從空位到邀請',term:'示範',items,includeFeedback:true})],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='RIB-模擬作品集.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}finally{e.target.disabled=false;}});render();
