import {portfolioHtml} from './portfolio-export.js';
export function createJourneyUI({state,api,app,heading,show,button,esc,say,dialog}){
 let data=null,people=[],selected=new Set(),observer;
 const $=s=>document.querySelector(s),args=()=>({term:data.term,studentId:data.person.studentId});
 async function open(studentId){
 state.activity=null;state.board=null;observer?.disconnect();
 if(state.home.person.role!=='student'&&!studentId){
  const list=await api('studentAccounts',{term:state.termView||state.home.currentTerm});people=list.students;
  heading('學生學期歷程','選一位學生，接著看各週作品、同學初讀與本人改留。');
  app.innerHTML=`${button('← 教學工作台','home','',true)}<section class="panel"><h2>${esc(list.term)} 學期</h2><label>搜尋學生<input id="journeySearch" type="search" placeholder="姓名、班級、座號或學號"></label><div id="journeyPeople"></div><p class="muted">紀錄有無不等於學習成效；紙本歷程本仍須一併查閱。</p></section>`;
  const render=()=>{const q=$('#journeySearch').value.trim();$('#journeyPeople').innerHTML=people.filter(s=>!q||[s.name,s.className,s.seat,s.studentId].join(' ').includes(q)).map(s=>`<article class="account-row"><div><strong>${esc(s.className)} 班 ${s.seat} 號 · ${esc(s.name)}</strong><p class="muted">${esc(s.studentId)}${s.isTest?' · 測試帳號':''}${s.active?'':' · 已停用'}</p></div>${button('查看學期歷程','journeyStudent',`data-id="${esc(s.studentId)}"`,true)}</article>`).join('')||'<p>沒有符合的學生。</p>';};$('#journeySearch').oninput=render;render();return;
 }
 data=await api('journey',state.home.person.role==='student'?{}:{term:state.termView||state.home.currentTerm,studentId});selected=new Set();
 heading(state.home.person.role==='student'?'我的學期作品':`${data.person.name}的學期歷程`,'從作品開始，回看別人怎麼理解，以及自己為什麼改或留。');
 app.innerHTML=`<div class="row">${button('← 課堂活動','home','',true)}${state.home.person.role!=='student'?button('← 選其他學生','journey','',true):''}</div><section class="panel journey-intro"><p class="eyebrow">${esc(data.term)} 學期 · ${data.works.length} 件作品</p><h2>留下作品，也留下改變。</h2><p>展開版本，勾選要帶走的內容，再整理成作品集。沒有紀錄的週次不代表沒有學習；紙本依據仍保留在歷程本。</p>${button('整理所選作品','journeyPreview')} <span id="journeyCount" role="status">尚未選取版本</span></section><div class="journey-list">${data.works.map(w=>`<section class="panel journey-work"><div class="section-title"><h2>${esc(w.title)}</h2><span class="tag">${w.versions.length} 個版本${w.archived?' · 歷史':''}</span></div>${['w3-rebuild','w5-workshop','w15-deck'].includes(w.kind)?'<p class="muted">小組共同作品；下方改留只列這位學生本人的紀錄。</p>':''}${w.versions.map(v=>`<details class="journey-version" data-version="${esc(v.id)}" ${v.id===(w.current_version_id||w.versions.at(-1)?.id)?'open':''}><summary>V${v.ordinal} · ${esc(new Date(v.created_at).toLocaleDateString('zh-TW'))}${v.id===w.current_version_id?' · 目前選用':''}</summary><label class="check-row"><input type="checkbox" data-journey-select="${esc(v.id)}">選入作品集</label>${v.metadata.text?`<p class="journey-text">${esc(v.metadata.text)}</p>`:''}<div class="journey-images" data-journey-media="${esc(v.id)}"><p>展開後讀取圖片</p></div>${w.reviews.filter(r=>r.version_id===v.id).map(r=>`<details><summary>同學當時的理解</summary><p class="journey-text">${esc(r.situation)}</p><p class="journey-text">${esc(r.meaning)}</p></details>`).join('')}${w.decisions.filter(d=>d.version_id===v.id).map(d=>`<blockquote><strong>本人決定${d.choice==='keep'?'保留':'修改'}</strong><p class="journey-text">${esc(d.reason)}</p></blockquote>`).join('')}</details>`).join('')||'<p>目前尚無已交版本。</p>'}</section>`).join('')||'<section class="panel">目前尚無可查閱作品；可先回到課堂活動開始。</section>'}</div>`;
 observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting&&e.target.closest('details').open)load(e.target);},{rootMargin:'150px'});app.querySelectorAll('[data-journey-media]').forEach(x=>observer.observe(x));
 app.querySelectorAll('.journey-version').forEach(el=>el.addEventListener('toggle',()=>{if(el.open)load(el.querySelector('[data-journey-media]'));}));
 app.querySelectorAll('[data-journey-select]').forEach(el=>el.onchange=()=>{if(el.checked)selected.add(el.dataset.journeySelect);else selected.delete(el.dataset.journeySelect);$('#journeyCount').textContent=`已選 ${selected.size} 個版本`;});
 }
 async function load(el){if(el.dataset.loaded)return;el.dataset.loaded='true';try{const media=await api('journeyMedia',{...args(),versionId:el.dataset.journeyMedia});if(!el.isConnected)return;el.innerHTML=media.images.map((m,i)=>`<img src="${esc(m.url)}" alt="作品第 ${i+1} 張" loading="lazy">`).join('');}catch(e){delete el.dataset.loaded;el.textContent=e.message;const retry=document.createElement('button');retry.textContent='重新讀取圖片';retry.onclick=()=>load(el);el.append(retry);}}
 function items(){return data.works.flatMap(work=>work.versions.filter(v=>selected.has(v.id)).map(version=>({work,version})));}
 async function action(el){
 const a=el.dataset.action;if(a==='journey'||a==='journeyStudent'){await open(a==='journeyStudent'?el.dataset.id:undefined);return true;}
 if(a==='journeyPreview'){const chosen=items();if(!chosen.length)throw Error('請先勾選至少一個作品版本。');if(chosen.length>12||chosen.reduce((n,x)=>n+x.version.image_count,0)>36)throw Error('每次最多選 12 個版本、36 張圖；可分成兩份作品集。');
 show(`<h2>整理我的作品集</h2><p>將嵌入 ${chosen.reduce((n,x)=>n+x.version.image_count,0)} 張圖片；可離線開啟，再列印成 PDF。不會上傳或公開這份檔案。</p><ul>${chosen.map(x=>`<li>${esc(x.work.title)} · V${x.version.ordinal}</li>`).join('')}</ul><form id="journeyExport"><label>作品集標題<input name="title" value="我的閱讀與表達作品集" maxlength="100" required></label><label class="check-row"><input type="checkbox" name="feedback">一併收錄同學初讀（私人保存，勿直接公開）</label><label class="check-row"><input type="checkbox" name="confirmed" required>已核對所選版本；分享前會再檢查文字與圖片中的個資</label><p id="formStatus" role="status"></p><button>製作並下載作品集</button></form>`);return true;}
 return false;
 }
 async function submit(form,values){if(form.id!=='journeyExport')return false;if(!values.has('confirmed'))throw Error('請先核對所選版本。');const chosen=items();let total=0,done=0;const count=chosen.reduce((n,x)=>n+x.version.image_count,0);for(const item of chosen){item.images=[];for(let index=0;index<item.version.image_count;index++){const r=await api('journeyMedia',{...args(),versionId:item.version.id,index:String(index),export:'true'});total+=r.dataUrl.length;if(total>55*1024*1024)throw Error('所選作品太大，請減少版本後分批匯出。');item.images.push(r.dataUrl);$('#formStatus').textContent=`正在嵌入圖片 ${++done}／${count}…`;}}
 const html=portfolioHtml({title:values.get('title'),term:data.term,items:chosen,includeFeedback:values.has('feedback')}),url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`RIB-${data.term}-作品集.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);state.dirty=false;dialog.close();say('已下載作品集。開啟 HTML 即可離線查看；以瀏覽器列印另存 PDF。');return true;
 }
 return {action,submit};
}
