import {icon,itemIcon,deskArt} from './visuals.js';
import {studentProgress,studentTaskSummary,progressActionLabel,progressStatusLabel,teacherNextStep} from './progress-model.js';

export function createProgressUI({state,api,esc,openActivity,previewUrl,previewActive,onWeekChange,focusStudent}){
 let data=null,generation=0,week=0,className=null,query='',testOnly=false,initializedKey=null,onlyAction=false,composing=false;
 const host=()=>document.querySelector('#progressDashboard');
 const btn=(text,action,attrs='')=>`<button type="button" class="secondary" data-action="${action}" ${attrs}>${action==='progressRefresh'?icon('refresh'):''}${action==='progressRefresh'?`<span class="progress-refresh-label">${esc(text)}</span>`:esc(text)}</button>`;
 const labels={done:'已保存',missing:'待本人完成',waiting:'等待回饋／材料',dependent:'先完成前一步',blocked:'待開放補存'};
 const key=()=>`rib-nav:${state.home?.currentTerm}:${state.home?.person.studentId||state.home?.person.name}`;
 function initWeek(){if(initializedKey===key())return;initializedKey=key();week=0;const n=Number(new URLSearchParams(location.search).get('week'));if(n>=1&&n<=18)week=n;else if(!previewActive)try{const saved=Number(sessionStorage.getItem(key()));if(saved>=1&&saved<=18)week=saved;}catch{};}
 function rememberWeek(n){if(n>=0&&n<=18){initializedKey=key();week=n;if(!previewActive)try{sessionStorage.setItem(key(),String(n));}catch{}}}
 function navigation(){initWeek();return `<section class="week-entry"><div class="week-entry-copy"><h2>${icon('book')}${week?'目前接續 W'+week:'今天接續哪一週？'}</h2><p>依課堂安排進入教材；各週有不同活動，不是每週都要交作品。</p></div><div class="row"><label>切換週次<select id="progressWeek"><option value="0">請選擇週次</option>${Array.from({length:18},(_,i)=>i+1).map(n=>`<option value="${n}" ${n===week?'selected':''}>W${n}</option>`).join('')}</select></label>${week?`<a class="button" href="/W${week}/">進入 W${week} 教材 →</a>`:''}</div>${deskArt()}</section>`;}
 const target=(i,s)=>btn(s?'查看／處理':progressActionLabel(i),'progressOpen',`data-id="${esc(i.activityId)}" data-section="${esc(i.key)}" data-edit="${!s&&i.state==='missing'}" ${s?`data-student="${esc(s.studentId)}" data-class="${esc(s.className)}"`:''}`);
 const statusIcon=i=>icon(i.state==='done'?'check':i.state==='missing'?'pencil':'clock');
 const list=(items,s)=>items.length?`<ul class="progress-items">${items.map(i=>`<li data-task="${esc(i.key)}" data-state="${esc(i.state)}"><div><span class="progress-badge ${i.state}">${statusIcon(i)}${esc(progressStatusLabel(i))}</span><strong class="progress-item-title">${icon(itemIcon[i.key])}${esc(i.label)}</strong>${!s?`<small class="progress-task-kind">${i.scored?'作品評閱紀錄':'課堂練習・不另計分'}</small>`:''}<p>${esc(i.detail)}${i.state==='blocked'?' 需由老師開放後再保存。':''}</p></div>${target(i,s)}</li>`).join('')}</ul>`:'<p class="muted">目前沒有這一類事項。</p>';
 function render(){const el=host();if(!el||!data)return;const teacher=state.home.person.role!=='student';
 el.innerHTML=`<section class="panel progress-dashboard"><div class="section-title"><div><p class="eyebrow">${teacher?'本次指定收件':'接續自己的下一步'}</p><h2>${icon(teacher?'folder':'pencil')}${teacher?'W4–W5 評閱準備':`本次任務 <span class="week-pair">${esc(data.collection?.title||'紀錄')}</span>`}</h2></div>${btn('更新紀錄','progressRefresh')}</div><div id="progressContent"></div></section>`;
 const content=el.querySelector('#progressContent');
 if(!data.collection){content.innerHTML='<p>這個學期目前沒有指定的補齊清單。各週作品與既有紀錄仍可從下方查看。</p>';return;}
 if(teacher){renderTeacher(content);return;}
 const s=data.students[0];if(!s){content.innerHTML='<p class="notice">無法核對本人紀錄，請重新讀取或洽老師。</p>';return;}
 const p=studentProgress(data,s,18),tasks=studentTaskSummary(p,data.collection);
 for(const i of tasks.actionable.filter(i=>i.key==='image')){const reminder=state.home.reminders?.find(r=>r.activityId===i.activityId);if(reminder)i.detail+=' 老師提醒：'+reminder.message+(reminder.deadline?' 補交日期：'+reminder.deadline:'');}
 const todo=[...tasks.actionable].sort((a,b)=>(b.key==='reader')-(a.key==='reader'));
 content.innerHTML=`<div class="progress-task-summary ${tasks.state}" role="status" data-summary-state="${tasks.state}">${icon(tasks.state==='done'?'check':tasks.state==='missing'?'pencil':'clock')}<div><strong>${esc(tasks.title)}</strong><p>${esc(tasks.detail)}</p></div></div><p class="muted small-text">依本次 W4–W5 任務核對；已交齊表示平台紀錄齊備，內容仍由老師評閱。紙本與 Classroom 依原要求確認。</p>${todo.length?`<section aria-label="現在可以完成"><h3 class="progress-group-title">現在可以完成</h3>${list(todo)}</section>`:''}${tasks.waiting.length?`<details class="progress-section progress-waiting" open><summary>${icon('clock')}等待接續・${tasks.waiting.length} 項</summary>${list(tasks.waiting)}</details>`:''}${tasks.done.length?`<details class="progress-section"><summary>${icon('check')}已保存／送出・${tasks.done.length} 項</summary>${list(tasks.done)}</details>`:''}${manual()}`;
 }
 function manual(){return `<details class="progress-section"><summary>${icon('book')}紙本與其他週次，也可以接續</summary><p>W2／W3 不計分仍有原來的練習與收件安排。紙本及 Classroom 依原入口核對；沒有平台紀錄不能判定整週沒寫。</p><div class="row"><a class="button secondary" href="/W2/">W2 教材與原收件說明</a><a class="button secondary" href="${esc(previewUrl('/workspace/?week=3'))}">W3 作品與練習</a><a class="button secondary" href="/worksheets/#weekly">各週歷程本</a></div></details>`;}
 const cols=[['圖卡','image'],['收到真人初讀','human'],['本人改留','decision'],['W5 判讀','judgment']];
 const itemFor=(p,key)=>p.items.find(i=>i.key===key&&i.scored&&!i.archived);
 const status=i=>!i?'無本次項目':i.state==='done'?(i.key==='judgment'?'已送出':i.key==='human'?'已收到':'已保存'):i.statusLabel||labels[i.state];
 function renderTeacher(content){const classes=[...new Set(data.students.map(s=>s.className))];if(className===null||className&&!classes.includes(className))className=classes[0]||'';
 content.innerHTML=`<div class="progress-toolbar"><label>班級<select id="progressClass"><option value="">全部授課班級</option>${classes.map(c=>`<option value="${esc(c)}" ${className===c?'selected':''}>${esc(c)} 班</option>`).join('')}</select></label><label>找學生<input type="search" id="progressSearch" value="${esc(query)}" placeholder="姓名、座號或學號"></label><label class="progress-action-filter"><input type="checkbox" id="progressOnlyAction" ${onlyAction?'checked':''}>只看需要處理</label></div><div id="progressTeacherRows"></div><div id="progressStudentDetail"></div><p class="muted small-text">已保存只表示有平台紀錄；紙本與 Classroom 仍由老師核對。</p><details class="progress-section"><summary>其他練習與讀者任務</summary><p>文轉圖、ORID 及該生給別人的初讀，從「查看／處理」展開。這些紀錄不與計分證據合算完成率。</p></details><details class="progress-section progress-data-tools"><summary>教師資料範圍</summary><label>資料範圍<select id="progressTest"><option value="false" ${!testOnly?'selected':''}>正式學生</option><option value="true" ${testOnly?'selected':''}>測試學生</option></select></label></details>${manual()}`;
 renderTeacherRows();
 }
 function renderTeacherRows(){const el=document.querySelector('#progressTeacherRows');if(!el)return;
 const rows=data.students.filter(s=>(!className||s.className===className)&&(!query||[s.name,s.studentId,String(s.seat),s.className].some(v=>v.includes(query)))).map(s=>{const p=studentProgress(data,s,18);return {s,p,next:teacherNextStep(p)};}).filter(r=>!onlyAction||r.next.needsAction);
 const cells=p=>cols.map(([,key])=>{const i=itemFor(p,key);return `<span class="progress-badge ${i?.state||''}">${esc(status(i))}</span>`;});
 const action=s=>btn('查看／處理','progressStudent',`data-id="${esc(s.studentId)}"`);
 el.innerHTML=`<div class="progress-matrix-desktop"><table class="progress-matrix"><caption>平台證據 · 每位學生一列</caption><thead><tr><th scope="col">學生</th>${cols.map(([name,key])=>`<th scope="col">${icon(itemIcon[key])}${name}</th>`).join('')}<th scope="col">下一步</th></tr></thead><tbody>${rows.map(({s,p,next})=>`<tr><th scope="row">${esc(s.className)} 班 ${s.seat} 號<br>${esc(s.name)}</th>${cells(p).map(x=>`<td>${x}</td>`).join('')}<td><strong class="teacher-next-step">${esc(next.label)}</strong>${action(s)}</td></tr>`).join('')||'<tr><td colspan="6">沒有符合的學生。</td></tr>'}</tbody></table></div><div class="progress-matrix-mobile">${rows.map(({s,p,next})=>`<article class="progress-mobile-student"><h3>${s.seat} 號 · ${esc(s.name)}</h3><p class="teacher-next-step">${esc(next.label)}</p><dl>${cells(p).map((x,i)=>`<div><dt>${cols[i][0]}</dt><dd>${x}</dd></div>`).join('')}</dl>${action(s)}</article>`).join('')||'<p>沒有符合的學生。</p>'}</div>`;
 }
 function detail(id){const s=data.students.find(s=>s.studentId===id),el=document.querySelector('#progressStudentDetail');if(!s||!el)return;const p=studentProgress(data,s,18),a=data.activities.find(a=>a.kind==='w4'&&!a.archived);el.innerHTML=`<section class="progress-person-detail"><h3>${s.seat} 號 · ${esc(s.name)}</h3>${list(p.items.filter(i=>i.scored&&!i.archived),s)}<details class="progress-section"><summary>其他練習與讀者任務</summary>${list(p.items.filter(i=>!i.scored&&[4,5].includes(i.week)&&!i.archived),s)}</details><div class="row">${a?`<a class="button secondary" href="/workspace/?${esc(new URLSearchParams({previewStudent:s.studentId,previewActivity:a.id}).toString())}" target="_blank" rel="noopener">唯讀學生視角 ↗</a>`:''}${btn('完整學期歷程','journeyStudent',`data-id="${esc(s.studentId)}"`)}</div></section>`;el.scrollIntoView({block:'nearest'});}
 async function load(){const el=host();if(!el)return;const v=++generation;data=null;el.innerHTML='<section class="panel" role="status">正在核對平台紀錄……</section>';try{const r=await api('progress',state.home.person.role==='student'?{}:{term:state.termView||state.home.currentTerm,testOnly:String(testOnly)});if(v!==generation||!el.isConnected)return;data=r;render();}catch(e){if(v===generation&&el.isConnected)el.innerHTML=`<section class="panel"><p role="alert">紀錄尚未讀取：${esc(e.message)}</p>${btn('重新讀取','progressRefresh')}<p>未讀到資料不代表沒有缺項；各週入口仍可使用。</p></section>`;}}
 async function action(el){if(el.dataset.action==='progressRefresh'){await load();return true;}if(el.dataset.action==='progressStudent'){detail(el.dataset.id);return true;}if(el.dataset.action==='progressOpen'){state.className=el.dataset.class||'';await openActivity(el.dataset.id);await focusStudent(el.dataset.student,el.dataset.section,undefined,el.dataset.edit==='true');return true;}return false;}
 document.addEventListener('change',e=>{if(e.target.id==='progressWeek'){rememberWeek(Number(e.target.value));onWeekChange();}if(e.target.id==='progressClass'){className=e.target.value;renderTeacherRows();}if(e.target.id==='progressOnlyAction'){onlyAction=e.target.checked;renderTeacherRows();}if(e.target.id==='progressTest'){testOnly=e.target.value==='true';void load();}});
 document.addEventListener('compositionstart',e=>{if(e.target.id==='progressSearch')composing=true;});
 document.addEventListener('compositionend',e=>{if(e.target.id==='progressSearch'){composing=false;query=e.target.value;renderTeacherRows();}});
 document.addEventListener('input',e=>{if(e.target.id==='progressSearch'&&!e.isComposing&&!composing){query=e.target.value;renderTeacherRows();}});
 return {load,action,navigation,rememberWeek,initWeek,get week(){return week;}};
}
