export function createRosterUI({state,api,show,button,esc,say,dialog}){
 let plan=null,raw='',receipt=null;
 dialog.addEventListener('close',()=>{plan=null;raw='';receipt=null;});
 async function action(el){const a=el.dataset.action;
 if(a==='rosterAdd'){show(`<h2>追加本學期學生</h2><p>從試算表複製四欄：學號、姓名、班級、座號。可含標題列，每批最多 100 人；完全相同者略過，既有資料與六碼不覆蓋。</p><form id="rosterPreview"><label>貼上四欄名單<textarea name="text" rows="8" required placeholder="11500901&#9;範例同學&#9;108&#9;37"></textarea></label><p id="formStatus" role="status"></p><button>預覽新增名單</button></form>`);return true;}
 if(a==='profileEdit'){const list=await api('studentAccounts',{term:state.termView||state.home.currentTerm}),s=list.students.find(s=>s.studentId===el.dataset.id);if(!s?.canManage)throw Error('目前無法修改這位學生。');show(`<h2>修正姓名與座號</h2><p>${esc(s.className)} 班 · 學號 ${esc(s.studentId)}。原六碼與作品保留；學生需重新登入以更新資料。</p><form id="studentProfile" data-student="${esc(s.studentId)}" data-revision="${s.revision}"><label>姓名<input name="name" value="${esc(s.name)}" maxlength="60" required></label><label>座號<input name="seat" type="number" min="1" max="999" value="${s.seat}" required></label><p class="muted">學號與本期班級不在此修改。轉班涉及既有小組、讀者與教師權限，請由維護者核對；下學期轉班可在學期管理設定。</p><p id="formStatus" role="status"></p><button>確認修正資料</button></form>`);return true;}
 if(a==='rosterCodes'&&receipt){const safe=x=>String(x).replace(/[\t\r\n]/g,' ').replace(/^[=+@-]/,"'$&"),content='學期\t學號\t姓名\t班級\t座號\t六碼\n'+receipt.codes.map(s=>[receipt.term,s.studentId,s.name,s.className,s.seat,s.code].map(safe).join('\t')).join('\n'),url=URL.createObjectURL(new Blob(['\uFEFF'+content],{type:'text/plain;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='本批新生登入碼.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return true;}
 return false;}
 async function submit(form,values){if(!['rosterPreview','rosterImport','studentProfile'].includes(form.id))return false;const term=state.termView||state.home.currentTerm;
 if(form.id==='rosterPreview'){raw=values.get('text');plan=await api('rosterPreview',{term,text:raw},true);show(`<h2>核對本批名單</h2><p>新增 ${plan.added.length} 人；完全相同略過 ${plan.skipped.length} 人。</p><ul>${plan.added.map(s=>`<li>${esc(s.className)} 班 ${s.seat} 號 · ${esc(s.name)} · ${esc(s.studentId)}</li>`).join('')}</ul>${plan.added.length?'<form id="rosterImport"><label class="check-row"><input name="confirmed" type="checkbox" required>已核對名單，確認新增並產生個人六碼</label><p id="formStatus" role="status"></p><button>確認新增學生</button></form>':'<p>不需要重複新增。</p>'}`);state.dirty=false;return true;}
 if(form.id==='rosterImport'){if(!values.has('confirmed')||!plan)throw Error('請先預覽並核對名單。');receipt=await api('rosterImport',{term,text:raw,fingerprint:plan.fingerprint,confirmed:true},true);state.dirty=false;show(`<h2>已新增 ${receipt.codes.length} 位學生</h2><p>請立即下載本批登入碼，私下逐一交給本人。關閉後不能查回；遺失可到帳號管理個別重設。</p>${button('下載本批新生登入碼','rosterCodes')}<p>關閉後按「重新載入名單」。</p>`);return true;}
 if(form.id==='studentProfile'){await api('studentProfile',{term,studentId:form.dataset.student,expectedRevision:Number(form.dataset.revision),name:values.get('name'),seat:Number(values.get('seat'))},true);state.dirty=false;dialog.close();say('資料已修正，原六碼保留。請重新載入名單；學生重新登入後會看到新資料。');return true;}
 return false;}
 return {action,submit};
}
