import {w8Topic} from './w8-topics.js';
import {w7Topic} from './w7-topics.js';
import {w5Topic} from './w5-topics.js';
import {ACTIVITY} from './activities.js';
export function createWeeklyUI(ctx){
 const {state,api,show,heading,app,button,esc,images,board,home,say,dialog,uploadFile}=ctx;
 const $=s=>document.querySelector(s);let selectionData=null;
 const selectionCard=(test=false)=>`<button class="card activity-card" data-action="selections" data-test="${test}"><span class="week-mark">W18</span><strong>${test?'【測試】':''}自願選期末精選</strong><span class="muted">選既有作品，零至三件；不用重傳、不計分。</span><span class="card-bottom">${state.home.person.role==='student'?'看看我的作品':'查看自願選件'} →</span></button>`;
 function boardTools(a,teacher=false){if(a.kind==='w8-materials')return '';return `${teacher&&state.home.person.role==='admin'&&a.kind==='w3-rebuild'&&a.phase==='exhibit'&&!a.archived?(a.authorsRevealed?'<p>投票已結束，已公布作者。</p>':button('結束投票並公布作者','revealAuthors','',true)):''}<div class="row weekly-tools">${teacher||a.phase==='exhibit'?'<a class="button secondary" href="'+esc('/workspace/class-gallery.html?'+new URLSearchParams({activity:state.activity,...(state.className?{className:state.className}:{})}))+'">進入課程展廳 →</a>':''}${a.kind==='w3-rebuild'?button('查看教師原圖','original','',true)+(teacher&&state.home.person.role==='admin'&&!a.archived?button('設定教師原圖','reference','',true):''):''}</div>`;}
 function workTools(w,teacher){const a=state.board.activity;return `${a.kind==='w5-personal'&&w.versions.length?'<a class="button secondary" href="'+esc('/workspace/reflection.html?'+new URLSearchParams({activity:a.id,work:w.id,...(teacher?{className:w.class_name}:{})}))+'">'+(teacher?'查看 ORID／檢查匿名副本':w.reflection?.status==='submitted'?'查看／修改我的 ORID':'③ 欣賞同題作品，寫 ORID')+'</a>':''}${!teacher&&a.accepting&&!a.archived&&a.kind==='w7'&&w.versions.length?button('保留目前版本（依據記在歷程本）','paperKeep',`data-id="${esc(w.id)}"`,true):''}${a.kind==='w15-deck'&&w.versions.length?'<p>目前選用：V'+(w.versions.find(v=>v.id===w.current_version_id)?.ordinal||w.versions.at(-1).ordinal)+'</p>':''}${!teacher&&a.accepting&&!a.archived&&a.kind==='w15-deck'?w.versions.map(v=>button('沿用 V'+v.ordinal,'markCurrent',`data-id="${esc(w.id)}" data-version="${esc(v.id)}"`,true)).join(''):''}`;}
 function uploadForm(w){const a=state.board.activity,k=a.kind,img=(label,name='imageA')=>`<label>${label}<input type="file" name="${name}" accept="image/jpeg,image/png,image/webp" required></label>`;
  let fields=img('作品圖片');
  if(['w3-rebuild','w3-personal'].includes(k))fields=`<label>${k==='w3-personal'?'自己的短文':'本版使用的完整描述'}<textarea name="text" maxlength="3000" required></textarea></label>`+fields;
  if(k==='w7-news'){const t=w7Topic(w.topic);if(!t)throw Error('請先完成本組抽題。');fields=`<p><strong>${esc(t.id)} · ${esc(t.title)}</strong></p><p>全組先分享，再選一個交流重點；代表一次送出最後圖卡與一則ORID紀錄，其他組員不用重複交。</p>`+img('最後圖卡（一張照片）')+`<ol><li><strong>O｜我看到哪位同學的什麼具體內容？</strong><br>寫同學姓名，以及作品中的文字、圖法或依據。</li><li><strong>R｜我有什麼感受？</strong><br>新鮮、驚訝、疑惑……都可以。</li><li><strong>I＋D｜這讓我釐清什麼問題，或學到什麼？</strong></li></ol><label>ORID交流紀錄（三問合存一則）<textarea name="text" rows="7" maxlength="1200" required placeholder="O｜看到＿＿（同學姓名）在作品中＿＿（具體內容）。&#10;R｜我覺得＿＿。&#10;I＋D｜我釐清／學到＿＿。">${esc(w.versions.at(-1)?.metadata?.text||'')}</textarea></label><p>紀錄會隨作品供課程展廳閱讀；只需觀察對象的姓名，不必填座號、學號或其他個人資料。</p>`;}

  if(k==='w8-proposal'){const t=w8Topic(w.topic);if(!t)throw Error('請先在小組題材入口完成抽題。');fields=`<p><strong>${esc(t.id)} · ${esc(t.title)}</strong></p><p>每人交自己的提案。先在 p.2 記下同學的真實問句，再用另一色筆修改或說明保留理由；拍清楚整頁，上傳一張照片。挑戰與反思已在紙上，不用重打。</p><label>提案名稱（要改什麼）<input name="title" maxlength="100" required value="${esc(w.versions.at(-1)?.metadata?.title||'')}" placeholder="例如：高鐵聲音處理流程：先詢問，再提醒或協助"></label>`+img('交流後的提案書 p.2（一張完整清楚的照片）')+'<p>送出後請打開照片確認：原稿、問句和修改或保留的理由都看得清楚。拍糊或漏拍可補傳，舊版保留。</p>';}
  if(k==='w7')fields=`${w.versions.length?'': '<label>材料<select name="topic"><option value="Z">動物園</option><option value="M">校園手機</option></select></label>'}<p>V1 保存圖文作品；V2 保存修訂處。同學的回饋與自己修改或保留的理由仍記在歷程本，不必重寫在網站。</p>`+img(w.versions.length?'修訂處 V2':'圖文作品 V1');
  if(k==='w5-personal'){const t=w5Topic(w.topic);if(!t)throw Error('請先選題，再上傳。');fields=`<div class="notice"><strong>${esc(t.id)} · ${esc(t.title)}</strong><p>${esc(t.purpose)}</p></div><p>作品直接畫在歷程本 p.3 的大框。拍清楚題號與完整圖，每人上傳一張；修訂時延續這一題。</p>`+img('歷程本 p.3 的作品圖（一張）');}
  if(k==='w5-workshop')fields='<label>A 區題號<select name="topicA">'+['A02','A03','A04','A05'].map(t=>`<option>${t}</option>`).join('')+'</select></label>'+img('A 題照片','imageA')+'<label>B 區題號<select name="topicB">'+['B02','B03','B05','B06','B07','B08','B09','B10'].map(t=>`<option>${t}</option>`).join('')+'</select></label>'+img('B 題照片','imageB');
  if(k==='w15-deck')fields=`<label>本版用途<select name="purpose">${['試讀版','試讀修訂','發表定稿','提問後修訂'].map(t=>'<option>'+t+'</option>').join('')}</select></label><label>作品形式<select name="layout" id="deckLayout"><option value="slides">五張投影片圖片</option><option value="paper">一張完整 A3 五格照片</option></select></label><div id="deckFiles">${[1,2,3,4,5].map(i=>img('第 '+i+' 頁','page'+i)).join('')}</div><p>各頁順序由上到下。PDF／PPTX 先匯出圖片；沒有修改可以直接沿用既有版本。</p>`;
  if(k==='w4'&&w.versions.length)fields+='<label>根據同學的回饋，我改了什麼？<textarea name="reason" required maxlength="1200"></textarea></label>';
  show(`<h2>${esc(ACTIVITY[k].title)} · 保存 V${w.versions.length+1}</h2><form id="upload" data-work="${esc(w.id)}"><p>每張原圖最多 20 MB。上傳前會縮成適合閱讀的圖片，避免整班下載大圖。</p>${fields}<div id="localPreview" class="images"></div><p class="notice">${k==='w8-proposal'?'提案書供登入的課堂師生查看，保留紙上的作者與提問者姓名；不會自動放到對外展覽。':['w3-personal','w4','w5-personal'].includes(k)?'課堂展廳會顯示作者姓名；對外展覽仍匿名，可在作品下按「不公開」。上傳圖片仍請裁掉姓名、班級座號、人像與私人對話；系統不會自動遮字。':k==='w7-news'?'圖卡照片只保留作品與出處，遮住姓名欄、座號、人像及私人對話。ORID文字依任務寫觀察對象姓名，會隨作品顯示；不需加其他個人資料。可在作品下按「不公開」。':'作品預設匿名展示；可在本週作品下按「不公開」。先裁掉或遮住姓名、班級座號、人像與私人對話；系統不會自動遮字。'}</p><progress id="uploadProgress" max="100" value="0"></progress><p id="formStatus" role="status"></p><button>保存作品</button></form>`);
  if(k==='w15-deck')$('#deckLayout').onchange=()=>{$('#deckFiles').innerHTML=$('#deckLayout').value==='paper'?img('完整 A3 五格照片'):[1,2,3,4,5].map(i=>img('第 '+i+' 頁','page'+i)).join('');delete $('#upload').dataset.request;$('#localPreview').replaceChildren();};
 }
 async function compress(files){if(!files.length)throw Error('請先選圖。');const out=[];for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>20*1024*1024)throw Error('請選 20 MB 以內的 JPG、PNG 或 WebP。');if(file.size<=2*1024*1024){out.push(file);continue;}const bitmap=await createImageBitmap(file),ratio=Math.min(1,3200/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.88));if(!blob||blob.size>8*1024*1024)throw Error('圖片仍太大，請先裁切或縮小後再試。');out.push(new File([blob],'work.jpg',{type:'image/jpeg'}));}return out;}
 async function fileInfo(files){return Promise.all(files.map(async f=>({bytes:f.size,mime:f.type,sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',await f.arrayBuffer()))].map(v=>v.toString(16).padStart(2,'0')).join('')})));}
 async function selections(){state.activity=null;state.board=null;heading('W18 自願選期末精選','選既有作品，不重傳、不計分，也不列缺交。','w18');const teacher=state.home.person.role!=='student';selectionData=await api(teacher?'selectionTeacher':'selections',teacher?{term:state.termView||state.home.currentTerm,testOnly:String(!!state.selectionTest)}:{});app.innerHTML=button('← 課堂活動','home','',true)+(teacher?`<section class="panel"><h2>${state.selectionTest?'測試帳號自願選件':'學生自願選件'}</h2><p>先檢查匿名展示；符合作者意願且目前公開的作品，才能列入精選。</p>${selectionData.items.map(v=>`<article class="work"><h3>${esc(v.class_name)} 班 · ${esc(v.title)} V${v.ordinal}</h3>${button('查看原件','view',`data-id="${esc(v.version_id)}"`,true)} ${!state.selectionTest&&v.publication_id?button('檢查展示','selectionReview',`data-id="${esc(v.publication_id)}"`,true)+button(v.featured?'取消精選':'列入期末精選','selectionFeature',`data-id="${esc(v.publication_id)}" data-featured="${!v.featured}"`):''}</article>`).join('')||'<p>目前沒有學生自願選件。</p>'}</section>`:`<section class="panel"><p>自願選零至三份作品版本，表示希望老師考慮列入精選。選件不會代替公開設定，也不會自動展示；取消後退出精選，原作品保留。</p><form id="selectionSave"><fieldset><legend>我的既有作品版本</legend>${selectionData.candidates.map(v=>`<article class="work"><label><input type="checkbox" name="versions" value="${esc(v.id)}" ${selectionData.selected.includes(v.id)?'checked':''}>${esc(v.title)} · V${v.ordinal}${v.metadata.purpose?' · '+esc(v.metadata.purpose):''}</label>${button('查看這一版','view',`data-id="${esc(v.id)}"`,true)}</article>`).join('')||'<p>目前沒有可選的作品；這不是缺交。</p>'}</fieldset><p id="formStatus" role="status"></p>${selectionData.readOnly?'<p>此學期已封存，可查看原選件。</p>':'<button>保存我的選件</button>'}</form></section>`);}
 async function project(url,container){const r=await fetch(url);if(!r.ok)throw Error('舊專案連結已到期，請重新開啟。');const data=await r.json();const frames=Array.isArray(data.frames)?data.frames:[];const wrap=document.createElement('div');const h=document.createElement('h3');h.textContent='原微故事專案';wrap.append(h);const play=document.createElement('button');play.textContent='播放原專案';const screen=document.createElement('div');wrap.append(play,screen);let timer;const render=i=>{screen.replaceChildren();const f=frames[i];if(!f)return;const src=f.src;if(typeof src==='string'&&/^data:(image\/(jpeg|png|webp)|video\/(mp4|webm));base64,/.test(src)){const el=document.createElement(src.startsWith('data:video/')?'video':'img');el.src=src;if(el.tagName==='VIDEO'){el.controls=true;el.autoplay=true;}el.style.maxWidth='100%';screen.append(el);}const caption=document.createElement('p');caption.textContent=String(f.caption||f.text||'');screen.append(caption);timer=setTimeout(()=>{if(dialog.open&&wrap.isConnected)render(i+1);},Math.min(30,Math.max(1,Number(f.seconds)||3))*1000);};play.onclick=()=>{clearTimeout(timer);render(0);};const a=document.createElement('a');a.href=url;a.textContent='下載原專案 JSON';a.rel='noopener noreferrer';a.target='_blank';wrap.append(a);container.append(wrap);}
 async function action(el){const a=el.dataset.action,id=el.dataset.id;
  if(a==='revealAuthors'){if(confirm('確定大家已投完？公布作者後即停止投票。')){await api('revealAuthors',{activityId:state.activity,expectedRevision:state.board.activity.revision,confirm:true},true);await board();say('投票已結束，重新整理課程展廳即可看到作者。');}return true;}
  if(a==='selections'){state.selectionTest=el.dataset.test==='true';await selections();return true;}
  if(a==='original'){const r=await api('original',{activityId:state.activity});show('<h2>教師原圖</h2>'+r.images.map(url=>`<img class="reference-image" src="${esc(url)}" alt="本週教師原圖">`).join('')+(r.images.length?'':'<p>老師尚未設定原圖。</p>'));return true;}
  if(a==='reference'){show('<h2>設定 W3 教師原圖</h2><form id="referenceUpload"><label>原圖<input type="file" name="image" accept="image/jpeg,image/png,image/webp" required></label><div id="localPreview" class="images"></div><p>只供本活動登入師生查看，不放入公開展廳。</p><p id="formStatus" role="status"></p><button>保存教師原圖</button></form>');return true;}
  if(a==='markCurrent'||a==='paperKeep'){const w=state.board.works.find(w=>w.id===id);await api(a,{workId:id,versionId:el.dataset.version||w.versions.at(-1).id,expectedRevision:w.revision},true);await board();say('已保存選用版本，原件與歷程保留。');return true;}
  if(a==='selectionFeature'){await api(a,{publicationId:id,featured:el.dataset.featured==='true'},true);await selections();say('已更新精選狀態。');return true;}
  if(a==='selectionReview'){const p=selectionData.items.find(v=>v.publication_id===id);show(`<h2>檢查匿名展示</h2><div id="selectionMedia"></div><form id="selectionPublish" data-id="${esc(id)}"><label>匿名標題<input name="title" value="匿名作品" maxlength="80" required></label><label><input type="checkbox" name="reviewed" required>已逐張確認圖片與文字不含個資</label><p>不會繞過作者的不公開設定。</p><p id="formStatus" role="status"></p><button>確認已檢查並公開</button></form>`);await images(p.version_id,$('#selectionMedia'));return true;}
  return false;
 }
 async function submit(form,values){const get=n=>values.get(n);
  if(form.id==='selectionSave'){await api('selectionSave',{versionIds:values.getAll('versions'),expectedRevision:selectionData.revision},true);state.dirty=false;await selections();say('已保存自願選件。');return true;}
  if(form.id==='selectionPublish'){await api('publish',{publicationId:form.dataset.id,title:get('title'),reviewed:values.has('reviewed'),publish:true},true);state.dirty=false;dialog.close();await selections();say('展示檢查已保存；可再選擇是否列入期末精選。');return true;}
  if(form.id==='referenceUpload'){const files=await compress([...form.elements.image.files]),[info]=await fileInfo(files);form.dataset.request||=crypto.randomUUID();const r=await api('referencePrepare',{activityId:state.activity,file:info,requestId:form.dataset.request},true);if(!r.saved){$('#formStatus').textContent='正在上傳原圖……';await uploadFile(r.url,files[0],()=>{});await api('referenceFinalize',{ticketId:r.ticketId},true);}state.dirty=false;dialog.close();say('本週教師原圖已保存。');return true;}
  return false;
 }
 return {selectionCard,boardTools,workTools,uploadForm,compress,fileInfo,selections,project,action,submit};
}
