import {isW8,W8_TITLE,W8_DESCRIPTION,mergeW8Entries,w8EntryStatus,createW8FlowUI} from './w8-flow.js';
import {w9Values,w9Evidence} from './w9-evidence.js';
import {installButtonHelp} from './button-help.js';
import {teacherHelp} from './teacher-help.js';
import {previewFetch,previewUrl,previewActive,previewPicker} from './student-preview.js';
import {createW4RemediationUI} from './w4-remediation-ui.js';
import {createW8MaterialsUI} from './w8-materials-ui.js';
import {createAiJudgmentUI} from './ai-judgment-ui.js';
import {topicById} from './topic-bank.js';
import {activityFlow} from './activity-flow.js';
import {createTopicUI} from './topic-ui.js';
import {learningBrief} from './learning-brief.js';
import {createJourneyUI} from './journey-ui.js';
import {createRosterUI} from './roster-ui.js';
import {ACTIVITY,isGroup,canUpload,activityTitle} from './activities.js';
import {createWeeklyUI} from './weekly-ui.js';
import {createAccountsUI} from './accounts-ui.js';
import {phaseLabel,supported,workFlags,matchesWork,missingStudents,studentNext} from './ui-model.js';
const $=s=>document.querySelector(s),app=$('#app'),notice=$('#notice'),dialog=$('#detail');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={config:null,home:null,activity:null,board:null,className:'',cursor:null,busy:false,dirty:false,termView:null,termData:null,issued:null,classes:[],roster:[],workFilter:'all',query:'',studentView:'work'};
installButtonHelp({enabled:()=>!!state.home&&state.home.person.role!=='student'});
const button=(label,action,data='',secondary=false)=>`<button type="button" ${secondary?'class="secondary"':''} data-action="${action}" ${data}>${label}</button>`;
async function api(action,data={},write=false){const response=await previewFetch('/api/workspace'+(write?'':'?'+new URLSearchParams({action,...data})),{method:write?'POST':'GET',credentials:'same-origin',headers:write?{'Content-Type':'application/json'}:{},...(write?{body:JSON.stringify({action,...data})}:{})});const payload=await response.json();if(!payload.ok)throw new Error(payload.error||'暫時無法完成，請稍後再試。');return payload.data;}
function say(s,error=false){notice.textContent=s;notice.className=error?'error':'';}
function show(html){$('#detailBody').innerHTML=html;const title=$('#detailBody h2');if(title){title.id='dialogTitle';dialog.setAttribute('aria-labelledby','dialogTitle');}if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}
function heading(title,subtitle='',kind=''){document.querySelector('#learningBrief').innerHTML=isW8({kind})?'<details><summary>本週學習重點</summary>'+learningBrief(kind)+'</details>':learningBrief(kind);document.querySelector('.intro h1').textContent=title;$('#pageSubtitle').textContent=subtitle;document.title=title+'｜閱讀理解與表達';}
$('#closeDialog').onclick=()=>{if(state.busy)return;if(state.dirty&&!confirm('內容還沒送出。確定關閉？'))return;state.dirty=false;dialog.close();};
dialog.addEventListener('cancel',e=>{if(state.busy||state.dirty)e.preventDefault();});
document.addEventListener('input',e=>{if(e.target.closest('#detail'))state.dirty=true;});
window.addEventListener('beforeunload',e=>{if(state.busy||state.dirty){e.preventDefault();e.returnValue='';}});
async function guard(fn){if(state.busy)return;state.busy=true;document.body.classList.add('busy');app.setAttribute('aria-busy','true');const active=document.activeElement,btn=active?.tagName==='BUTTON'?active:null;if(btn)btn.disabled=true;try{await fn();}catch(e){say(e.message,true);const inline=$('#formStatus');if(inline)inline.textContent=e.message;}finally{state.busy=false;document.body.classList.remove('busy');app.removeAttribute('aria-busy');if(btn?.isConnected)btn.disabled=false;}}
const remediation=createW4RemediationUI({state,api,show,esc,images,board,say,dialog});
const aiJudgment=createAiJudgmentUI({state,api,show,esc,board,say,dialog});
const topics=createTopicUI({state,api,show,esc,board,say,dialog});
const {student:w8StudentPanel,teacher:w8TeacherPanel,render:w8RenderWorks}=createW8MaterialsUI({state,esc,button,topics});
const w8Flow=createW8FlowUI({state,esc,button,workCard,boardTools:a=>weekly.boardTools(a)});
const weekly=createWeeklyUI({state,api,show,heading,app,button,esc,images,board,home,say,dialog,uploadFile});
const accounts=createAccountsUI({state,api,app,heading,show,dialog,button,esc,say});
const journey=createJourneyUI({state,api,app,heading,show,dialog,button,esc,say});
const rosterUI=createRosterUI({state,api,show,dialog,button,esc,say});
function login(){$('#identity').textContent='';heading('每一次理解，都留下來。','保存作品、聽見同學的理解，再決定修改或保留。');app.innerHTML=`<div class="login-layout"><section class="panel login-card"><p class="eyebrow">STUDENT · 學生入口</p><h2>回到我的作品</h2><p class="muted">使用原本的學號與個人六碼。</p><form id="login"><label>學號<input name="studentId" inputmode="numeric" autocomplete="username" pattern="[0-9]{8}" placeholder="輸入 8 碼學號" required></label><label>個人六碼<input name="code" type="password" inputmode="numeric" autocomplete="current-password" pattern="[0-9]{6}" maxlength="6" placeholder="輸入老師發的 6 碼" required></label><label>學期<input name="term" inputmode="numeric" pattern="[0-9]{3}0[12]" value="${esc(state.config?.currentTerm||'11501')}" required></label><label class="check-row"><input type="checkbox" name="remember">這是我的裝置，記住登入 30 天</label><p id="formStatus" role="status"></p><button class="full-width">進入我的作品</button></form><p class="muted small-text">共用裝置請勿勾選記住登入。忘記六碼時請洽老師。</p></section><aside class="login-aside"><p class="eyebrow">TEACHER · 教師入口</p><h2>掌握全班的進度</h2><p>查看兩班作品、安排讀者、回應學生，並保留每一學期的學習歷程。</p>${state.config?.teacherLogin?'<a class="button" href="/api/workspace?action=teacher-start">以 Google 教師帳號登入 →</a>':'<p class="muted">教師 Google 登入設定中。</p>'}<div class="login-note"><strong>作品屬於學習，選擇留給自己。</strong><p>作品預設匿名展示；每件作品都能選擇不公開，交件與回饋照常。</p></div></aside></div>`;}
async function home(){say('');state.home=await api('home');state.activity=null;state.board=null;const p=state.home.person;$('#identity').textContent=p.role==='student'?`${p.className} 班 ${p.seat} 號 · ${p.name}`:`${p.name} · 教師管理`;$('#logout').hidden=false;
  renderHome();window.scrollTo(0,0);if(!state.home.agreementRequired){const params=new URLSearchParams(location.search),requested=params.get('activity');if(requested&&state.home.activities.some(a=>a.id===requested)){state.className=params.get('className')||'';history.replaceState(null,'',previewUrl(location.pathname));await openActivity(requested);return;}const week=Number(new URLSearchParams(location.search).get('week'));if(week===18){history.replaceState(null,'',previewUrl(location.pathname));await weekly.selections();return;}if([3,4,5,7,8,9,15,16].includes(week)){const section=new URLSearchParams(location.search).get('section'),wantedWeek=week===16?15:week;const target=state.home.activities.find(a=>a.week===wantedWeek&&(week!==8||(section==='proposal'?a.kind==='w8-proposal':a.kind==='w8-materials'))&&(week!==3||(section==='personal'?a.kind==='w3-personal':a.kind==='w3-rebuild'))&&!a.archived&&supported(a)&&a.test_only===(p.role==='student'&&p.isTest===true));history.replaceState(null,'',previewUrl(location.pathname));if(target)await openActivity(target.id);}}}
function renderHome(){
 if(state.home.agreementRequired){renderAgreement();return;}
 const p=state.home.person,teacher=p.role!=='student',terms=[...new Set(state.home.activities.map(a=>a.term))];
 if(!terms.includes(state.termView))state.termView=terms.includes(state.home.currentTerm)?state.home.currentTerm:terms[0];
 heading(teacher?'教學工作台':'我的學習作品',teacher?'先選活動，再查看班級進度與需要協助的同學。':'選擇課堂正在進行的活動，接著完成自己的下一步。');
 const activities=mergeW8Entries(state.home.activities.filter(a=>!teacher||a.term===state.termView)),current=activities.filter(a=>supported(a)&&!a.archived&&(!teacher||!a.test_only)).sort((a,b)=>a.week-b.week||(a.kind==='w3-rebuild'?-1:b.kind==='w3-rebuild'?1:0)),testing=teacher?activities.filter(a=>supported(a)&&!a.archived&&a.test_only):[],history=activities.filter(a=>!current.includes(a)&&!testing.includes(a));
 const cards=list=>list.map(a=>`<button class="card activity-card" data-action="activity" data-id="${esc(a.id)}"><span class="card-top"><span class="week-mark">W${a.week===15?'15–W16':a.week}</span><span class="tag">${a.test_only?'測試活動':esc(isW8(a)?w8EntryStatus(state.home.activities,a):phaseLabel(a,state.config))}</span></span><strong>${esc((isW8(a)?W8_TITLE:activityTitle(a)).replace(/^W\d+(?:[–-]W?\d+)?\s*/,''))}</strong><span class="muted">${esc(isW8(a)?W8_DESCRIPTION:ACTIVITY[a.kind]?.description||'早期課程 · 原件與歷程查閱')}</span><span class="card-bottom">${esc(a.term)} 學期<span>${teacher?'查看班級':'進入作品'} →</span></span></button>`).join('');
 app.innerHTML=`${remediation.reminders()}<div class="home-toolbar"><div class="row">${teacher?`<label class="term-filter">查看學期<select id="termView">${terms.map(t=>`<option value="${esc(t)}" ${state.termView===t?'selected':''}>${esc(t)}${state.home.currentTerm===t?' · 目前學期':' · 歷史查閱'}</option>`).join('')}</select></label>`:`<span class="tag">${esc(state.home.currentTerm)} 學期</span>`}</div><div class="row">${button(teacher?'學生學期歷程':'我的學期作品','journey','',true)}<a class="button secondary" href="/workspace/${teacher?'teacher-guide':'guide'}.html" target="_blank" rel="noopener">${teacher?'每週操作速查':'系統導覽與期末示範'} ↗</a>${teacher?button('系統維護','maintenance','',true):''}${teacher?button('學生帳號與登入碼','studentAccounts','',true):''}${p.role==='admin'?button('學期管理','termManager','',true)+button('搬遷封存紀錄','archive','',true):''}${!teacher?button('匿名展示說明','sharingInfo','',true):''}</div></div><section aria-labelledby="activitiesTitle"><div class="section-title"><h2 id="activitiesTitle">課堂活動</h2><span class="muted">${current.length} 個活動</span></div><div class="grid activity-grid">${cards(current)||'<div class="empty-state">目前沒有開放的課堂活動，可在下方查閱歷史紀錄。</div>'}${weekly.selectionCard()}</div></section>${testing.length?`<details class="history-section"><summary>測試活動 · ${testing.length}</summary><p class="muted">供教師與測試學生驗收，不列入正式班級或公開展廳。</p><div class="grid">${cards(testing)}${weekly.selectionCard(true)}</div></details>`:''}${history.length?`<details class="history-section" ${current.length?'':'open'}><summary>歷史與封存活動 · ${history.length}</summary><p class="muted">保留原有作品與學習紀錄。</p><div class="grid">${cards(history)}</div></details>`:''}`;
}
function agreementContent(){const a=state.home.sharingAgreement;return `<h2>${esc(a.title)}</h2>${a.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}`;}
function renderAgreement(){heading("開始之前，先了解作品怎麼展示","每學期確認一次，每件作品仍可自行選擇不公開。");app.innerHTML=`${remediation.reminders(false)}<section class="panel agreement-panel">${agreementContent()}<form id="agreement"><label><input type="checkbox" name="accepted" required>我已閱讀並同意上述匿名展示與個資保護說明，知道可以逐件選擇不公開。</label><p id="formStatus" role="status"></p><button>同意並進入作品區</button></form></section>`;}
const rosterText=students=>students.map(s=>[s.studentId,s.name,s.className,s.seat].join('\t')).join('\n');
async function termManager(){
 heading('學期管理','先準備與核對，再切換。既有作品與登入碼保留。');state.activity=null;state.board=null;state.termData=await api('terms');const t=state.termData;
 app.innerHTML=`${button('← 回作品首頁','home','',true)}<section class="panel"><h2>學期管理</h2><p>目前學期：<strong>${esc(t.currentTerm)}</strong>。查閱其他學期不會改變學生入口。</p><p>新學期先存草稿；核對名單、共同授課教師與活動後，再啟用。既有作品與歷史不覆蓋。</p>${!t.activationAllowed?'<p class="notice">驗收站可以儲存草稿；正式啟用功能保持關閉，目前學期不受影響。</p>':''}${button('準備新學期','termEdit')}<h3>學期草稿</h3>${t.drafts.filter(d=>d.status==='draft').map(d=>`<article class="work"><strong>${esc(d.sourceTerm)} → ${esc(d.term)}</strong><p>${d.summary.total} 人 · ${d.summary.classes.map(esc).join('、')} 班 · 第 ${d.revision} 版</p>${button('核對摘要','termSummary',`data-id="${esc(d.term)}"`,true)} ${button('編輯草稿','termEdit',`data-id="${esc(d.term)}"`,true)}</article>`).join('')||'<p class="muted">尚未建立新學期草稿。</p>'}<h3>切換紀錄</h3>${t.history.map(h=>`<article class="work"><p>${esc(h.from_term)} → ${esc(h.to_term)} · ${esc(h.actor)} · ${esc(h.created_at)}</p>${button('下載切換前備份','termBackup',`data-id="${esc(h.id)}"`,true)}</article>`).join('')||'<p class="muted">目前沒有切換紀錄。</p>'}</section>`;
}
function termEdit(term){const t=state.termData,d=t.drafts.find(d=>d.term===term),source=t.currentTerm,next=source?.endsWith('01')?source.slice(0,3)+'02':String(Number(source?.slice(0,3))+1)+'01';
 show(`<h2>準備新學期</h2><p>來源學期 ${esc(source)}；儲存草稿不會切換入口，也不會關閉舊活動。</p><form id="termSave" data-revision="${d?.revision||0}"><label>新學期代碼<input name="term" value="${esc(d?.term||next)}" pattern="[0-9]{3}0[12]" ${d?'readonly':''} required></label><label>新學期學生名單<textarea name="rosterText" class="roster-input" maxlength="26000" required spellcheck="false">${esc(rosterText(d?.students||t.roster))}</textarea></label><p class="muted">從試算表複製四欄：學號、姓名、班級、座號（Tab 分隔，可含標題）。預填的是原名單，請核對轉班與離班；測試帳號不帶入。</p><fieldset><legend>共同授課教師（皆可查看與評閱新學期所有班級）</legend>${t.teachers.map(x=>`<label><input type="checkbox" name="teachers" value="${esc(x.email)}" ${(!d||d.teachers.includes(x.email))?'checked':''}>${esc(x.name)} · ${esc(x.email)}${x.role==='admin'?'（管理員）':''}</label>`).join('')}</fieldset><p>原學生沿用六碼，新生自動產生六碼。新生碼只在產生後提供下載，請立即保存，系統不存明文。</p>${d?'<label><input type="checkbox" name="reissue">重新產生此草稿新生的六碼（原學生六碼不變）</label>':''}<p id="formStatus" role="status"></p><button>儲存草稿並核對</button></form>`);
}
function termSummary(term){const d=state.termData.drafts.find(d=>d.term===term),s=d.summary,t=state.termData;const names=ids=>ids.map(id=>d.students.find(s=>s.studentId===id)?.name||t.roster.find(s=>s.studentId===id)?.name||id).map(esc).join('、');
 show(`<h2>核對 ${esc(d.sourceTerm)} → ${esc(d.term)}</h2><p>第 ${d.revision} 版 · ${s.total} 人 · ${s.classes.map(esc).join('、')} 班</p><ul><li>沿用六碼 ${s.retained.length} 人</li><li>新生 ${s.added.length} 人：${names(s.added)||'無'}</li><li>轉班／座號變更 ${s.moved.length} 人：${names(s.moved)||'無'}</li><li>本期不列入 ${s.removed.length} 人：${names(s.removed)||'無'}；舊作品仍保留。</li></ul><p>共同授課：${d.teachers.map(e=>esc(t.teachers.find(x=>x.email===e)?.name||e)).join('、')}，均可看與評閱全部班級；既有管理員仍保有管理權限。</p><details><summary>核對完整名單與 ${s.activityCount} 個活動</summary><pre class="archive-record">${esc(rosterText(d.students))}</pre><ul>${d.templates.map(a=>`<li>W${a.week} · ${esc(a.title)}</li>`).join('')}</ul></details>${state.issued?.term===term&&state.issued.codes.length?`<p class="notice">請先下載並妥善保存新生六碼，關閉頁面後不再顯示。</p>${button('下載新生登入碼（文字檔）','termCodes','',true)}`:''}${s.unavailable.length?`<p class="notice">下列歷史模式尚未完成新系統操作，只保留活動設定並停寫：${s.unavailable.map(esc).join('、')}。需要使用時仍走原入口。</p>`:''}<p>啟用前會將完整資料快照存入私有儲存空間，並讀回核對；失敗則整次切換取消。新活動先停寫，由老師課前開放。</p>${t.activationAllowed?`<form id="termActivate" data-term="${esc(term)}" data-revision="${d.revision}"><label><input name="confirmed" type="checkbox" required>已核對名單、登入碼及共同授課權限</label>${s.unavailable.length?'<label><input name="unsupported" type="checkbox" required>我已確認歷史模式仍需原入口，尚不能完整取代舊系統</label>':''}<label>輸入 ${esc(term)} 確認啟用<input name="confirmTerm" autocomplete="off" required pattern="${esc(term)}"></label><p id="formStatus" role="status"></p><button>備份並啟用新學期</button></form>`:'<p class="notice">驗收期間不能正式啟用。你可以核對、編輯草稿，目前學期維持不變。</p>'}`);
}
function downloadCodes(){const row=state.issued;if(!row)return;const safe=x=>String(x).replace(/[\t\r\n]/g,' ').replace(/^[=+@-]/,"'$&");const content='學期\t學號\t姓名\t班級\t座號\t六碼\n'+row.codes.map(c=>[row.term,c.studentId,c.name,c.className,c.seat,c.code].map(safe).join('\t')).join('\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+content],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`${row.term}-新生登入碼.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

async function loadRoster(){const r=await api('roster',{activityId:state.activity,className:state.className});state.roster=r.students;}
async function openActivity(activityId){say('');state.activity=activityId;state.cursor=null;state.workFilter='all';state.query='';state.studentView='work';const teacher=state.home.person.role!=='student';if(teacher){const r=await api('classes',{activityId});state.classes=r.classes;state.className=r.classes.includes(state.className)?state.className:r.classes[0]||'';if(state.className)await loadRoster();else state.roster=[];}await board();if(previewActive||isW8(state.board.activity))history.replaceState(null,'',previewUrl(location.pathname+'?'+new URLSearchParams({activity:activityId,...(state.className?{className:state.className}:{})})));window.scrollTo(0,0);}
async function board(){
 const expanded=[...document.querySelectorAll('[data-work-details][open]')].map(el=>el.dataset.workDetails),queues=[...document.querySelectorAll('.queue')].map(el=>el.open),focusId=document.activeElement?.id,scroll=window.scrollY;
 const b=await api('board',{activityId:state.activity,...(state.className?{className:state.className}:{})});state.board=b;const teacher=state.home.person.role!=='student',a=b.activity;
 if(!teacher)state.home.reminders=b.reminders||[];
 state.aiJudgments=a.kind==='w5-personal'?(await api('aiJudgments',{activityId:state.activity,...(teacher?{className:state.className}:{})})).responses:[];
 b.aiJudgments=state.aiJudgments;
 state.w8MaterialsBoard=!teacher&&a.kind==='w8-proposal'&&b.relatedActivityId?await api('board',{activityId:b.relatedActivityId}):null;
 heading(isW8(a)?W8_TITLE:activityTitle(a),teacher?(a.kind==='w8-materials'?'查看小組名單與本班題材分配。':'查看班級交件、作品版本與需要協助的同學。'):ACTIVITY[a.kind]?.description||'查閱原件與歷程。',a.kind);
 app.innerHTML=`${teacher?'':remediation.reminders()}<div class="board-toolbar"><div class="row">${button('← 課堂活動','home','',true)}<span class="tag">${esc(phaseLabel(a,state.config))}</span>${a.testOnly?'<span class="tag test-tag">測試活動</span>':''}</div><button class="secondary refresh-button" data-action="refresh" aria-label="更新作品與回饋"><span class="refresh-long">更新作品與回饋</span><span class="refresh-short">更新</span></button></div>${a.archived?'<p class="notice">此學期已封存，作品、回饋與評閱保留查閱。</p>':''}${w8Flow.nav(b)}${teacher?previewPicker(state)+teacherHelp(a)+aiJudgment.panel()+teacherPanel(b):studentPanel(b)}${readingPanel(b,teacher)}`;
 if(!teacher&&a.kind!=='w4'&&!b.reviews.length)state.studentView='work';
 if(teacher){renderWorks();for(const el of document.querySelectorAll('[data-work-details]'))el.open=expanded.includes(el.dataset.workDetails);document.querySelectorAll('.queue').forEach((el,i)=>{if(queues[i])el.open=true;});}else setStudentView(state.studentView);
 if(['classChoice','workFilter','workSearch'].includes(focusId))document.getElementById(focusId)?.focus({preventScroll:true});window.scrollTo(0,scroll);
}
function readingPanel(b,teacher){
 const rows=b.aiReadings||[];if(!rows.length)return '';
 return `<section class="panel ai-reading-panel"><p class="eyebrow">W5 · 圖卡與甲乙留言</p><h2>甲乙兩種讀法</h2><p>讀圖，再逐句檢查留言的根據。W5 只找一句黃或紅的留言，判讀與改後一句直接在平台填寫。</p><div class="row">${rows.map(r=>button((teacher?r.seat+' 號 · ':'')+(r.isDemo?r.label:'W4 V'+r.ordinal)+(r.has_pair?' 的甲乙留言':' 的圖卡提醒')+(teacher&&r.status!=='published'?'（'+({draft:'草稿',withdrawn:'已收回'}[r.status])+ '）':''),'aiReading',`data-id="${esc(r.id)}"`,true)).join('')}</div><p class="muted">AI 模擬留言，供核對畫面證據使用。</p></section>`;
}
async function openReading(id){
 const r=await api('aiReading',{readingId:id});
 show(`<h2>${r.commentA?'甲乙兩種讀法':'圖卡提醒'}</h2><p>對照${r.isDemo?esc(r.label):`你的 W4 V${r.ordinal} 圖卡`}${r.commentA?'，逐句找根據':''}。</p>${r.taskNote?`<section class="notice"><h3>圖卡要求與提醒</h3><p>${esc(r.taskNote)}</p></section>`:''}<div class="ai-reading-image"><img src="${esc(r.imageUrl)}" alt="這份甲乙留言所對照的圖卡"></div>${r.commentA?`<div class="ai-reading-comments"><section><h3>甲</h3><p>${esc(r.commentA)}</p></section><section><h3>乙</h3><p>${esc(r.commentB)}</p></section></div><p class="notice">綠：畫面支持；紅：畫面直接反駁；黃：目前證據不足。請在 W5 平台摘一句黃或紅的留言，寫畫面依據並改寫，不用抄進歷程本。</p>`:''}${r.recordLocked?'<p class="notice">送出這份圖卡的 AI 留言判讀後，這裡才會顯示判讀紀錄與依據；保存草稿尚未開放。</p>':''}${r.studentRecord?`<section class="panel"><h3>${r.studentRecord.kind==='joint'?'共同判讀紀錄與依據':'AI 判讀紀錄與依據'}</h3><p>${esc(r.studentRecord.disclosure)}</p>${[['aiObservation','AI 的讀圖與疑問'],['teacherReply','老師的回覆'],['result','這次如何處理'],['basis','甲乙判讀依據'],['limit','仍需保留的界線']].filter(([k])=>r.studentRecord[k]).map(([k,label])=>`<h4>${label}</h4><p>${esc(r.studentRecord[k])}</p>`).join('')}</section>`:''}${r.teacherNotes?`<details><summary>內部判讀備註（僅教師可見）</summary><p>${esc(r.teacherNotes.evidence||'')}</p><p>${esc(r.teacherNotes.judgment||'')}</p><p>${esc(r.teacherNotes.limit||'')}</p><p>${esc(r.teacherNotes.record||'')}</p></details>`:''}`);
}
function studentPanel(b){
 if(b.activity.kind==='w8-materials')return w8StudentPanel(b);
 if(b.activity.kind==='w8-proposal')return w8Flow.proposal(b);
 const a=b.activity,[title,description]=studentNext(b,state.config),w=b.works[0],invites=b.invitations.length?'<p class="notice">小組名單正在更新，請稍後按「更新作品與回饋」。不用逐人確認加入。</p>':'';
 const tasks=b.reviews.map(r=>`<article class="reader-task">${r.teacherCovered?'<p class="notice">已由老師補讀。你的初讀任務沒有被代填，仍可看圖並補充自己的理解。</p>':''}<span class="tag">${{waiting:'等待作品',assigned:'輪到我初讀',done:'已送出初讀',requested:'等待老師協助'}[r.status]||'初讀任務'}</span><h3>${{waiting:'作者還在製作，任務為你保留',assigned:'先看圖，再說出你的理解',done:'我的初讀已送出',requested:'已申請更換作品'}[r.status]||'查看任務'}</h3><p>${r.status==='waiting'?'晚交的同學也需要讀者；作品送到後會出現在這裡。':r.status==='assigned'&&a.phase==='production'?'等老師開放初讀後，就能打開作品。':r.status==='assigned'&&a.phase==='exhibit'?'展示階段仍可完成補讀；若已知原意，請申請更換作品。':r.status==='done'?'可以查看對話，接著向作者提問或回應。':'先獨立閱讀，不用猜作者的標準答案。'}</p><div class="row">${!a.archived&&r.status==='assigned'&&a.accepting&&['review','exhibit'].includes(a.phase)?button('看圖並留下初讀','read',`data-id="${esc(r.id)}"`):''}${r.status==='done'?button('查看與回覆','conversation',`data-id="${esc(r.id)}"`,true):''}${!a.archived&&['waiting','assigned'].includes(r.status)?button('已知原意／需要換作品','request',`data-id="${esc(r.id)}"`,true):''}</div></article>`).join('');
 return `<section class="next-step"><div><p class="eyebrow">現在這一步</p><h2>${esc(title)}</h2><p>${esc(description)}</p></div><span class="next-symbol" aria-hidden="true">↗</span></section>${a.kind==='w8-proposal'?'<p><a href="'+esc(b.relatedActivityId?'?activity='+encodeURIComponent(b.relatedActivityId):'?week=8')+'">查看本組題材與原文 →</a></p>':''}${aiJudgment.panel()}${activityFlow(b)}${invites}${weekly.boardTools(a)}${topics.panel()}<nav class="view-switch" aria-label="作品與任務"><button data-action="studentView" data-view="work" aria-controls="studentWork">我的作品${w?.feedback.length?` <span class="count">${w.feedback.length} 則回饋</span>`:''}</button>${a.kind==='w4'||b.reviews.length?`<button data-action="studentView" data-view="reader" aria-controls="studentReader">我的初讀任務 <span class="count">${b.reviews.length}</span></button>`:''}</nav><section id="studentWork" class="panel student-panel" aria-label="我的作品">${b.works.length?b.works.map(w=>workCard(w,false)).join(''):a.kind==='w5-personal'?'<p class="muted">選定題目後，這裡會出現你的上傳入口。</p>':`<div class="empty-state"><h3>${a.archived||!a.accepting||!supported(a)?'目前沒有你的作品紀錄':b.invitations.length?'小組名單更新中':'從第一份作品開始'}</h3><p>${a.archived||!a.accepting||!supported(a)?'這個活動目前僅供查閱，不能建立或上傳作品。':isGroup(a.kind)?'只有代表建立小組，再用座號加入組員；其他同學不用先建立。':'準備好作品後，建立自己的作品並上傳。'}</p>${!a.archived&&a.accepting&&!b.invitations.length&&supported(a)?button(isGroup(a.kind)?'建立我的小組':'建立我的作品','ensureWork'):''}</div>`}</section><section id="studentReader" class="panel" aria-label="我的初讀任務" hidden><p>「初讀」是先自己看圖，寫下你讀到的意思與畫面根據，再把這份回饋交給作者。</p>${tasks||'<div class="empty-state"><h3>目前沒有初讀任務</h3><p>老師安排後，任務會出現在這裡。先依課堂指示完成自己的作品。</p></div>'}</section>`;
}
function setStudentView(view){state.studentView=view;$('#studentWork').hidden=view!=='work';$('#studentReader').hidden=view!=='reader';document.querySelectorAll('[data-action="studentView"]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.view===view)));}
function workCard(w,teacher){const group=isGroup(state.board.activity.kind),members=w.members.filter(m=>m.status==='confirmed'),former=w.members.filter(m=>m.status==='declined');return `<article class="work"><h3>${teacher?esc(members.map(m=>`${m.seat} 號 ${m.name}`).join('、')||'原小組作品（目前無組員）'):'我的作品'}</h3>${group?`<section class="group-members" aria-label="本組成員"><h4>本組成員 · ${members.length} 人</h4><p>${members.map(m=>`${esc(m.seat)} 號 ${esc(m.name)}`).join('、')||'目前無組員'}</p>${!teacher&&!state.board.activity.archived?`<div class="group-exit"><button class="leave-group" data-action="leaveGroup" data-id="${esc(w.id)}">離開這個小組</button><p>${state.board.activity.kind==='w7-news'&&w.topic?'本組已抽題。離組不會取得重抽機會；分組有誤請先請老師核對。':'分錯組或自己建錯組？先離開，再請正確小組的代表加入你。'}</p></div>`:''}${teacher&&former.length?`<details><summary>先前成員（已離組）</summary><p>${former.map(m=>`${esc(m.seat)} 號 ${esc(m.name)}`).join('、')}</p></details>`:''}</section>`:''}<div class="row">${w.versions.map(v=>button(state.board.activity.kind==='w8-proposal'?'查看已交提案（第 '+v.ordinal+' 版）':'查看 V'+v.ordinal,'view',`data-id="${esc(v.id)}"`,true)).join('')}
${!teacher&&canUpload(state.board.activity,w)&&(state.board.activity.kind!=='w8-proposal'||state.w8MaterialsBoard?.works[0]?.topic)&&(!['w5-personal','w7-news'].includes(state.board.activity.kind)||w.topic)?button(w.versions.length?(state.board.activity.kind==='w8-proposal'?'照片不清楚或有修改？補傳':'保存新版本'):state.board.activity.kind==='w5-personal'?'② 上傳一張作品':state.board.activity.kind==='w7-news'?'上傳圖卡＋ORID交流紀錄':state.board.activity.kind==='w9-check'?'填資料依據與提案，附 p.1':state.board.activity.kind==='w8-proposal'?'上傳我的提案書 p.2':'上傳 V1','upload',`data-id="${esc(w.id)}"`):''}
${!teacher&&!state.board.activity.archived&&state.board.activity.accepting&&isGroup(state.board.activity.kind)&&!w.versions.length?button('加入同組同學','invite',`data-id="${esc(w.id)}"`,true):''}${weekly.workTools(w,teacher)}</div>${teacher&&topicById(w.topic)?`<p>選題：${esc(w.topic)} · ${esc(topicById(w.topic).title)}</p>`:''}
${teacher&&!state.board.activity.archived&&state.home.person.role==='admin'&&state.board.activity.testOnly&&state.board.activity.kind==='w4'&&w.versions.length&&!w.feedback.length?button('送出示範讀者回饋（測試）','testFeedback',`data-id="${esc(w.id)}"`,true):''}
${remediation.workTools(w,teacher)}${w.feedback.map(r=>`<div class="feedback"><strong>同學的回饋</strong><p>情境：${esc(r.situation)}</p><p>意思：${esc(r.meaning)}</p>${button('查看與回覆','conversation',`data-id="${esc(r.id)}"`,true)}</div>`).join('')}
${!teacher&&!state.board.activity.archived&&state.board.activity.accepting&&['review','exhibit'].includes(state.board.activity.phase)&&(w.hasHumanFeedback??w.feedback.length)&&state.board.activity.kind==='w4'&&w.versions.length?button('有理由保留目前版本','keep',`data-id="${esc(w.id)}"`,true):''}
${['w5-personal','w9-check'].includes(state.board.activity.kind)&&w.reflection?`<section class="feedback"><h4>${teacher?'學生的':'我的'} ORID · V${w.versions.find(v=>v.id===w.reflection.versionId)?.ordinal||'？'} · ${w.reflection.status==='submitted'?'已送出':'草稿'}</h4>${w.reflection.versionId!==w.current_version_id?'<p>這份反思對應先前版本，原文保留；可開啟 ORID，對照目前圖卡核對。</p>':''}${[['o','O｜看見'],['r','R｜感受'],['id','I＋D｜學習與運用']].map(([k,l])=>'<p><strong>'+l+'</strong>：'+esc(w.reflection.answers[k])+'</p>').join('')}</section>`:''}
${w.decisions.map(d=>`<p class="muted">${d.choice==='keep'?'保留':'修改'}：${esc(d.reason)}</p>`).join('')}
${teacher&&!state.board.activity.archived&&state.board.activity.kind==='w4'&&!state.board.reviews.some(r=>r.target_work_id===w.id)?button('這份還沒有讀者：安排補位','assign',`data-id="${esc(w.id)}"`,true):''}${teacher&&!state.board.activity.archived&&state.board.activity.kind==='w4'&&w.versions.length?button('查看證據與評閱','assess',`data-id="${esc(w.id)}"`,true):''}
${w.grades.map(g=>`<p>教師評閱：${esc(g.comment)}${g.status==='graded'?' · '+(g.legacy_payload?(g.legacy_score===null?'未登分':esc(g.legacy_score)+'／'+esc(g.legacy_max)):(g.criteria.reduce((a,n)=>a+n,0)/12*20).toFixed(2)+'／20'):''}${g.legacy_payload?'（原系統評閱）':''}</p>`).join('')}
${!teacher?`<div class="privacy-setting"><p>${['w8-proposal','w9-check'].includes(state.board.activity.kind)?'課堂提案不會自動對外公開。':w.members.some(m=>m.status==='confirmed'&&m.sharing_opt_out)?'本作品不公開。'+(group?'小組任一成員選擇不公開，整份作品就不展示。':''):'公開設定：預設匿名展示。'+(state.config.acceptanceOnly?'驗收站不對外公開。':'')}</p>${button(w.members.find(m=>m.student_id===state.home.person.studentId)?.sharing_opt_out?(['w8-proposal','w9-check'].includes(state.board.activity.kind)?'允許教師審查後展示':'恢復預設公開'):(['w8-proposal','w9-check'].includes(state.board.activity.kind)?'不參與對外展示':'不公開'),'workPrivacy',`data-id="${esc(w.id)}" data-public="${w.members.find(m=>m.student_id===state.home.person.studentId)?.sharing_opt_out?'true':'false'}"`,true)}<p class="muted">此設定不影響交件、回饋與評閱，之後重傳也會保留。</p></div>`:''}
${w.publication_hold?'<p class="notice">老師已暫停此作品的公開展示；重傳也不會自動上架。課堂作品仍保留。</p>':''}${w.publications.some(p=>p.status==='published')?'<p class="muted">已匿名展示</p>':''}${teacher?w.publications.map(p=>button(p.status==='published'?(p.reviewed_by?'已檢查／撤下展示':'已公開 · 待老師檢查'):'檢查匿名展示','publication',`data-id="${esc(p.id)}" data-work="${esc(w.id)}"`,true)).join(' '):''}</article>`;}
function teacherPanel(b){
 if(b.activity.kind==='w8-materials')return w8TeacherPanel(b);
 const missing=missingStudents(state.roster,b),pending=b.reviews.filter(r=>r.status!=='done'),requested=pending.filter(r=>r.status==='requested');
 const person=id=>{const s=state.roster.find(s=>s.student_id===id);return s?`${s.seat} 號 ${s.name}`:id;};
 return `${weekly.boardTools(b.activity,true)}<section class="panel teacher-overview"><div class="section-title"><label class="class-filter">查看班級<select id="classChoice" aria-label="查看班級">${state.classes.map(c=>`<option ${c===state.className?'selected':''}>${esc(c)}</option>`).join('')}</select></label><div class="row">${!b.activity.archived&&b.activity.kind==='w4'?button('隨機配對／補齊缺額','dispatch')+button('提醒未交者補交','reminderPlan','',true):''}${!b.activity.archived&&supported(b.activity)&&state.home.person.role==='admin'?button(b.activity.kind==='w8-proposal'?'開放／關閉個人交件':'課堂開關','control','',true):''}</div></div><div class="stats"><div><strong>${b.works.filter(w=>w.versions.length).length}</strong><span>份已交作品</span></div><div><strong>${missing.length}</strong><span>人尚未交件</span></div>${b.activity.kind==='w4'?`<div><strong>${b.reviews.filter(r=>r.status==='assigned'&&!r.teacherCovered).length}</strong><span>份等讀者初讀</span></div><div><strong>${b.works.filter(w=>w.hasHumanFeedback).length}</strong><span>份已有真人初讀</span></div>`:`<div><strong>${b.works.length}</strong><span>份已建立作品</span></div><div><strong>${b.works.reduce((n,w)=>n+w.members.filter(m=>m.status==='confirmed').length,0)}</strong><span>人列入作品</span></div>`}</div><p class="muted small-text">${b.activity.kind==='w8-proposal'?'每人各交一份提案；小組已抽題不代表組員已交件。':'作品以份數計，小組成員的交件狀態合併計入；完成數不代表評閱結果。'}</p>${missing.length?`<details class="queue"><summary>尚未交件名單 · ${missing.length} 人</summary><p>${missing.map(s=>esc(s.seat+' 號 '+s.name)).join('、')}</p></details>`:''}${pending.length?`<details class="queue" ${requested.length?'open':''}><summary>追蹤讀者任務 · ${pending.length} 份${requested.length?'，其中 '+requested.length+' 份申請協助':''}</summary>${[...pending].sort((a,b)=>(b.status==='requested')-(a.status==='requested')).map(r=>`<div class="queue-row"><div><strong>${esc(person(r.reviewer_id))}</strong><p class="muted">${r.teacherCovered?'已由老師補讀；原讀者仍可補充。':''}${{waiting:'等作者上傳 · 讀者位置已保留',assigned:'待送出初讀',requested:'申請換作品'}[r.status]}${r.reason?'：'+esc(r.reason):''}</p></div>${!b.activity.archived?button('手動更換讀者','replace',`data-id="${esc(r.id)}"`,true):''}</div>`).join('')}</details>`:''}</section><section class="panel works-panel"><div class="section-title"><h2>班級作品</h2><span id="workCount" class="muted" role="status"></span></div><div class="work-filters"><label>搜尋學生<input id="workSearch" type="search" placeholder="姓名、座號或學號" value="${esc(state.query)}" autocomplete="off"></label><label>作品狀態<select id="workFilter">${[['all','全部作品'],['missing','尚未上傳'],...(b.activity.kind==='w4'?[['feedback','已上傳，尚無初讀'],['unpaired','尚未安排讀者'],['ungraded','尚未完成正式評閱']]:[]),['moderation','公開作品待檢查']].map(([k,v])=>`<option value="${k}" ${state.workFilter===k?'selected':''}>${v}</option>`).join('')}</select></label></div><div id="works"></div></section>`;
}
function renderWorks(){
 if(state.board.activity.kind==='w8-materials')return w8RenderWorks();
 const b=state.board,works=b.works.filter(w=>matchesWork(w,b,state.workFilter,state.query)).sort((a,b)=>(a.members.find(m=>m.status==='confirmed')?.seat||999)-(b.members.find(m=>m.status==='confirmed')?.seat||999));
 $('#workCount').textContent=`${works.length} / ${b.works.length} 份`;
 $('#works').innerHTML=works.map(w=>{const f=workFlags(w,b),names=w.members.filter(m=>m.status==='confirmed').map(m=>`${m.seat} 號 ${m.name}`).join('、')||'原小組作品（目前無組員）';return `<details class="work-summary" data-work-details="${esc(w.id)}"><summary><span class="student-names">${esc(names)}<small>${w.versions.length?'最新 V'+w.versions.at(-1).ordinal+' · '+w.versions.length+' 個版本':'作品位置已建立，尚未上傳'}</small></span><span class="work-badges"><span class="tag ${f.uploaded?'':'warm'}">${f.uploaded?'已交件':'待上傳'}</span>${f.uploaded&&b.activity.kind==='w4'?`<span class="tag ${f.feedback?'':'warm'}">${esc(remediation.status(w))}</span>`:''}${f.moderation?'<span class="tag warm">待檢查公開</span>':''}</span><span class="expand-label">查看詳情</span></summary><div class="work-detail">${workCard(w,true)}</div></details>`;}).join('')||`<div class="empty-state"><h3>${b.works.length?'沒有符合條件的作品':'這一班還沒有建立作品'}</h3><p>${b.works.length?'試著更換狀態，或清除搜尋文字。':'學生開始交件後，作品會出現在這裡。'}</p>${b.works.length?button('清除篩選','clearFilters','',true):''}</div>`;
}
async function images(versionId,container){container.innerHTML='<p class="muted" role="status">正在讀取作品圖片……</p>';let r;try{r=await api('media',{versionId});}catch(e){container.innerHTML='<p class="error" role="alert">圖片暫時無法讀取，請關閉後重新開啟作品。</p>';throw e;}container.innerHTML=`${r.metadata?.title?'<h3>'+esc(r.metadata.title)+'</h3>':''}${w9Evidence(r.metadata,esc)}${r.metadata?.text?'<p class="work-text">'+esc(r.metadata.text)+'</p>':''}${r.metadata?.topic?'<p>題目：'+esc(topicById(r.metadata.topic)?r.metadata.topic+' · '+topicById(r.metadata.topic).title:r.metadata.topic==='Z'?'動物園':r.metadata.topic==='M'?'校園手機':r.metadata.topic)+'</p>':''}${r.metadata?.purpose?'<p>'+esc(r.metadata.purpose)+'</p>':''}${r.contextImages?.length?'<h3>V1 原作品</h3><div class="images">'+r.contextImages.map(m=>`<img src="${esc(m.url)}" alt="V1 原作品">`).join('')+'</div><h3>V2 修訂處</h3>':''}<div class="images">${r.images.map((m,i)=>`<a href="${esc(m.url)}" target="_blank" rel="noopener noreferrer"><img src="${esc(m.url)}" alt="作品 V${r.ordinal} 第 ${i+1} 張" decoding="async"></a>`).join('')}</div>`;if(r.projectUrl)await weekly.project(r.projectUrl,container);}
function workById(id){return state.board.works.find(w=>w.id===id);}
async function action(el){const a=el.dataset.action,id=el.dataset.id;if(a==='maintenance'){const m=await api('maintenance');show(`<h2>系統維護與備份</h2><p>每日資料庫快照：${m.dailyConfigured?'已設定每日凌晨約 3–4 點（臺灣時間）':'排程尚未設定'}</p><p>最近成功：${m.last?esc(new Date(m.last.at).toLocaleString('zh-TW')):'尚無成功紀錄'}</p>${m.stale||m.failedAfterSuccess?'<p class="error">最近備份逾時或有失敗紀錄，請聯絡維護者檢查。</p>':''}<p>每日快照包含名單、作品版本索引、回饋及評閱，經讀回核對。不含圖片本體；完整離線備份需由維護工具另存圖片與資料庫。</p><p>R2 憑證交接紀錄到期日：${esc(m.tokenReviewDate)}。需在到期前由維護者核對及續換。</p>${m.canRun?button('立即建立資料快照','backupRun'):''}<p id="formStatus" role="status"></p>`);return;}if(a==='backupRun'){await api('backupRun',{},true);say('資料庫快照已保存並讀回核對。圖片本體不包含在本次快照。');dialog.close();return;}if(await journey.action(el))return;if(await rosterUI.action(el))return;if(await accounts.action(el))return;if(await weekly.action(el))return;if(await topics.action(el))return;if(await aiJudgment.action(el))return;if(await remediation.action(el))return;
  if(a==='studentView'){setStudentView(el.dataset.view);return;}if(a==='clearFilters'){state.workFilter='all';state.query='';$('#workFilter').value='all';$('#workSearch').value='';renderWorks();$('#workSearch').focus();return;}
  if(a==='sharingInfo'){show(agreementContent());return;}if(a==='workPrivacy'){const open=el.dataset.public==='true';await api('consent',{workId:id,consent:open},true);await board();say(open?'已恢復本人的預設公開設定；仍尊重其他組員的不公開選擇及老師的停展設定。':'本作品已設為不公開，交件與回饋照常。');return;}
  if(a==='termManager')return termManager();if(a==='termEdit')return termEdit(id);if(a==='termSummary')return termSummary(id);if(a==='termCodes')return downloadCodes();
  if(a==='termBackup'){const r=await api('termBackup',{jobId:id});show(`<h2>切換前備份</h2><p>含名單與登入驗證資料，僅供管理教師保管。</p><a href="${esc(r.url)}" download rel="noopener noreferrer">下載私人備份（連結 120 秒有效）</a>`);return;}

  if(a==='testFeedback'){await api('testFeedback',{workId:id},true);say('已留下標示為系統測試的示範回饋。');return board();}
  if(a==='archive'){const data=await api('archive');show('<h2>原系統完整封存</h2><p>僅管理教師可查閱；保留原始內容及核對雜湊。</p>'+data.tables.map(t=>button(esc(t.source_table)+' · '+t.count+' 筆','archiveTable',`data-id="${esc(t.source_table)}"`,true)).join(' '));return;}if(a==='archiveTable'){const data=await api('archive',{table:id,offset:el.dataset.offset||0});show('<h2>原始封存紀錄</h2>'+data.records.map(r=>`<details><summary>${esc(r.source_id)}</summary><pre class="archive-record">${esc(JSON.stringify(r.payload,null,2))}</pre><small>${esc(r.source_hash)}</small></details>`).join('')+(data.next!==null?button('下一頁','archiveTable',`data-id="${esc(id)}" data-offset="${data.next}"`):''));return;}if(a==='home'){history.replaceState(null,'',previewUrl(location.pathname));return home();}if(a==='activity')return openActivity(id);if(a==='refresh'){await board();say('作品與回饋已更新。');return;}
  if(a==='w8StartUpload'){await api('ensureWork',{activityId:state.activity},true);await board();return weekly.uploadForm(state.board.works[0]);}
  if(a==='ensureWork'){await api(a,{activityId:state.activity},true);return board();}
  if(a==='leaveGroup'){const w=workById(id);show(`<h2>離開這個小組？</h2><p>離開後，你不再列為本組成員，也不能編輯或選錄本組作品。之後請正確小組的代表用座號加入你。</p>${w.versions.length?'<p class="notice">已有作品與操作紀錄會保留給原組與老師；對外展示暫停，請老師核對後恢復。</p>':'<p>若只是自己誤建空白小組，也可以在這裡離開。</p>'}<form id="leaveGroup" data-id="${esc(id)}" data-revision="${w.revision}"><p id="formStatus" role="status"></p><div class="row"><button class="leave-group">確認離開這個小組</button><button type="button" class="secondary" data-action="cancelGroupLeave">留在小組</button></div></form>`);return;}
  if(a==='cancelGroupLeave'){dialog.close();return;}
  if(a==='view'){show('<h2>作品版本</h2><div id="media"></div>');return images(id,$('#media'));}
  if(a==='upload'){weekly.uploadForm(workById(id));return;}
  if(a==='read'){const r=state.board.reviews.find(x=>x.id===id);show(`<h2>先自己看圖，寫下你讀到的意思</h2><div id="media"></div><form id="review" data-id="${esc(id)}"><label>① 發生什麼事？指出畫面根據。<textarea name="situation" required maxlength="1200"></textarea></label><label>② 讀到什麼關係、心情或意味？根據在哪裡？<textarea name="meaning" required maxlength="1200"></textarea></label><p class="muted">拿不準可以說明。送出後保留這次獨立初讀，不用猜作者的標準答案。</p><p id="formStatus" role="status"></p><label><input type="checkbox" required>我還不知道作者原意，這是我看圖後的獨立理解。</label><button>送出我的初讀</button></form>`);return images(r.version_id,$('#media'));}
  if(a==='keep'||a==='request'){show(`<h2>${a==='keep'?'說明保留的依據':'請老師協助換作品'}</h2><form id="${a}" data-id="${esc(id)}"><label>${a==='keep'?'比對真人回饋、原本想表達的意思與畫面線索，我保留的理由是':'換作品原因'}<textarea name="reason" required maxlength="1200"></textarea></label><p id="formStatus"></p><button>保存</button></form>`);return;}
  if(a==='invite'){show(`<h2>加入同組同學</h2><p>班級：<strong>${esc(state.home.person.className)} 班</strong>（依你的登入帳號）</p><form id="invite" data-id="${esc(id)}"><label>同班組員座號<input name="seats" placeholder="例如：5、12、23" autocomplete="off" maxlength="40" required aria-describedby="seatHelp"></label><p id="seatHelp" class="muted">可用頓號、逗號或空白分隔。不用填自己，最多加入三位同學。</p><div id="invitePreview" aria-live="polite"></div><p>核對姓名後直接加入，不用組員再次確認。若分錯組，本人可按「離開這個小組」，再請正確小組的代表加入。</p><p id="formStatus" role="status"></p><button id="inviteSubmit">核對組員</button></form>`);return;}
  if(a==='dispatch'){
    const r=await api('roster',{activityId:state.activity,className:state.className}),students=r.students.filter(s=>s.is_test===state.board.activity.testOnly&&s.active);
    show(`<h2>${esc(state.className)} 班 · 隨機配對讀者</h2><p class="notice">預設全班參與。每人讀另一人的作品，奇數也能配對；不會配到自己。</p><p>保留已完成及進行中的配對，補齊空缺與申請換件的任務。優先找沒有待辦的同學，必要時請已完成者補讀一份；每人同時最多一份待回饋或等待作品的任務。</p>${state.board.activity.phase==='exhibit'?'<p class="notice">目前是第三階段「課程展示」，仍可補配讀者；學生仍可留下回饋，決定修改或保留作品，不必切回第二階段。</p>':''}${!state.board.activity.accepting?'<p class="error">目前尚未開放交件與保存；可先安排讀者，再由「課堂開關」開放保存，學生才能送出回饋。</p>':''}<form id="dispatch" data-total="${students.length}"><details class="dispatch-absence"><summary id="absenceSummary">有缺席？設定不參與名單（目前 0 人）</summary><p class="muted">只勾選本次缺席或暫不參與的人。已完成回饋保留；缺席者尚未完成的任務會嘗試交給其他讀者。</p><fieldset><legend>勾選者不加入本次新配對</legend><div class="dispatch-roster">${students.map(s=>`<label><input type="checkbox" name="absent" value="${esc(s.student_id)}">${s.seat} 號 ${esc(s.name)}</label>`).join('')}</div></fieldset></details><div class="dispatch-actions"><p id="dispatchCount" aria-live="polite">本次參與 ${students.length} 人 · 不參與 0 人</p><p id="formStatus" role="status"></p><button id="dispatchSubmit">開始隨機配對／補齊缺額</button></div></form>`);return;
  }
  if(a==='replace'||a==='assign'){const r=await api('roster',{activityId:state.activity,className:state.className});show(`<h2>手動指定另一位讀者</h2><form id="replace" data-operation="${a}" data-id="${esc(id)}"><label>補位同學<select name="studentId">${r.students.filter(s=>s.active&&s.is_test===state.board.activity.testOnly).map(s=>`<option value="${s.student_id}">${s.seat} 號 ${esc(s.name)}</option>`).join('')}</select></label><label><input type="checkbox" name="extra">若已完成一份，我已安排他補位再讀一份</label><p id="formStatus"></p><button>保存補位</button></form>`);return;}
  if(a==='control'&&state.board.activity.kind==='w8-materials'){show(`<h2>W8 題材分配</h2><form id="control"><input type="hidden" name="phase" value="production"><label><input type="checkbox" name="accepting" ${state.board.activity.accepting?'checked':''}>開放建立小組、加入組員與抽題</label><p>已抽題材保留可讀；關閉不會清除分配。此活動不收作品、不進行展示或評分。</p><p id="formStatus"></p><button>保存</button></form>`);return;}
  if(a==='control'){show(`<h2>課堂開關</h2><form id="control"><label>目前階段<select name="phase"><option value="production">製作與上傳</option>${state.board.activity.kind==='w4'?'<option value="review">獨立初讀與修改或保留</option>':'<option value="review">製作後核對與修改</option>'}<option value="exhibit">課程展示</option></select></label><label><input type="checkbox" name="accepting" ${state.board.activity.accepting?'checked':''}>開放交件與保存</label><p>課程展示開放同活動的兩班作品展覽；W3 可欣賞交流。W7／公共說明的回饋仍留歷程本。W4 展示階段仍可補配、完成回饋，決定修改或保留作品；已完成紀錄保留。</p><p id="formStatus"></p><button>更新課堂狀態</button></form>`);$('#control').elements.phase.value=state.board.activity.phase;return;}
  if(a==='aiReading')return openReading(id);
  if(a==='assess'){const w=workById(id),e=await api('evidence',{workId:id});const member=w.members.find(m=>m.status==='confirmed'),old=w.grades.find(g=>g.student_id===member.student_id);show(`<h2>W4–W5 個人作品評閱</h2><p>合看學生自己的圖卡、真人回饋（同學或老師親自初讀）、修改或保留的決定與 W5 平台判讀；平台完成數不等於達標。</p>${remediation.feedback(w)}${aiJudgment.assessment(e.judgments)}<div class="row">${w.versions.map(v=>button('打開 V'+v.ordinal,'assessmentMedia',`data-id="${v.id}"`,true)).join('')}</div><div id="assessmentMedia"></div><form id="assess" data-id="${esc(id)}" data-student="${member.student_id}" data-key="${e.key}" data-revision="${old?.revision||0}">${['素材與表達目的','畫面與文字安排','真人接收與判讀','改留決定與依據'].map((label,i)=>`<label>${label}<select name="c${i}"><option value="">尚未評定</option>${[0,1,2,3].map(n=>`<option ${old?.criteria[i]===n?'selected':''}>${n}</option>`).join('')}</select></label>`).join('')}<label>評閱依據／補件說明<textarea name="comment" maxlength="2000">${esc(old?.comment||'')}</textarea></label><label>狀態<select name="status"><option value="draft">評分草稿</option><option value="needs-evidence">待補證據</option><option value="graded">正式評閱</option></select></label><label><input type="checkbox" name="checked">我已親自合看 W4–W5 本人證據</label><p id="formStatus"></p><button>保存評閱</button></form>`);return;}
  if(a==='conversation'){const c=await api('conversation',{reviewId:id});show(`<h2>把理解說清楚</h2><p>第一次看圖寫下的回饋保留原樣；這裡接著詢問或回應。</p><div class="feedback"><p>${esc(c.review.situation)}</p><p>${esc(c.review.meaning)}</p></div>${c.replies.map(r=>`<div class="feedback"><strong>${{author:'作者',reader:'讀者',teacher:'老師'}[r.label]}</strong><p>${esc(r.body)}</p></div>`).join('')}${state.board.activity.archived?'<p>此學期已封存，對話僅供查閱。</p>':`<form id="reply" data-id="${esc(id)}"><label>我的回應<textarea name="body" required maxlength="1200"></textarea></label><p id="formStatus"></p><button>送出回覆</button></form>`}`);return;}if(a==='assessmentMedia')return images(id,$('#assessmentMedia'));
  if(a==='publication'){const w=workById(el.dataset.work),p=w.publications.find(x=>x.id===id);show(`<h2>檢查匿名展示</h2><div id="media"></div><form id="publication" data-id="${esc(id)}"><label>匿名標題<input name="title" value="匿名作品" maxlength="80" required></label><label><input type="checkbox" name="reviewed">已逐張檢查，圖片與文字沒有姓名、班級座號、可辨識個人或私人對話</label><p>確認圖片與標題本身沒有個資。原意、回饋、成績不進入公開展廳。撤下會暫停整份作品自動上架，保留課堂版本；由老師重新確認公開後恢復。</p><p id="formStatus"></p>${state.board.activity.archived||state.config.acceptanceOnly?'':'<button name="publish" value="yes">確認已檢查並公開</button>'}${state.config.acceptanceOnly?'<p class="notice">驗收站可檢查圖片與練習撤下，不會對外公開。</p>':''} <button name="publish" value="no" class="secondary">撤下展示</button></form>`);return images(p.version_id,$('#media'));}
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)guard(()=>action(el));});
document.addEventListener('change',e=>{if(e.target.form?.id==='dispatch'&&e.target.name==='absent'){const total=Number(e.target.form.dataset.total),absent=e.target.form.querySelectorAll('input[name=absent]:checked').length;$('#absenceSummary').textContent=`有缺席？設定不參與名單（目前 ${absent} 人）`;$('#dispatchCount').textContent=`本次參與 ${total-absent} 人 · 不參與 ${absent} 人`;}if(e.target.id==='termView'){state.termView=e.target.value;renderHome();}if(['upload','referenceUpload'].includes(e.target.form?.id))delete e.target.form.dataset.request;if(e.target.id==='classChoice'){const selected=e.target.value;if(state.busy){e.target.value=state.className;return;}guard(async()=>{const previous=state.className,previousRoster=state.roster;state.className=selected;state.query='';state.workFilter='all';try{await loadRoster();await board();}catch(err){state.className=previous;state.roster=previousRoster;e.target.value=previous;throw err;}});}if(e.target.id==='workFilter'){state.workFilter=e.target.value;renderWorks();}if(e.target.type==='file'){const preview=$('#localPreview');if(preview){preview.querySelectorAll('img').forEach(img=>URL.revokeObjectURL(img.src));preview.innerHTML='';for(const input of e.target.form.querySelectorAll('input[type=file]'))for(const file of input.files){const img=new Image();img.src=URL.createObjectURL(file);img.alt='準備上傳的作品';preview.append(img);}if($('#upload'))delete $('#upload').dataset.request;}}});
document.addEventListener('input',e=>{if(e.target.form?.id==='upload')delete e.target.form.dataset.request;if(e.target.name==='seats'&&e.target.form?.id==='invite'){delete e.target.form.dataset.preview;$('#invitePreview').innerHTML='';$('#inviteSubmit').textContent='核對組員';$('#formStatus').textContent='';}if(e.target.id==='workSearch'){state.query=e.target.value;renderWorks();}});
async function uploadFile(url,file,onProgress){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',url);xhr.setRequestHeader('Content-Type',file.type);xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(e.loaded/e.total);};xhr.timeout=120000;xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve():reject(new Error('圖片尚未傳完，請保留選圖後重試。'));xhr.onerror=()=>reject(new Error('網路中斷，請保留選圖後重試。'));xhr.ontimeout=()=>reject(new Error('圖片上傳逾時，請重試。'));xhr.send(file);});}
document.addEventListener('submit',e=>{e.preventDefault();const form=e.target,values=new FormData(form),get=n=>values.get(n);guard(async()=>{
  if(await journey.submit(form,values))return;if(await rosterUI.submit(form,values))return;if(await accounts.submit(form,values))return;if(await weekly.submit(form,values,e.submitter))return;if(await topics.submit(form,values))return;if(await aiJudgment.submit(form,values,e.submitter))return;if(await remediation.submit(form,values,e.submitter))return;
  if(form.id==='login'){await api('login',{term:get('term'),studentId:get('studentId'),code:get('code'),remember:values.has('remember')},true);form.reset();say('登入成功。');return home();}
  if(form.id==='agreement'){await api('agreement',{accepted:values.has('accepted'),version:state.home.sharingAgreement.version},true);await home();say('已保存本學期的展示設定；每份作品都可單獨選擇不公開。');return;}
  if(form.id==='termSave'){
    const result=await api('termSave',{term:get('term'),sourceTerm:state.termData.currentTerm,rosterText:get('rosterText'),teachers:values.getAll('teachers'),expectedRevision:Number(form.dataset.revision),reissueNewCodes:values.has('reissue')},true);
    if(result.issuedCodes.length)state.issued={term:result.draft.term,codes:result.issuedCodes};
    state.dirty=false;dialog.close();await termManager();termSummary(result.draft.term);say('草稿已儲存，目前學期沒有切換。');return;
  }
  if(form.id==='termActivate'){
    const result=await api('termActivate',{term:form.dataset.term,expectedRevision:Number(form.dataset.revision),confirmTerm:get('confirmTerm'),confirm:values.has('confirmed'),ackUnsupported:values.has('unsupported')},true);
    state.dirty=false;state.issued=null;dialog.close();state.termView=result.term;state.config.currentTerm=result.term;await home();say('已備份並啟用 '+result.term+'。舊學期保留查閱，新活動需課前開放。');return;
  }
  const id=form.dataset.id;
  if(form.id==='upload'){
    const w=workById(form.dataset.work);const raw=[...form.querySelectorAll('input[type=file]')].flatMap(input=>[...input.files]);const files=await weekly.compress(raw);const info=await weekly.fileInfo(files);
    form.dataset.request||=crypto.randomUUID();$('#formStatus').textContent='準備上傳……';
    const prepared=await api('prepare',{workId:w.id,requestId:form.dataset.request,expectedRevision:w.revision,files:info,topics:[get('topicA'),get('topicB')],text:get('text'),title:get('title'),...(state.board.activity.kind==='w9-check'?w9Values(values):{}),topic:['w5-personal','w7-news','w8-proposal'].includes(state.board.activity.kind)?w.topic:get('topic'),layout:get('layout'),purpose:get('purpose')},true);
    if(!prepared.versionId){for(let i=0;i<files.length;i++)await uploadFile(prepared.files[i].url,files[i],fraction=>{$('#uploadProgress').value=(i+fraction)/files.length*90;$('#formStatus').textContent=`正在上傳第 ${i+1} 張……`;});$('#formStatus').textContent='圖片已傳完，正在確認保存……';await api('finalize',{ticketId:prepared.ticketId,reason:get('reason')},true);}
  }
  else if(form.id==='review'){const r=state.board.reviews.find(x=>x.id===id);await api('review',{reviewId:id,expectedRevision:r.revision,situation:get('situation'),meaning:get('meaning')},true);}
  else if(form.id==='reply'){form.dataset.request||=crypto.randomUUID();await api('reply',{reviewId:id,body:get('body'),requestId:form.dataset.request},true);}
  else if(form.id==='keep'){const w=workById(id);await api('decision',{workId:id,versionId:w.versions.at(-1).id,reason:get('reason')},true);}
  else if(form.id==='request')await api('requestReplacement',{reviewId:id,reason:get('reason')},true);
  else if(form.id==='leaveGroup')await api('leaveGroup',{workId:id,expectedRevision:Number(form.dataset.revision),confirmed:true},true);
  else if(form.id==='invite'){
    const raw=String(get('seats')).normalize('NFKC').trim(),parts=raw.split(/[,、;\s]+/);if(!parts.length||parts.length>3||parts.some(x=>!/^\d{1,3}$/.test(x)))throw new Error('請輸入一至三位同班座號，例如 5、12、23。');
    const seats=parts.map(Number);if(seats.some(n=>n<1)||new Set(seats).size!==seats.length)throw new Error('請核對座號，不要重複填寫。');
    if(!form.dataset.preview){
      const r=await api('invitePreview',{workId:id,seats},true);if(form.elements.seats.value.normalize('NFKC').trim()!==raw)throw new Error('座號已修改，請重新核對。');
      form.dataset.preview=JSON.stringify(r);$('#invitePreview').innerHTML=`<div class="notice"><strong>核對 ${esc(r.className)} 班的同學</strong><ul>${r.students.map(s=>`<li>${s.seat} 號 · ${esc(s.name)}</li>`).join('')}</ul><p>這一步尚未加入。姓名正確後，再按下方按鈕。</p></div>`;$('#inviteSubmit').textContent='確認姓名，加入小組';$('#formStatus').textContent='請核對上方座號與姓名。';return;
    }
    const preview=JSON.parse(form.dataset.preview);
    try{await api('invite',{workId:id,seats,expectedStudentIds:preview.students.map(s=>s.studentId)},true);}catch(e){delete form.dataset.preview;$('#invitePreview').innerHTML='';$('#inviteSubmit').textContent='核對組員';throw e;}
  }
  else if(form.id==='dispatch'){const r=await api('dispatch',{activityId:state.activity,className:state.className,expectedRevision:state.board.activity.revision,absentIds:values.getAll('absent')},true);state.dirty=false;dialog.close();await board();show(`<h2>讀者安排結果</h2><p class="notice">已安排 ${r.added} 份任務，包含 ${r.replaced} 份換讀者、${r.extra} 份由已完成者補讀。</p>${r.waiting?`<h3>仍有 ${r.waiting} 份作品需要讀者</h3><ul>${r.unmatched.map(w=>`<li><strong>${esc(w.seat)} 號 ${esc(w.name)}</strong>：${esc(w.reason)}</li>`).join('')}</ul><p>等同學完成手上的回饋，或有其他同學恢復參與後，再按「補齊缺額」。</p>`:'<p>本次參與且可分派的作品都有讀者。已有的回饋保留；安排完成不代表讀者已送出回饋。</p>'}`);return;}
  else if(form.id==='replace')await api(form.dataset.operation==='assign'?'assignReader':'replace',{reviewId:id,workId:id,studentId:get('studentId'),confirmExtra:values.has('extra')},true);
  else if(form.id==='control')await api('control',{activityId:state.activity,expectedRevision:state.board.activity.revision,phase:get('phase'),accepting:values.has('accepting')},true);
  else if(form.id==='assess')await api('assess',{workId:id,studentId:form.dataset.student,evidenceKey:form.dataset.key,expectedRevision:Number(form.dataset.revision),criteria:[0,1,2,3].map(i=>get('c'+i)===''?null:Number(get('c'+i))),comment:get('comment'),status:get('status'),evidenceReviewed:values.has('checked')},true);
  else if(form.id==='publication')await api('publish',{publicationId:id,title:get('title'),reviewed:values.has('reviewed'),publish:e.submitter?.value==='yes'},true);
  else return;
  state.dirty=false;dialog.close();if(form.id!=='dispatch')say(form.id==='invite'?'組員已直接加入。請組員進入同一活動，更新後即可看到共同作品。':form.id==='leaveGroup'?'已離開小組，請正確小組的代表用座號加入你。':'✓ 已保存。');await board();
});});
$('#logout').onclick=()=>guard(async()=>{if(state.dirty&&!confirm('還有未保存內容，確定登出？'))return;await api('logout',{},true);state.home=null;state.activity=null;state.board=null;state.dirty=false;state.issued=null;state.termData=null;dialog.close();$('#logout').hidden=true;$('#identity').textContent='保存自己的安排，聽見讀者的理解，再決定修改或保留。';login();say('已登出。');});
// Small cursor check only; never replaces a form or downloads the class wall in the background.
setInterval(async()=>{if(!state.activity||state.busy||document.hidden)return;try{const r=await api('updates',{activityId:state.activity});if(state.cursor!==null&&state.cursor!==r.cursor){say('有新的作品或回饋，按「更新作品與回饋」查看。');if(!dialog.open&&!state.dirty&&!document.activeElement?.matches('input,select,textarea'))await guard(board);}state.cursor=r.cursor;}catch{}},15000);
await guard(async()=>{const config=await api('config');state.config=config;$('#environment').hidden=!config.acceptanceOnly;if(!config.enabled){app.innerHTML='<section class="panel narrow"><h2>新作品區準備中</h2><p>目前請繼續使用原作品牆，原作品與登入碼仍保留。</p><a class="button" href="/portfolio/">回原作品牆入口</a></section>';return;}try{await home();}catch(error){if(previewActive)throw error;login();}});
