import {phaseLabel,supported,workFlags,matchesWork,missingStudents,studentNext} from './ui-model.js';
const $=s=>document.querySelector(s),app=$('#app'),notice=$('#notice'),dialog=$('#detail');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={config:null,home:null,activity:null,board:null,className:'',cursor:null,busy:false,dirty:false,termView:null,termData:null,issued:null,classes:[],roster:[],workFilter:'all',query:'',studentView:'work'};
const button=(label,action,data='',secondary=false)=>`<button ${secondary?'class="secondary"':''} data-action="${action}" ${data}>${label}</button>`;
async function api(action,data={},write=false){const response=await fetch('/api/workspace'+(write?'':'?'+new URLSearchParams({action,...data})),{method:write?'POST':'GET',credentials:'same-origin',headers:write?{'Content-Type':'application/json'}:{},...(write?{body:JSON.stringify({action,...data})}:{})});const payload=await response.json();if(!payload.ok)throw new Error(payload.error||'暫時無法完成，請稍後再試。');return payload.data;}
function say(s,error=false){notice.textContent=s;notice.className=error?'error':'';}
function show(html){$('#detailBody').innerHTML=html;const title=$('#detailBody h2');if(title){title.id='dialogTitle';dialog.setAttribute('aria-labelledby','dialogTitle');}if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}
function heading(title,subtitle=''){document.querySelector('.intro h1').textContent=title;$('#pageSubtitle').textContent=subtitle;document.title=title+'｜閱讀理解與表達';}
$('#closeDialog').onclick=()=>{if(state.busy)return;if(state.dirty&&!confirm('內容還沒送出。確定關閉？'))return;state.dirty=false;dialog.close();};
dialog.addEventListener('cancel',e=>{if(state.busy||state.dirty)e.preventDefault();});
document.addEventListener('input',e=>{if(e.target.closest('#detail'))state.dirty=true;});
window.addEventListener('beforeunload',e=>{if(state.busy||state.dirty){e.preventDefault();e.returnValue='';}});
async function guard(fn){if(state.busy)return;state.busy=true;document.body.classList.add('busy');app.setAttribute('aria-busy','true');const active=document.activeElement,btn=active?.tagName==='BUTTON'?active:null;if(btn)btn.disabled=true;try{await fn();}catch(e){say(e.message,true);const inline=$('#formStatus');if(inline)inline.textContent=e.message;}finally{state.busy=false;document.body.classList.remove('busy');app.removeAttribute('aria-busy');if(btn?.isConnected)btn.disabled=false;}}
function login(){$('#identity').textContent='';heading('每一次理解，都留下來。','保存作品、聽見同學的理解，再決定改或留。');app.innerHTML=`<div class="login-layout"><section class="panel login-card"><p class="eyebrow">STUDENT · 學生入口</p><h2>回到我的作品</h2><p class="muted">使用原本的學號與個人六碼。</p><form id="login"><label>學號<input name="studentId" inputmode="numeric" autocomplete="username" pattern="[0-9]{8}" placeholder="輸入 8 碼學號" required></label><label>個人六碼<input name="code" type="password" inputmode="numeric" autocomplete="current-password" pattern="[0-9]{6}" maxlength="6" placeholder="輸入老師發的 6 碼" required></label><label>學期<input name="term" inputmode="numeric" pattern="[0-9]{3}0[12]" value="${esc(state.config?.currentTerm||'11501')}" required></label><label class="check-row"><input type="checkbox" name="remember">這是我的裝置，記住登入 30 天</label><p id="formStatus" role="status"></p><button class="full-width">進入我的作品</button></form><p class="muted small-text">共用裝置請勿勾選記住登入。忘記六碼時請洽老師。</p></section><aside class="login-aside"><p class="eyebrow">TEACHER · 教師入口</p><h2>掌握全班的進度</h2><p>查看兩班作品、安排讀者、回應學生，並保留每一學期的學習歷程。</p>${state.config?.teacherLogin?'<a class="button" href="/api/workspace?action=teacher-start">以 Google 教師帳號登入 →</a>':'<p class="muted">教師 Google 登入設定中。</p>'}<div class="login-note"><strong>作品屬於學習，選擇留給自己。</strong><p>作品預設匿名展示；每件作品都能選擇不公開，交件與回饋照常。</p></div></aside></div>`;}
async function home(){say('');state.home=await api('home');state.activity=null;state.board=null;const p=state.home.person;$('#identity').textContent=p.role==='student'?`${p.className} 班 ${p.seat} 號 · ${p.name}`:`${p.name} · 教師管理`;$('#logout').hidden=false;
  renderHome();window.scrollTo(0,0);if(!state.home.agreementRequired){const week=Number(new URLSearchParams(location.search).get('week'));if([4,5].includes(week)){const target=state.home.activities.find(a=>a.week===week&&!a.archived&&supported(a)&&a.test_only===(p.role==='student'&&p.isTest===true));history.replaceState(null,'',location.pathname);if(target)await openActivity(target.id);}}}
function renderHome(){
 if(state.home.agreementRequired){renderAgreement();return;}
 const p=state.home.person,teacher=p.role!=='student',terms=[...new Set(state.home.activities.map(a=>a.term))];
 if(!terms.includes(state.termView))state.termView=terms.includes(state.home.currentTerm)?state.home.currentTerm:terms[0];
 heading(teacher?'教學工作台':'我的學習作品',teacher?'先選活動，再查看班級進度與需要協助的同學。':'選擇課堂正在進行的活動，接著完成自己的下一步。');
 const activities=state.home.activities.filter(a=>!teacher||a.term===state.termView),current=activities.filter(a=>supported(a)&&!a.archived),history=activities.filter(a=>!current.includes(a));
 const cards=list=>list.map(a=>`<button class="card activity-card" data-action="activity" data-id="${esc(a.id)}"><span class="card-top"><span class="week-mark">W${a.week}</span><span class="tag">${a.test_only?'測試活動':esc(phaseLabel(a,state.config))}</span></span><strong>${esc(a.title.replace(/^W\d+\s*/,''))}</strong><span class="muted">${a.kind==='w4'?'個人圖卡 · 真人初讀 · 改或留':a.kind==='w5-workshop'?'小組作品 · A、B 題各一張':'歷史紀錄 · 僅供查閱'}</span><span class="card-bottom">${esc(a.term)} 學期<span>${teacher?'查看班級':'進入作品'} →</span></span></button>`).join('');
 app.innerHTML=`<div class="home-toolbar"><div class="row">${teacher?`<label class="term-filter">查看學期<select id="termView">${terms.map(t=>`<option value="${esc(t)}" ${state.termView===t?'selected':''}>${esc(t)}${state.home.currentTerm===t?' · 目前學期':' · 歷史查閱'}</option>`).join('')}</select></label>`:`<span class="tag">${esc(state.home.currentTerm)} 學期</span>`}</div><div class="row">${p.role==='admin'?button('學期管理','termManager','',true)+button('搬遷封存紀錄','archive','',true):''}${!teacher?button('匿名展示說明','sharingInfo','',true):''}</div></div><section aria-labelledby="activitiesTitle"><div class="section-title"><h2 id="activitiesTitle">課堂活動</h2><span class="muted">${current.length} 個活動</span></div><div class="grid activity-grid">${cards(current)||'<div class="empty-state">目前沒有開放的課堂活動，可在下方查閱歷史紀錄。</div>'}</div></section>${history.length?`<details class="history-section" ${current.length?'':'open'}><summary>歷史與封存活動 · ${history.length}</summary><p class="muted">保留原有作品與學習紀錄。</p><div class="grid">${cards(history)}</div></details>`:''}`;
}
function agreementContent(){const a=state.home.sharingAgreement;return `<h2>${esc(a.title)}</h2>${a.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}`;}
function renderAgreement(){heading("開始之前，先了解作品怎麼展示","每學期確認一次，每件作品仍可自行選擇不公開。");app.innerHTML=`<section class="panel agreement-panel">${agreementContent()}<form id="agreement"><label><input type="checkbox" name="accepted" required>我已閱讀並同意上述匿名展示與個資保護說明，知道可以逐件選擇不公開。</label><p id="formStatus" role="status"></p><button>同意並進入作品區</button></form></section>`;}
const rosterText=students=>students.map(s=>[s.studentId,s.name,s.className,s.seat].join('\t')).join('\n');
async function termManager(){
 heading('學期管理','先準備與核對，再切換。既有作品與登入碼保留。');state.activity=null;state.board=null;state.termData=await api('terms');const t=state.termData;
 app.innerHTML=`${button('← 回作品首頁','home','',true)}<section class="panel"><h2>學期管理</h2><p>目前學期：<strong>${esc(t.currentTerm)}</strong>。查閱其他學期不會改變學生入口。</p><p>新學期先存草稿；核對名單、共同授課教師與活動後，再啟用。既有作品與歷史不覆蓋。</p>${!t.activationAllowed?'<p class="notice">驗收站可以儲存草稿；正式啟用功能保持關閉，目前學期不受影響。</p>':''}${button('準備新學期','termEdit')}<h3>學期草稿</h3>${t.drafts.filter(d=>d.status==='draft').map(d=>`<article class="work"><strong>${esc(d.sourceTerm)} → ${esc(d.term)}</strong><p>${d.summary.total} 人 · ${d.summary.classes.map(esc).join('、')} 班 · 第 ${d.revision} 版</p>${button('核對摘要','termSummary',`data-id="${esc(d.term)}"`,true)} ${button('編輯草稿','termEdit',`data-id="${esc(d.term)}"`,true)}</article>`).join('')||'<p class="muted">尚未建立新學期草稿。</p>'}<h3>切換紀錄</h3>${t.history.map(h=>`<article class="work"><p>${esc(h.from_term)} → ${esc(h.to_term)} · ${esc(h.actor)} · ${esc(h.created_at)}</p>${button('下載切換前備份','termBackup',`data-id="${esc(h.id)}"`,true)}</article>`).join('')||'<p class="muted">目前沒有切換紀錄。</p>'}</section>`;
}
function termEdit(term){const t=state.termData,d=t.drafts.find(d=>d.term===term),source=t.currentTerm,next=source?.endsWith('01')?source.slice(0,3)+'02':String(Number(source?.slice(0,3))+1)+'01';
 show(`<h2>準備新學期</h2><p>來源學期 ${esc(source)}；儲存草稿不會切換入口，也不會關閉舊活動。</p><form id="termSave" data-revision="${d?.revision||0}"><label>新學期代碼<input name="term" value="${esc(d?.term||next)}" pattern="[0-9]{3}0[12]" ${d?'readonly':''} required></label><label>新學期學生名單<textarea name="rosterText" class="roster-input" maxlength="26000" required spellcheck="false">${esc(rosterText(d?.students||t.roster))}</textarea></label><p class="muted">從試算表複製四欄：學號、姓名、班級、座號（Tab 分隔，可含標題）。預填的是原名單，請核對轉班與離班；測試帳號不帶入。</p><fieldset><legend>共同授課教師（皆可查看與評閱新學期所有班級）</legend>${t.teachers.map(x=>`<label><input type="checkbox" name="teachers" value="${esc(x.email)}" ${(!d||d.teachers.includes(x.email))?'checked':''}>${esc(x.name)} · ${esc(x.email)}${x.role==='admin'?'（管理員）':''}</label>`).join('')}</fieldset><p>原學生沿用六碼，新生自動產生六碼。新生碼只在產生後提供下載，請立即保存，系統不存明文。</p>${d?'<label><input type="checkbox" name="reissue">重新產生此草稿新生的六碼（原學生六碼不變）</label>':''}<p id="formStatus" role="status"></p><button>儲存草稿並核對</button></form>`);
}
function termSummary(term){const d=state.termData.drafts.find(d=>d.term===term),s=d.summary,t=state.termData;const names=ids=>ids.map(id=>d.students.find(s=>s.studentId===id)?.name||t.roster.find(s=>s.studentId===id)?.name||id).map(esc).join('、');
 show(`<h2>核對 ${esc(d.sourceTerm)} → ${esc(d.term)}</h2><p>第 ${d.revision} 版 · ${s.total} 人 · ${s.classes.map(esc).join('、')} 班</p><ul><li>沿用六碼 ${s.retained.length} 人</li><li>新生 ${s.added.length} 人：${names(s.added)||'無'}</li><li>轉班／座號變更 ${s.moved.length} 人：${names(s.moved)||'無'}</li><li>本期不列入 ${s.removed.length} 人：${names(s.removed)||'無'}；舊作品仍保留。</li></ul><p>共同授課：${d.teachers.map(e=>esc(t.teachers.find(x=>x.email===e)?.name||e)).join('、')}，均可看與評閱全部班級；既有管理員仍保有管理權限。</p><details><summary>核對完整名單與 ${s.activityCount} 個活動</summary><pre class="archive-record">${esc(rosterText(d.students))}</pre><ul>${d.templates.map(a=>`<li>W${a.week} · ${esc(a.title)}</li>`).join('')}</ul></details>${state.issued?.term===term&&state.issued.codes.length?`<p class="notice">請先下載並妥善保存新生六碼，關閉頁面後不再顯示。</p>${button('下載新生登入碼（文字檔）','termCodes','',true)}`:''}${s.unavailable.length?`<p class="notice">下列歷史模式尚未完成新系統操作，只保留活動設定並停寫：${s.unavailable.map(esc).join('、')}。需要使用時仍走原入口。</p>`:''}<p>啟用前會將完整資料快照存入私有儲存空間，並讀回核對；失敗則整次切換取消。新活動先停寫，由老師課前開放。</p>${t.activationAllowed?`<form id="termActivate" data-term="${esc(term)}" data-revision="${d.revision}"><label><input name="confirmed" type="checkbox" required>已核對名單、登入碼及共同授課權限</label>${s.unavailable.length?'<label><input name="unsupported" type="checkbox" required>我已確認歷史模式仍需原入口，尚不能完整取代舊系統</label>':''}<label>輸入 ${esc(term)} 確認啟用<input name="confirmTerm" autocomplete="off" required pattern="${esc(term)}"></label><p id="formStatus" role="status"></p><button>備份並啟用新學期</button></form>`:'<p class="notice">驗收期間不能正式啟用。你可以核對、編輯草稿，目前學期維持不變。</p>'}`);
}
function downloadCodes(){const row=state.issued;if(!row)return;const safe=x=>String(x).replace(/[\t\r\n]/g,' ').replace(/^[=+@-]/,"'$&");const content='學期\t學號\t姓名\t班級\t座號\t六碼\n'+row.codes.map(c=>[row.term,c.studentId,c.name,c.className,c.seat,c.code].map(safe).join('\t')).join('\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+content],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`${row.term}-新生登入碼.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

async function loadRoster(){const r=await api('roster',{activityId:state.activity,className:state.className});state.roster=r.students;}
async function openActivity(activityId){say('');state.activity=activityId;state.cursor=null;state.workFilter='all';state.query='';state.studentView='work';const teacher=state.home.person.role!=='student';if(teacher){const r=await api('classes',{activityId});state.classes=r.classes;state.className=r.classes.includes(state.className)?state.className:r.classes[0]||'';if(state.className)await loadRoster();else state.roster=[];}await board();window.scrollTo(0,0);}
async function board(){
 const expanded=[...document.querySelectorAll('[data-work-details][open]')].map(el=>el.dataset.workDetails),queues=[...document.querySelectorAll('.queue')].map(el=>el.open),focusId=document.activeElement?.id,scroll=window.scrollY;
 const b=await api('board',{activityId:state.activity,...(state.className?{className:state.className}:{})});state.board=b;const teacher=state.home.person.role!=='student',a=b.activity;
 heading(a.title,teacher?(a.kind==='w4'?'查看全班進度，優先處理尚未收到回饋的作品。':'查看各組交件、成員確認與作品版本。'):(a.kind==='w4'?'保存自己的作品，也為另一位同學留下理解。':'小組共同保存 A、B 題，保留核對與修改歷程。'));
 app.innerHTML=`<div class="board-toolbar"><div class="row">${button('← 課堂活動','home','',true)}<span class="tag">${esc(phaseLabel(a,state.config))}</span>${a.testOnly?'<span class="tag test-tag">測試活動</span>':''}</div><button class="secondary refresh-button" data-action="refresh" aria-label="更新作品與回饋"><span class="refresh-long">更新作品與回饋</span><span class="refresh-short">更新</span></button></div>${a.archived?'<p class="notice">此學期已封存，作品、回饋與評閱保留查閱。</p>':''}${teacher?teacherPanel(b):studentPanel(b)}`;
 if(!teacher&&a.kind!=='w4'&&!b.reviews.length)state.studentView='work';
 if(teacher){renderWorks();for(const el of document.querySelectorAll('[data-work-details]'))el.open=expanded.includes(el.dataset.workDetails);document.querySelectorAll('.queue').forEach((el,i)=>{if(queues[i])el.open=true;});}else setStudentView(state.studentView);
 if(['classChoice','workFilter','workSearch'].includes(focusId))document.getElementById(focusId)?.focus({preventScroll:true});window.scrollTo(0,scroll);
}
function studentPanel(b){
 const a=b.activity,[title,description]=studentNext(b,state.config),w=b.works[0],invites=b.invitations.map(i=>`<div class="invitation"><h3>有一份小組邀請</h3><p>請先向同組同學核對。</p><div class="row">${button('是我的組，確認加入','accept',`data-id="${esc(i.id)}"`)}${button('不是我的組','decline',`data-id="${esc(i.id)}"`,true)}</div></div>`).join('');
 const tasks=b.reviews.map(r=>`<article class="reader-task"><span class="tag">${{waiting:'等待作品',assigned:'輪到我初讀',done:'已送出初讀',requested:'等待老師協助'}[r.status]||'初讀任務'}</span><h3>${{waiting:'作者還在製作，任務為你保留',assigned:'先看圖，再說出你的理解',done:'我的初讀已送出',requested:'已申請更換作品'}[r.status]||'查看任務'}</h3><p>${r.status==='waiting'?'晚交的同學也需要讀者；作品送到後會出現在這裡。':r.status==='assigned'&&a.phase==='production'?'等老師開放初讀後，就能打開作品。':r.status==='assigned'&&a.phase==='exhibit'?'目前是展示階段，已停止新增初讀。':r.status==='done'?'可以查看對話，接著向作者提問或回應。':'先獨立閱讀，不用猜作者的標準答案。'}</p><div class="row">${!a.archived&&r.status==='assigned'&&a.accepting&&a.phase==='review'?button('看圖並留下初讀','read',`data-id="${esc(r.id)}"`):''}${r.status==='done'?button('查看與回覆','conversation',`data-id="${esc(r.id)}"`,true):''}${!a.archived&&['waiting','assigned'].includes(r.status)?button('已知原意／需要換作品','request',`data-id="${esc(r.id)}"`,true):''}</div></article>`).join('');
 return `<section class="next-step"><div><p class="eyebrow">現在這一步</p><h2>${esc(title)}</h2><p>${esc(description)}</p></div><span class="next-symbol" aria-hidden="true">↗</span></section>${invites}<nav class="view-switch" aria-label="作品與任務"><button data-action="studentView" data-view="work" aria-controls="studentWork">我的作品${w?.feedback.length?` <span class="count">${w.feedback.length} 則初讀</span>`:''}</button>${a.kind==='w4'||b.reviews.length?`<button data-action="studentView" data-view="reader" aria-controls="studentReader">我的初讀任務 <span class="count">${b.reviews.length}</span></button>`:''}</nav><section id="studentWork" class="panel student-panel" aria-label="我的作品">${b.works.length?b.works.map(w=>workCard(w,false)).join(''):`<div class="empty-state"><h3>${a.archived||!a.accepting||!supported(a)?'目前沒有你的作品紀錄':b.invitations.length?'先確認邀請，再一起完成作品':'從第一份作品開始'}</h3><p>${a.archived||!a.accepting||!supported(a)?'這個活動目前僅供查閱，不能建立或上傳作品。':a.kind==='w4'?'準備好圖卡後，建立作品並上傳。':'小組先確認成員，由一位同學建立共同作品。'}</p>${!a.archived&&a.accepting&&!b.invitations.length&&supported(a)?button(a.kind==='w4'?'開始我的圖卡':'建立我的小組','ensureWork'):''}</div>`}</section><section id="studentReader" class="panel" aria-label="我的初讀任務" hidden>${tasks||'<div class="empty-state"><h3>目前沒有初讀任務</h3><p>老師安排後，任務會出現在這裡。先依課堂指示完成自己的作品。</p></div>'}</section>`;
}
function setStudentView(view){state.studentView=view;$('#studentWork').hidden=view!=='work';$('#studentReader').hidden=view!=='reader';document.querySelectorAll('[data-action="studentView"]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.view===view)));}
function workCard(w,teacher){return `<article class="work"><h3>${teacher?esc(w.members.filter(m=>m.status==='confirmed').map(m=>`${m.seat} 號 ${m.name}`).join('、')):'我的作品'}</h3>${w.members.length>1?`<p class="muted">${w.members.map(m=>`${esc(m.name)}${m.status==='invited'?'（待本人確認）':m.status==='declined'?'（未加入）':''}`).join('、')}</p>`:''}<div class="row">${w.versions.map(v=>button('查看 V'+v.ordinal,'view',`data-id="${esc(v.id)}"`,true)).join('')}
${!teacher&&!state.board.activity.archived&&state.board.activity.accepting&&['w4','w5-workshop'].includes(state.board.activity.kind)&&(state.board.activity.kind==='w5-workshop'||!w.versions.length||w.versions.length<2&&w.feedback.length&&state.board.activity.phase==='review')?button(state.board.activity.kind==='w5-workshop'?(w.versions.length?'更新兩張 A3':'上傳兩張 A3'):(w.versions.length?'保存新版本':'上傳 V1'),'upload',`data-id="${esc(w.id)}"`):''}
${!teacher&&!state.board.activity.archived&&state.board.activity.accepting&&state.board.activity.kind==='w5-workshop'&&!w.versions.length?button('邀請同組同學','invite',`data-id="${esc(w.id)}"`,true):''}</div>
${teacher&&!state.board.activity.archived&&state.home.person.role==='admin'&&state.board.activity.testOnly&&state.board.activity.kind==='w4'&&w.versions.length&&!w.feedback.length?button('送出示範讀者回饋（測試）','testFeedback',`data-id="${esc(w.id)}"`,true):''}
${w.feedback.map(r=>`<div class="feedback"><strong>同學的初讀</strong><p>情境：${esc(r.situation)}</p><p>意思：${esc(r.meaning)}</p>${button('查看與回覆','conversation',`data-id="${esc(r.id)}"`,true)}</div>`).join('')}
${!teacher&&!state.board.activity.archived&&state.board.activity.accepting&&state.board.activity.phase==='review'&&w.feedback.length&&state.board.activity.kind==='w4'&&w.versions.length?button('有理由保留目前版本','keep',`data-id="${esc(w.id)}"`,true):''}
${w.decisions.map(d=>`<p class="muted">${d.choice==='keep'?'保留':'修改'}：${esc(d.reason)}</p>`).join('')}
${teacher&&!state.board.activity.archived&&state.board.activity.kind==='w4'&&!state.board.reviews.some(r=>r.target_work_id===w.id)?button('這份還沒有讀者：安排補位','assign',`data-id="${esc(w.id)}"`,true):''}${teacher&&!state.board.activity.archived&&state.board.activity.kind==='w4'&&w.versions.length?button('查看證據與評閱','assess',`data-id="${esc(w.id)}"`,true):''}
${w.grades.map(g=>`<p>教師評閱：${esc(g.comment)}${g.status==='graded'?' · '+(g.legacy_payload?(g.legacy_score===null?'未登分':esc(g.legacy_score)+'／'+esc(g.legacy_max)):(g.criteria.reduce((a,n)=>a+n,0)/12*20).toFixed(2)+'／20'):''}${g.legacy_payload?'（原系統評閱）':''}</p>`).join('')}
${!teacher?`<div class="privacy-setting"><p>${w.members.some(m=>m.status==='confirmed'&&m.sharing_opt_out)?'本作品不公開。小組任一成員選擇不公開，整份作品就不展示。':'公開設定：預設匿名展示。'+(state.config.acceptanceOnly?'驗收站不對外公開。':'')}</p>${button(w.members.find(m=>m.student_id===state.home.person.studentId)?.sharing_opt_out?'恢復預設公開':'不公開','workPrivacy',`data-id="${esc(w.id)}" data-public="${w.members.find(m=>m.student_id===state.home.person.studentId)?.sharing_opt_out?'true':'false'}"`,true)}<p class="muted">此設定不影響交件、回饋與評閱，之後重傳也會保留。</p></div>`:''}
${w.publication_hold?'<p class="notice">老師已暫停此作品的公開展示；重傳也不會自動上架。課堂作品仍保留。</p>':''}${w.publications.some(p=>p.status==='published')?'<p class="muted">已匿名展示</p>':''}${teacher?w.publications.map(p=>button(p.status==='published'?(p.reviewed_by?'已檢查／撤下展示':'已公開 · 待老師檢查'):'檢查匿名展示','publication',`data-id="${esc(p.id)}" data-work="${esc(w.id)}"`,true)).join(' '):''}</article>`;}
function teacherPanel(b){
 const missing=missingStudents(state.roster,b),pending=b.reviews.filter(r=>r.status!=='done'),requested=pending.filter(r=>r.status==='requested');
 const person=id=>{const s=state.roster.find(s=>s.student_id===id);return s?`${s.seat} 號 ${s.name}`:id;};
 return `<section class="panel teacher-overview"><div class="section-title"><label class="class-filter">查看班級<select id="classChoice">${state.classes.map(c=>`<option ${c===state.className?'selected':''}>${esc(c)}</option>`).join('')}</select></label><div class="row">${!b.activity.archived&&b.activity.kind==='w4'?button('安排／補配讀者','dispatch'):''}${!b.activity.archived&&supported(b.activity)&&state.home.person.role==='admin'?button('課堂開關','control','',true):''}</div></div><div class="stats"><div><strong>${b.works.filter(w=>w.versions.length).length}</strong><span>份已交作品</span></div><div><strong>${missing.length}</strong><span>人尚未交件</span></div>${b.activity.kind==='w4'?`<div><strong>${b.reviews.filter(r=>r.status==='assigned').length}</strong><span>份等讀者初讀</span></div><div><strong>${b.reviews.filter(r=>r.status==='done').length}</strong><span>份已完成初讀</span></div>`:`<div><strong>${b.works.length}</strong><span>份已建立作品</span></div><div><strong>${b.works.reduce((n,w)=>n+w.members.filter(m=>m.status==='invited').length,0)}</strong><span>人待確認加入</span></div>`}</div><p class="muted small-text">作品以份數計，小組成員的交件狀態合併計入；完成數不代表評閱結果。</p>${missing.length?`<details class="queue"><summary>尚未交件名單 · ${missing.length} 人</summary><p>${missing.map(s=>esc(s.seat+' 號 '+s.name)).join('、')}</p></details>`:''}${pending.length?`<details class="queue" ${requested.length?'open':''}><summary>追蹤讀者任務 · ${pending.length} 份${requested.length?'，其中 '+requested.length+' 份申請協助':''}</summary>${[...pending].sort((a,b)=>(b.status==='requested')-(a.status==='requested')).map(r=>`<div class="queue-row"><div><strong>${esc(person(r.reviewer_id))}</strong><p class="muted">${{waiting:'等作者上傳 · 讀者位置已保留',assigned:'待送出初讀',requested:'申請換作品'}[r.status]}${r.reason?'：'+esc(r.reason):''}</p></div>${!b.activity.archived?button('安排補位','replace',`data-id="${esc(r.id)}"`,true):''}</div>`).join('')}</details>`:''}</section><section class="panel works-panel"><div class="section-title"><h2>班級作品</h2><span id="workCount" class="muted" role="status"></span></div><div class="work-filters"><label>搜尋學生<input id="workSearch" type="search" placeholder="姓名、座號或學號" value="${esc(state.query)}" autocomplete="off"></label><label>作品狀態<select id="workFilter">${[['all','全部作品'],['missing','尚未上傳'],...(b.activity.kind==='w4'?[['feedback','已上傳，尚無初讀'],['unpaired','尚未安排讀者'],['ungraded','尚未完成正式評閱']]:[]),['moderation','公開作品待檢查']].map(([k,v])=>`<option value="${k}" ${state.workFilter===k?'selected':''}>${v}</option>`).join('')}</select></label></div><div id="works"></div></section>`;
}
function renderWorks(){
 const b=state.board,works=b.works.filter(w=>matchesWork(w,b,state.workFilter,state.query)).sort((a,b)=>(a.members.find(m=>m.status==='confirmed')?.seat||999)-(b.members.find(m=>m.status==='confirmed')?.seat||999));
 $('#workCount').textContent=`${works.length} / ${b.works.length} 份`;
 $('#works').innerHTML=works.map(w=>{const f=workFlags(w,b),names=w.members.filter(m=>m.status==='confirmed').map(m=>`${m.seat} 號 ${m.name}`).join('、')||'待確認成員';return `<details class="work-summary" data-work-details="${esc(w.id)}"><summary><span class="student-names">${esc(names)}<small>${w.versions.length?'最新 V'+w.versions.at(-1).ordinal+' · '+w.versions.length+' 個版本':'作品位置已建立，尚未上傳'}</small></span><span class="work-badges"><span class="tag ${f.uploaded?'':'warm'}">${f.uploaded?'已交件':'待上傳'}</span>${f.uploaded&&b.activity.kind==='w4'?`<span class="tag ${f.feedback?'':'warm'}">${f.feedback?w.feedback.length+' 則初讀':'等候初讀'}</span>`:''}${f.moderation?'<span class="tag warm">待檢查公開</span>':''}</span><span class="expand-label">查看詳情</span></summary><div class="work-detail">${workCard(w,true)}</div></details>`;}).join('')||`<div class="empty-state"><h3>${b.works.length?'沒有符合條件的作品':'這一班還沒有建立作品'}</h3><p>${b.works.length?'試著更換狀態，或清除搜尋文字。':'學生開始交件後，作品會出現在這裡。'}</p>${b.works.length?button('清除篩選','clearFilters','',true):''}</div>`;
}
async function images(versionId,container){container.innerHTML='<p class="muted" role="status">正在讀取作品圖片……</p>';let r;try{r=await api('media',{versionId});}catch(e){container.innerHTML='<p class="error" role="alert">圖片暫時無法讀取，請關閉後重新開啟作品。</p>';throw e;}container.innerHTML=`<div class="images">${r.images.map((m,i)=>`<a href="${esc(m.url)}" target="_blank" rel="noopener noreferrer"><img src="${esc(m.url)}" alt="作品 V${r.ordinal} 第 ${i+1} 張" decoding="async"></a>`).join('')}</div>`;}
function workById(id){return state.board.works.find(w=>w.id===id);}
async function action(el){const a=el.dataset.action,id=el.dataset.id;
  if(a==='studentView'){setStudentView(el.dataset.view);return;}if(a==='clearFilters'){state.workFilter='all';state.query='';$('#workFilter').value='all';$('#workSearch').value='';renderWorks();$('#workSearch').focus();return;}
  if(a==='sharingInfo'){show(agreementContent());return;}if(a==='workPrivacy'){const open=el.dataset.public==='true';await api('consent',{workId:id,consent:open},true);await board();say(open?'已恢復本人的預設公開設定；仍尊重其他組員的不公開選擇及老師的停展設定。':'本作品已設為不公開，交件與回饋照常。');return;}
  if(a==='termManager')return termManager();if(a==='termEdit')return termEdit(id);if(a==='termSummary')return termSummary(id);if(a==='termCodes')return downloadCodes();
  if(a==='termBackup'){const r=await api('termBackup',{jobId:id});show(`<h2>切換前備份</h2><p>含名單與登入驗證資料，僅供管理教師保管。</p><a href="${esc(r.url)}" download rel="noopener noreferrer">下載私人備份（連結 120 秒有效）</a>`);return;}

  if(a==='testFeedback'){await api('testFeedback',{workId:id},true);say('已留下標示為系統測試的示範回饋。');return board();}
  if(a==='archive'){const data=await api('archive');show('<h2>原系統完整封存</h2><p>僅管理教師可查閱；保留原始內容及核對雜湊。</p>'+data.tables.map(t=>button(esc(t.source_table)+' · '+t.count+' 筆','archiveTable',`data-id="${esc(t.source_table)}"`,true)).join(' '));return;}if(a==='archiveTable'){const data=await api('archive',{table:id,offset:el.dataset.offset||0});show('<h2>原始封存紀錄</h2>'+data.records.map(r=>`<details><summary>${esc(r.source_id)}</summary><pre class="archive-record">${esc(JSON.stringify(r.payload,null,2))}</pre><small>${esc(r.source_hash)}</small></details>`).join('')+(data.next!==null?button('下一頁','archiveTable',`data-id="${esc(id)}" data-offset="${data.next}"`):''));return;}if(a==='home')return home();if(a==='activity')return openActivity(id);if(a==='refresh'){await board();say('作品與回饋已更新。');return;}
  if(a==='ensureWork'){await api(a,{activityId:state.activity},true);return board();}
  if(a==='accept'||a==='decline'){await api('invitation',{activityId:state.activity,workId:id,accept:a==='accept'},true);return board();}
  if(a==='view'){show('<h2>作品版本</h2><div id="media"></div>');return images(id,$('#media'));}
  if(a==='upload'){const w=workById(id),workshop=state.board.activity.kind==='w5-workshop';show(`<h2>${workshop?'保存兩張 A3':'保存我的圖卡'}</h2><form id="upload" data-work="${esc(id)}"><p>每張最多 8 MB，支援 JPG、PNG、WebP。失敗可直接重試，已保存版本不會重複建立。</p>${workshop?'<label>A 區題號<select name="topicA">'+['A02','A03','A04','A05'].map(t=>`<option>${t}</option>`).join('')+'</select></label><label>A 題照片<input type="file" name="imageA" accept="image/jpeg,image/png,image/webp" required></label><label>B 區題號<select name="topicB">'+['B02','B03','B05','B06','B07','B08','B09','B10'].map(t=>`<option>${t}</option>`).join('')+'</select></label><label>B 題照片<input type="file" name="imageB" accept="image/jpeg,image/png,image/webp" required></label>':'<label>圖卡圖片<input type="file" name="imageA" accept="image/jpeg,image/png,image/webp" required></label>'}${!workshop&&w.versions.length?'<label>根據同學初讀，我改了什麼？<textarea name="reason" required maxlength="1200"></textarea></label>':''}<div id="localPreview" class="images"></div><p class="notice">作品預設匿名展示。若這份不想公開，可在當週作品按「不公開」；選擇會保留到後續版本。</p><p class="muted">請先裁掉或遮住圖片中的姓名、班級座號、人像與私人對話；系統不會自動辨識或遮字。測試作品不對外公開。</p><progress id="uploadProgress" max="100" value="0"></progress><p id="formStatus" role="status"></p><button>保存作品</button></form>`);return;}
  if(a==='read'){const r=state.board.reviews.find(x=>x.id===id);show(`<h2>先看圖，再說理解</h2><div id="media"></div><form id="review" data-id="${esc(id)}"><label>① 發生什麼事？指出畫面根據。<textarea name="situation" required maxlength="1200"></textarea></label><label>② 讀到什麼關係、心情或意味？根據在哪裡？<textarea name="meaning" required maxlength="1200"></textarea></label><p class="muted">拿不準可以說明。送出後保留這次獨立初讀，不用猜作者的標準答案。</p><p id="formStatus" role="status"></p><label><input type="checkbox" required>我還不知道作者原意，這是我看圖後的獨立理解。</label><button>送出我的初讀</button></form>`);return images(r.version_id,$('#media'));}
  if(a==='keep'||a==='request'){show(`<h2>${a==='keep'?'說明保留的依據':'請老師協助換作品'}</h2><form id="${a}" data-id="${esc(id)}"><label>${a==='keep'?'比對同學初讀與畫面，我保留的理由是':'換作品原因'}<textarea name="reason" required maxlength="1200"></textarea></label><p id="formStatus"></p><button>保存</button></form>`);return;}
  if(a==='invite'){show(`<h2>邀請同組同學</h2><p>班級：<strong>${esc(state.home.person.className)} 班</strong>（依你的登入帳號）</p><form id="invite" data-id="${esc(id)}"><label>同班組員座號<input name="seats" placeholder="例如：5、12、23" autocomplete="off" maxlength="40" required aria-describedby="seatHelp"></label><p id="seatHelp" class="muted">可用頓號、逗號或空白分隔。不用填自己，最多邀請三位同學。</p><div id="invitePreview" aria-live="polite"></div><p>先核對姓名再送出。每位同學仍須用自己的帳號確認加入。</p><p id="formStatus" role="status"></p><button id="inviteSubmit">核對組員</button></form>`);return;}
  if(a==='dispatch'){const r=await api('roster',{activityId:state.activity,className:state.className});show(`<h2>先安排讀者責任</h2><p>未交 V1 也能擔任讀者。保留已完成及正在進行的分派，只補尚未分派的作品。</p><form id="dispatch"><fieldset><legend>本次缺席／暫不參與</legend>${r.students.filter(s=>s.is_test===state.board.activity.testOnly&&s.active).map(s=>`<label><input type="checkbox" name="absent" value="${s.student_id}">${s.seat} 號 ${esc(s.name)}</label>`).join('')}</fieldset><p id="formStatus"></p><button>安排本班讀者</button></form>`);return;}
  if(a==='replace'||a==='assign'){const r=await api('roster',{activityId:state.activity,className:state.className});show(`<h2>安排另一位讀者</h2><form id="replace" data-operation="${a}" data-id="${esc(id)}"><label>補位同學<select name="studentId">${r.students.filter(s=>s.active&&s.is_test===state.board.activity.testOnly).map(s=>`<option value="${s.student_id}">${s.seat} 號 ${esc(s.name)}</option>`).join('')}</select></label><label><input type="checkbox" name="extra">若已完成一份，我已安排他補位再讀一份</label><p id="formStatus"></p><button>保存補位</button></form>`);return;}
  if(a==='control'){show(`<h2>課堂開關</h2><form id="control"><label>目前階段<select name="phase"><option value="production">製作與上傳</option><option value="review">獨立初讀與本人改留</option><option value="exhibit">班內展示</option></select></label><label><input type="checkbox" name="accepting" ${state.board.activity.accepting?'checked':''}>開放交件與保存</label><p>進入展示後停止新增初讀。已有紀錄仍保留。</p><p id="formStatus"></p><button>更新課堂狀態</button></form>`);$('#control').elements.phase.value=state.board.activity.phase;return;}
  if(a==='assess'){const w=workById(id),e=await api('evidence',{workId:id});const member=w.members.find(m=>m.status==='confirmed'),old=w.grades.find(g=>g.student_id===member.student_id);show(`<h2>W4–W5 個人作品評閱</h2><p>合看本人紙本、圖卡、同學初讀、改留與 W5 判讀；平台完成數不等於達標。</p><div class="row">${w.versions.map(v=>button('打開 V'+v.ordinal,'assessmentMedia',`data-id="${v.id}"`,true)).join('')}</div><div id="assessmentMedia"></div><form id="assess" data-id="${esc(id)}" data-student="${member.student_id}" data-key="${e.key}" data-revision="${old?.revision||0}">${['素材與表達目的','畫面與文字安排','真人接收與判讀','改留決定與依據'].map((label,i)=>`<label>${label}<select name="c${i}"><option value="">尚未評定</option>${[0,1,2,3].map(n=>`<option ${old?.criteria[i]===n?'selected':''}>${n}</option>`).join('')}</select></label>`).join('')}<label>評閱依據／補件說明<textarea name="comment" maxlength="2000">${esc(old?.comment||'')}</textarea></label><label>狀態<select name="status"><option value="draft">評分草稿</option><option value="needs-evidence">待補證據</option><option value="graded">正式評閱</option></select></label><label><input type="checkbox" name="checked">我已親自合看 W4–W5 本人證據</label><p id="formStatus"></p><button>保存評閱</button></form>`);return;}
  if(a==='conversation'){const c=await api('conversation',{reviewId:id});show(`<h2>把理解說清楚</h2><p>初讀保留原樣；這裡接著詢問或回應。</p><div class="feedback"><p>${esc(c.review.situation)}</p><p>${esc(c.review.meaning)}</p></div>${c.replies.map(r=>`<div class="feedback"><strong>${{author:'作者',reader:'讀者',teacher:'老師'}[r.label]}</strong><p>${esc(r.body)}</p></div>`).join('')}${state.board.activity.archived?'<p>此學期已封存，對話僅供查閱。</p>':`<form id="reply" data-id="${esc(id)}"><label>我的回應<textarea name="body" required maxlength="1200"></textarea></label><p id="formStatus"></p><button>送出回覆</button></form>`}`);return;}if(a==='assessmentMedia')return images(id,$('#assessmentMedia'));
  if(a==='publication'){const w=workById(el.dataset.work),p=w.publications.find(x=>x.id===id);show(`<h2>檢查匿名展示</h2><div id="media"></div><form id="publication" data-id="${esc(id)}"><label>匿名標題<input name="title" value="匿名作品" maxlength="80" required></label><label><input type="checkbox" name="reviewed">已逐張檢查，圖片與文字沒有姓名、班級座號、可辨識個人或私人對話</label><p>確認圖片與標題本身沒有個資。原意、回饋、成績不進入公開展廳。撤下會暫停整份作品自動上架，保留課堂版本；由老師重新確認公開後恢復。</p><p id="formStatus"></p>${state.board.activity.archived||state.config.acceptanceOnly?'':'<button name="publish" value="yes">確認已檢查並公開</button>'}${state.config.acceptanceOnly?'<p class="notice">驗收站可檢查圖片與練習撤下，不會對外公開。</p>':''} <button name="publish" value="no" class="secondary">撤下展示</button></form>`);return images(p.version_id,$('#media'));}
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)guard(()=>action(el));});
document.addEventListener('change',e=>{if(e.target.id==='termView'){state.termView=e.target.value;renderHome();}if(['topicA','topicB','privacyChecked','publicDisplay'].includes(e.target.name)&&$('#upload'))delete $('#upload').dataset.request;if(e.target.id==='classChoice'){const selected=e.target.value;if(state.busy){e.target.value=state.className;return;}guard(async()=>{const previous=state.className,previousRoster=state.roster;state.className=selected;state.query='';state.workFilter='all';try{await loadRoster();await board();}catch(err){state.className=previous;state.roster=previousRoster;e.target.value=previous;throw err;}});}if(e.target.id==='workFilter'){state.workFilter=e.target.value;renderWorks();}if(e.target.type==='file'){const preview=$('#localPreview');if(preview){preview.querySelectorAll('img').forEach(img=>URL.revokeObjectURL(img.src));preview.innerHTML='';for(const input of $('#upload').querySelectorAll('input[type=file]')){if(input.files[0]){const img=new Image();img.src=URL.createObjectURL(input.files[0]);img.alt='準備上傳的作品';preview.append(img);}}if($('#upload'))delete $('#upload').dataset.request;}}});
document.addEventListener('input',e=>{if(e.target.name==='seats'&&e.target.form?.id==='invite'){delete e.target.form.dataset.preview;$('#invitePreview').innerHTML='';$('#inviteSubmit').textContent='核對組員';$('#formStatus').textContent='';}if(e.target.id==='workSearch'){state.query=e.target.value;renderWorks();}});
async function uploadFile(url,file,onProgress){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',url);xhr.setRequestHeader('Content-Type',file.type);xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(e.loaded/e.total);};xhr.timeout=120000;xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve():reject(new Error('圖片尚未傳完，請保留選圖後重試。'));xhr.onerror=()=>reject(new Error('網路中斷，請保留選圖後重試。'));xhr.ontimeout=()=>reject(new Error('圖片上傳逾時，請重試。'));xhr.send(file);});}
document.addEventListener('submit',e=>{e.preventDefault();const form=e.target,values=new FormData(form),get=n=>values.get(n);guard(async()=>{
  if(form.id==='login'){await api('login',{term:get('term'),studentId:get('studentId'),code:get('code'),remember:values.has('remember')},true);form.reset();say('登入成功。');return home();}
  if(form.id==='agreement'){await api('agreement',{accepted:values.has('accepted'),version:state.home.sharingAgreement.version},true);await home();say('已保存本學期的展示設定；每份作品都可單獨選擇不公開。');return;}
  if(form.id==='termSave'){
    const result=await api('termSave',{term:get('term'),sourceTerm:state.termData.currentTerm,rosterText:get('rosterText'),teachers:values.getAll('teachers'),expectedRevision:Number(form.dataset.revision),reissueNewCodes:values.has('reissue')},true);
    if(result.issuedCodes.length)state.issued={term:result.draft.term,codes:result.issuedCodes};
    state.dirty=false;dialog.close();await termManager();termSummary(result.draft.term);say('草稿已儲存，目前學期沒有切換。');return;
  }
  if(form.id==='termActivate'){
    const result=await api('termActivate',{term:form.dataset.term,expectedRevision:Number(form.dataset.revision),confirmTerm:get('confirmTerm'),confirm:values.has('confirmed'),ackUnsupported:values.has('unsupported')},true);
    state.dirty=false;state.issued=null;dialog.close();state.termView=result.term;state.config.currentTerm=result.term;await home();say('已備份並啟用 '+result.term+'。舊學期保留查閱，新活動需課前開放。');return;
  }
  const id=form.dataset.id;
  if(form.id==='upload'){
    const w=workById(form.dataset.work),files=[get('imageA'),get('imageB')].filter(f=>f instanceof File&&f.size);if(files.some(f=>f.size>8*1024*1024))throw new Error('每張圖片最多 8 MB，請先縮小檔案。');
    const info=[];for(const f of files){const hash=await crypto.subtle.digest('SHA-256',await f.arrayBuffer());info.push({bytes:f.size,mime:f.type,sha256:[...new Uint8Array(hash)].map(v=>v.toString(16).padStart(2,'0')).join('')});}
    form.dataset.request||=crypto.randomUUID();$('#formStatus').textContent='準備上傳……';
    const prepared=await api('prepare',{workId:w.id,requestId:form.dataset.request,expectedRevision:w.revision,files:info,topics:[get('topicA'),get('topicB')]},true);
    if(!prepared.versionId){for(let i=0;i<files.length;i++)await uploadFile(prepared.files[i].url,files[i],fraction=>{$('#uploadProgress').value=(i+fraction)/files.length*90;$('#formStatus').textContent=`正在上傳第 ${i+1} 張……`;});$('#formStatus').textContent='圖片已傳完，正在確認保存……';await api('finalize',{ticketId:prepared.ticketId,reason:get('reason')},true);}
  }
  else if(form.id==='review'){const r=state.board.reviews.find(x=>x.id===id);await api('review',{reviewId:id,expectedRevision:r.revision,situation:get('situation'),meaning:get('meaning')},true);}
  else if(form.id==='reply'){form.dataset.request||=crypto.randomUUID();await api('reply',{reviewId:id,body:get('body'),requestId:form.dataset.request},true);}
  else if(form.id==='keep'){const w=workById(id);await api('decision',{workId:id,versionId:w.versions.at(-1).id,reason:get('reason')},true);}
  else if(form.id==='request')await api('requestReplacement',{reviewId:id,reason:get('reason')},true);
  else if(form.id==='invite'){
    const raw=String(get('seats')).normalize('NFKC').trim(),parts=raw.split(/[,、;\s]+/);if(!parts.length||parts.length>3||parts.some(x=>!/^\d{1,3}$/.test(x)))throw new Error('請輸入一至三位同班座號，例如 5、12、23。');
    const seats=parts.map(Number);if(seats.some(n=>n<1)||new Set(seats).size!==seats.length)throw new Error('請核對座號，不要重複填寫。');
    if(!form.dataset.preview){
      const r=await api('invitePreview',{workId:id,seats},true);if(form.elements.seats.value.normalize('NFKC').trim()!==raw)throw new Error('座號已修改，請重新核對。');
      form.dataset.preview=JSON.stringify(r);$('#invitePreview').innerHTML=`<div class="notice"><strong>確認邀請 ${esc(r.className)} 班的同學</strong><ul>${r.students.map(s=>`<li>${s.seat} 號 · ${esc(s.name)}</li>`).join('')}</ul><p>這一步尚未送出邀請。姓名正確後，再按下方按鈕。</p></div>`;$('#inviteSubmit').textContent='確認姓名，送出邀請';$('#formStatus').textContent='請核對上方座號與姓名。';return;
    }
    const preview=JSON.parse(form.dataset.preview);
    try{await api('invite',{workId:id,seats,expectedStudentIds:preview.students.map(s=>s.studentId)},true);}catch(e){delete form.dataset.preview;$('#invitePreview').innerHTML='';$('#inviteSubmit').textContent='核對組員';throw e;}
  }
  else if(form.id==='dispatch'){const r=await api('dispatch',{activityId:state.activity,className:state.className,expectedRevision:state.board.activity.revision,absentIds:values.getAll('absent')},true);say(`已新增 ${r.added} 份分派${r.waiting?'；仍有 '+r.waiting+' 份需安排補位':''}。`);}
  else if(form.id==='replace')await api(form.dataset.operation==='assign'?'assignReader':'replace',{reviewId:id,workId:id,studentId:get('studentId'),confirmExtra:values.has('extra')},true);
  else if(form.id==='control')await api('control',{activityId:state.activity,expectedRevision:state.board.activity.revision,phase:get('phase'),accepting:values.has('accepting')},true);
  else if(form.id==='assess')await api('assess',{workId:id,studentId:form.dataset.student,evidenceKey:form.dataset.key,expectedRevision:Number(form.dataset.revision),criteria:[0,1,2,3].map(i=>get('c'+i)===''?null:Number(get('c'+i))),comment:get('comment'),status:get('status'),evidenceReviewed:values.has('checked')},true);
  else if(form.id==='publication')await api('publish',{publicationId:id,title:get('title'),reviewed:values.has('reviewed'),publish:e.submitter?.value==='yes'},true);
  else return;
  state.dirty=false;dialog.close();if(form.id!=='dispatch')say(form.id==='invite'?'邀請已送出，請組員登入自己的帳號確認加入。':'✓ 已保存。');await board();
});});
$('#logout').onclick=()=>guard(async()=>{if(state.dirty&&!confirm('還有未保存內容，確定登出？'))return;await api('logout',{},true);state.home=null;state.activity=null;state.board=null;state.dirty=false;state.issued=null;state.termData=null;dialog.close();$('#logout').hidden=true;$('#identity').textContent='保存自己的安排，聽見讀者的理解，再決定改或留。';login();say('已登出。');});
// Small cursor check only; never replaces a form or downloads the class wall in the background.
setInterval(async()=>{if(!state.activity||state.busy||document.hidden)return;try{const r=await api('updates',{activityId:state.activity});if(state.cursor!==null&&state.cursor!==r.cursor){say('有新的作品或回饋，按「更新作品與回饋」查看。');if(!dialog.open&&!state.dirty&&!document.activeElement?.matches('input,select,textarea'))await guard(board);}state.cursor=r.cursor;}catch{}},15000);
await guard(async()=>{const config=await api('config');state.config=config;$('#environment').hidden=!config.acceptanceOnly;if(!config.enabled){app.innerHTML='<section class="panel narrow"><h2>新作品區準備中</h2><p>目前請繼續使用原作品牆，原作品與登入碼仍保留。</p><a class="button" href="/portfolio/">回原作品牆入口</a></section>';return;}try{await home();}catch{login();}});
